(function(g){var window=this;'use strict';var UT=function(I){I.publish("cardstatechange",I.i5()&&I.cE()?1:0)},t6=function(I,U){var t=g.Bk(U);
const W=t?U:arguments;for(t=t?0:1;t<W.length;t++){if(I==null)return;I=I[W[t]]}return I},vfQ=function(I){const U=g.UG(I);
I=g.lO(I);return new g.qu(U.x,U.y,I.width,I.height)},c$Q=function(I,U,t){let W;
return W=g.nC(I,U,function(){g.VR(W);t.apply(I,arguments)},{})},Z5=function(I){I=g.Vz(I);
delete WM[I];g.tD(WM)&&ET&&ET.stop()},uew=function(){ET||(ET=new g.bP(function(){$8Y()},20));
const I=ET;I.isActive()||I.start()},$8Y=function(){var I=g.UH();
g.tW(WM,function(U){h0t(U,I)});
g.tD(WM)||uew()},HM=function(I,U,t,W){g.WK.call(this);
if(!Array.isArray(I)||!Array.isArray(U))throw Error("Start and end parameters must be arrays");if(I.length!=U.length)throw Error("Start and end points must be the same length");this.J=I;this.V=U;this.duration=t;this.T=W;this.coords=[];this.progress=this.G=0;this.A=null},h0t=function(I,U){U<I.startTime&&(I.endTime=U+I.endTime-I.startTime,I.startTime=U);
I.progress=(U-I.startTime)/(I.endTime-I.startTime);I.progress>1&&(I.progress=1);I.G=1E3/(U-I.A);I.A=U;SH8(I,I.progress);I.progress==1?(I.B=0,Z5(I),I.onFinish(),I.pS()):I.isPlaying()&&I.rr()},SH8=function(I,U){typeof I.T==="function"&&(U=I.T(U));
I.coords=Array(I.J.length);for(let t=0;t<I.J.length;t++)I.coords[t]=(I.V[t]-I.J[t])*U+I.J[t]},z08=function(I,U){g.HN.call(this,I);
this.coords=U.coords;this.x=U.coords[0];this.y=U.coords[1];this.z=U.coords[2];this.duration=U.duration;this.progress=U.progress;this.fps=U.G;this.state=U.B},wz=function(I,U,t,W,E){HM.call(this,U,t,W,E);
this.element=I},lf=function(I,U,t,W,E){if(U.length!=2||t.length!=2)throw Error("Start and end points must be 2D");
wz.call(this,I,U,t,W,E)},Lwt=function(I){return Math.pow(I,3)},ptf=function(I){return 3*I*I-2*I*I*I},dz=function(I){return I.baseUrl||null},K9=function(I,U){return g.h$(g.Sk(I,U),t=>!!t)},m8Q=function(I,U,t){function W(pm){var rA=pm.hovercardButton;
if(!rA)return null;rA=rA.subscribeButtonRenderer;if(!rA)return null;const nm=Z(rA.unsubscribedButtonText),jp=Z(rA.subscribedButtonText);let Gz,ZC;rA.subscribed?(Gz=Z(rA.subscriberCountWithUnsubscribeText),ZC=Z(rA.subscriberCountText)):(Gz=Z(rA.subscriberCountText),ZC=Z(rA.subscriberCountWithSubscribeText));let Gv=null;return pm.signinEndpoint&&((Gv=t6(pm,"signinEndpoint","webNavigationEndpointData","url"))||(Gv=g.Q(rA.signInEndpoint?.commandMetadata,g.wl)?.url),!Gv)?null:nm&&(jp||Gv)?{subscribed:rA.subscribed,
subscribeText:nm,subscribeCount:Gz,unsubscribeText:jp,unsubscribeCount:ZC,enabled:rA.enabled,signinUrl:Gv,classic:pm.useClassicSubscribeButton}:null}
function E(pm){if(pm){var rA=[],nm=pm.videoId;nm&&rA.push("v="+nm);(nm=pm.playlistId)&&rA.push("list="+nm);(pm=pm.startTimeSeconds)&&rA.push("t="+pm);return"/watch?"+rA.join("&")}}
function Z(pm){if(!pm)return null;const rA=pm.simpleText;return rA?rA:pm.runs?g.Sk(pm.runs,nm=>nm.text).join(""):null}
U=U.endscreenElementRenderer;if(!U)return null;const H=U.style,w=U.endpoint||{};let l=null;var d=null,K=!1;let v=null,c=null,u=null,z=null;var y=!1;let a=null,Y=null;var N=null;let k=null,G=null,Ec=null;if(H==="VIDEO")g.Q(w,g.Nf)?l=g.Q(w,g.Nf).url:(Ec=g.Q(w,g.VJ),l=E(Ec)),d=!1,v=I,U.thumbnailOverlays?(K=U.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,c=Z(K.text),K=K.style==="LIVE"):c=Z(U.videoDuration);else if(H==="PLAYLIST")g.Q(w,g.Nf)?l=g.Q(w,g.Nf).url:(Ec=g.Q(w,g.VJ),l=E(Ec)),d=!1,v=
I,u=Z(U.playlistLength);else if(H==="CHANNEL"){if(y=t6(w,"browseEndpoint","browseId"))z=y,l=`/channel/${z}`;d=!1;v="new";(y=!!U.isSubscribe)?a=W(U):Y=Z(U.subscribersText)}else H==="WEBSITE"?((N=t6(w,"urlEndpoint","url"))&&(l=N),d=!0,v="new",N=U.icon.thumbnails[0].url):H==="CREATOR_MERCHANDISE"&&(U.productPrice&&(k=Z(U.productPrice)),U.additionalFeesText&&(G=Z(U.additionalFeesText)),(d=t6(w,"urlEndpoint","url"))&&(l=d),d=!0,v="new");I=t6(U,"title","accessibility","accessibilityData","label");const wA=
U.endpoint?U.endpoint.clickTrackingParams:null;let x5="";if(U.metadata){const pm=Z(U.metadata);pm&&(x5=pm)}return{id:`element-${t}`,type:H,title:Z(U.title),metadata:x5,callToAction:Z(U.callToAction),eG:U.image,iconUrl:N,left:Number(U.left),width:Number(U.width),top:Number(U.top),aspectRatio:Number(U.aspectRatio),startMs:Math.floor(Number(U.startMs)),endMs:Math.floor(Number(U.endMs)),videoDuration:c,PB:K,playlistLength:u,channelId:z,subscribeButton:a,subscribersText:Y,isSubscribe:y,targetUrl:l||null,
BH:d,sessionData:wA?{itct:wA}:null,s3:v,bW:I?I:null,isPlaceholder:U.isPlaceholder,impressionUrls:K9(U.impressionUrls||[],dz),U$:K9(U.hovercardShowUrls||[],dz),clickUrls:K9(w.loggingUrls||[],dz),visualElement:g.zY(U.trackingParams),productPrice:k,additionalFeesText:G,watchEndpoint:Ec||null}},vM=function(I,U){const t={startMs:Math.floor(Number(I.startMs)),
impressionUrls:K9(I.impressionUrls||[],dz),elements:K9(I.elements||[],(W,E)=>m8Q(U,W,E))};
I.trackingParams&&(t.visualElement=g.zY(I.trackingParams));return t},cM=function(I){return I.player.S().playerStyle==="creator-endscreen-editor"},gft=function(I){return I.player.getVideoData().z_?"current":I.C?"new":"current"},$B=function(I,U,t=!0){I.player.RW("creatorendscreen");
I.D&&(I.D.dispose(),I.D=null,I.T.dispose(),I.T=null);for(var W of Object.values(I.J))W.dispose();I.J={};I.G={};I.U.length>0&&(I.U.forEach(E=>{E.dispose()}),I.U.length=0);
I.B&&(g.Ih(I.B,"ytp-ce-element-show"),I.B.setAttribute("aria-hidden","true"));I.V=0;if((I.endscreen=U)&&U.elements){t&&CY$(I);t=[];W=new g.jd(U.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});t.push(W);I.player.S().J||(I.D=new g.V({X:"div",Y:"ytp-ce-shadow"}),g.zp(I.player,I.D.element,4),I.T=new g.jx(I.D,200));for(W=0;W<U.elements.length;++W){const E=U.elements[W],Z=y$L(I,E);if(!Z){g.ae(new g.Lm("buildEndscreenElement null",E));continue}I.J[E.id]=Z;I.G[E.id]=E;g.zp(I.player,
Z.element,4);const H=new g.jd(E.startMs,E.endMs,{id:"ytp-ce-element-"+E.id,namespace:"creatorendscreen"});t.push(H);Fwk(I,Z,E)}I.player.d8(t);I.dC()}},Qw8=function(I){var U=I.player.getVideoData(),t=U.videoId;
I.A&&I.A.abort();t={method:"POST",onFinish:E=>{var Z=I.A=null;E.status===200&&(E=E.responseText,E.substring(0,3)===")]}"&&(E=E.substring(3),Z=JSON.parse(E),Z=vM(Z,gft(I))));$B(I,Z)},
urlParams:{v:t},withCredentials:!0};I.C&&(t.urlParams.ptype="embedded");const W=U.No;W&&(t.postParams={ad_tracking:W});if(U=g.SZc(U))if(U=g.nt(U),U=g.Bq(U))I.A=g.x9(U,t)},CY$=function(I){const U=g.mj(),t=g.gW();
t&&U&&I.endscreen.visualElement&&g.HY(g.bh)(void 0,t,U,I.endscreen.visualElement)},y$L=function(I,U){var t=null;
switch(U.type){case "VIDEO":I={X:"div",fl:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":U.bW||"","aria-hidden":"true"},j:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-covering-image",W:uf(U)},{X:"div",Y:"ytp-ce-covering-shadow-top"},{X:"a",Y:"ytp-ce-covering-overlay",W:{href:h6(I,U.targetUrl),tabindex:"-1"},j:[{X:"div",fl:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.vK(U.title||"")},Fe:U.title},{X:"div",Y:U.PB?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Fe:U.videoDuration||void 0}]}]};t=new g.V(I);break;case "PLAYLIST":I={X:"div",fl:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":U.bW||"","aria-hidden":"true"},j:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-covering-image",W:uf(U)},{X:"div",Y:"ytp-ce-covering-shadow-top"},{X:"a",Y:"ytp-ce-covering-overlay",W:{href:h6(I,U.targetUrl),tabindex:"-1"},j:[{X:"div",fl:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.vK(U.title||"")},Fe:U.title},{X:"div",Y:"ytp-ce-playlist-count",
j:[{X:"div",Y:"ytp-ce-playlist-icon"},{X:"div",Y:"ytp-ce-playlist-count-text",Fe:U.playlistLength||void 0}]}]}]};t=new g.V(I);break;case "CHANNEL":t={X:"div",fl:["ytp-ce-element","ytp-ce-channel",U.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":U.bW||"","aria-hidden":"true"},j:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",j:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",
j:[{X:"div",Y:"ytp-ce-expanding-overlay-body",j:[{X:"div",Y:"ytp-ce-expanding-overlay-body-padding",j:[{X:"a",fl:["ytp-ce-channel-title","ytp-ce-link"],W:{href:h6(I,U.targetUrl),target:"_blank",tabindex:"-1",dir:g.vK(U.title||"")},Fe:U.title},U.subscribeButton?{X:"div",Y:"ytp-ce-subscribe-container",j:[{X:"div",Y:"ytp-ce-channel-subscribe"}]}:"",U.subscribersText?{X:"div",Y:"ytp-ce-channel-subscribers-text",Fe:U.subscribersText}:"",U.metadata?{X:"div",fl:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Fe:U.metadata}:""]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",W:uf(U)}]};t=new g.V(t);const E=g.EW(document,"div","ytp-ce-channel-subscribe",t.element)[0];if(U.subscribeButton&&U.channelId){g.MV(E,"ytp-ce-subscribe-button");let Z;if(I.player.S().J){var W=null;Z=U.sessionData.itct}else W="endscreen",Z=null;W=new g.IF(U.subscribeButton.subscribeText,U.subscribeButton.subscribeCount,U.subscribeButton.unsubscribeText,U.subscribeButton.unsubscribeCount,!!U.subscribeButton.enabled,!!U.subscribeButton.classic,
U.channelId,!!U.subscribeButton.subscribed,W,Z,I.player,!1);E.appendChild(W.element);I.U.push(W)}break;case "WEBSITE":I={X:"div",fl:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":U.bW||"","aria-hidden":"true"},j:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",j:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",j:[{X:"div",Y:"ytp-ce-expanding-overlay-body",j:[{X:"div",
Y:"ytp-ce-expanding-overlay-body-padding",j:[{X:"div",Y:"ytp-ce-website-title",W:{dir:g.vK(U.title||"")},Fe:U.title},{X:"div",Y:"ytp-ce-website-metadata",Fe:U.metadata},{X:"a",fl:["ytp-ce-website-goto","ytp-ce-link"],W:{href:h6(I,U.targetUrl),target:"_blank",tabindex:"-1"},Fe:U.callToAction}]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",W:uf(U)},{X:"div",Y:"ytp-ce-expanding-icon",W:fV0(U.iconUrl)}]};t=new g.V(I);break;case "CREATOR_MERCHANDISE":t="",U.productPrice&&(t={X:"div",Y:"ytp-ce-merchandise-price-container",
j:[{X:"div",Y:"ytp-ce-merchandise-price",Fe:U.productPrice}]},U.additionalFeesText&&t.j.push({X:"div",Y:"ytp-ce-merchandise-additional-fees",Fe:U.additionalFeesText})),I={X:"div",fl:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":U.bW||"","aria-hidden":"true"},j:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",j:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",
j:[{X:"div",Y:"ytp-ce-expanding-overlay-body",j:[{X:"div",Y:"ytp-ce-expanding-overlay-body-padding",j:[{X:"div",Y:"ytp-ce-merchandise-title",W:{dir:g.vK(U.title||"")},Fe:U.title},t,{X:"div",Y:"ytp-ce-merchandise-metadata",Fe:U.metadata},{X:"a",fl:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:h6(I,U.targetUrl),target:"_blank",tabindex:"-1"},Fe:U.callToAction}]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",W:uf(U)},{X:"div",Y:"ytp-ce-merchandise-invideo-cta-container",j:[{X:"div",Y:"ytp-ce-merchandise-invideo-cta",
Fe:U.callToAction||void 0}]}]},t=new g.V(I)}U.isPlaceholder&&g.MV(t.element,"ytp-ce-placeholder");return t},Fwk=function(I,U,t){function W(){H(1)}
function E(){H(-1)}
U.listen("mouseenter",()=>{SQ(I,U,t)});
U.listen("mouseleave",()=>{zj(I,U,t)});
I.player.S().J||U.listen("click",()=>{g.MV(U.element,"ytp-ce-element-hover")});
U.listen("click",w=>{jwL(I,t,w)});
U.listen("keypress",w=>{jwL(I,t,w)});
U.listen("focus",()=>{SQ(I,U,t)});
U.listen("blur",()=>{zj(I,U,t)});
U.listen("touchstart",()=>{SQ(I,U,t)});
var Z=g.Zu("ytp-ce-expanding-overlay-hider",U.element);Z&&U.L(Z,"touchstart",w=>{w.stopPropagation();g.Ih(U.element,"ytp-ce-element-hover");g.Ih(U.element,"ytp-ce-force-expand")});
U.listen("keydown",w=>{I.mu=w.keyCode===9&&!w.shiftKey});
const H=w=>{I.V+=w;I.V>0?(g.MV(U.element,"ytp-ce-force-expand"),L9(I,t.id,!0)):(g.Ih(U.element,"ytp-ce-force-expand"),g.Ih(U.element,"ytp-ce-element-hover"),L9(I,t.id,!1))};
Z=w=>{w&&(U.listen("blur",()=>{w.style.display!="none"&&I.mu&&w.focus()}),U.L(w,"focus",W),U.L(w,"blur",E))};
Z(g.Zu("ytp-sb-subscribe",U.element));Z(g.Zu("ytp-sb-unsubscribe",U.element));U.listen("focus",W);U.listen("blur",E)},p9=function(I,U,t){function W(){Z||(E++,E===U.length&&(H.stop(),t&&t()))}
if(!U||U.length===0||cM(I))t&&t();else{U=A$8(I,U);var E=0,Z=!1,H=new g.bP(()=>{Z=!0;t&&t()},1E3,I);
H.start();for(I=0;I<U.length;I++)g.eh(U[I],W)}},uf=function(I){let U;
I.eG&&(U=I.eG.thumbnails);return fV0(U?U[U.length-1].url:null)},h6=function(I,U){I=I.player.S();
if(U){if(U.startsWith("//"))return I.protocol+":"+U;if(U.startsWith("/"))return g.dn(I)+U}else return"";return U},fV0=function(I){return I?{style:"background-image: url("+I+")"}:{}},SQ=function(I,U,t){g.VM(U.element,"ytp-ce-element-hover")||(t.type==="VIDEO"||t.type==="PLAYLIST"?g.MV(U.element,"ytp-ce-element-hover"):I.player.S().J?(new g.bP(()=>{g.MV(U.element,"ytp-ce-element-hover")},200)).start():g.MV(U.element,"ytp-ce-element-hover"),p9(I,t.U$),L9(I,t.id,!0))},zj=function(I,U,t){g.Ih(U.element,
"ytp-ce-element-hover");
g.Ih(U.element,"ytp-ce-force-expand");L9(I,t.id,!1)},jwL=function(I,U,t){if(U.targetUrl&&(!t||t.type!=="keypress"||t.keyCode===13)){for(var W=t.target;W&&!g.VM(W,"ytp-ce-element");){g.VM(W,"subscribe-label")&&mr(I,U);
if(g.VM(W,"ytp-ce-channel-subscribe"))return;W=W.parentElement||null}if(!W||g.VM(W,"ytp-ce-element-hover")){t.preventDefault();t.stopPropagation();if(W=I.J[U.id])zj(I,W,U),W.element.blur();if(t.ctrlKey||t.metaKey||U.s3==="new")mr(I,U),I.player.sendVideoStatsEngageEvent(17,void 0),I.player.pauseVideo(),t=g.nt(h6(I,U.targetUrl)),t=g.Bq(t),g.IM(t,void 0,U.sessionData);else{const E=g.Ut(I.player.S())||I.player.getVideoData().z_,Z=()=>{var H=h6(I,U.targetUrl),w=U.sessionData,l=U.watchEndpoint;const d=
g.$9(H);E&&d&&(d.v||d.list)?I.player.fb(d.v,w,d.list,!1,void 0,l||void 0):g.Pf(H,w)};
mr(I,U,()=>{I.player.sendVideoStatsEngageEvent(17,Z)})}}}},L9=function(I,U,t){I.D&&(t?I.T.show():I.T.hide());
for(const W of Object.keys(I.J))W!==U&&g.D(I.J[W].element,"ytp-ce-element-shadow-show",t)},mr=function(I,U,t){p9(I,U.clickUrls,t);
(I=g.gW())&&U.BH&&g.t5(I,U.visualElement)},A$8=function(I,U){var t=I.player.getVideoData().clientPlaybackNonce;
I=I.player.getCurrentTime().toFixed(2);t={CPN:t,AD_CPN:t,MT:I};I=[];for(let W=0;W<U.length;W++)I.push(sw8(U[W],t));return I},sw8=function(I,U){return I.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,t=>{let W=unescape(t);
W=W.substring(1,W.length-1);return U[W]?escape(U[W]):t})},aV0=function(I){return typeof I==="string"?I:""},gz=function(I,U,t){for(const W in U)if(U[W]===I)return I;
return t},C9=function(I){if(!I)return null;
var U=g.nt(aV0(I.value));U=g.Bq(U);if(!U)return null;const t=gz(I.target,NxY,"current");if(t==null)I=null;else{var W=I.show_link_icon;I=new J$k(U,t,W==="true"||W==="false"?W==="true":!0,I.pause_on_navigation!=null?I.pause_on_navigation:!0)}return I},YH8=function(I){if(!I)return null;
const U=gz(I.type,ofw),t=gz(I.trigger,Xtk);I=I.url;I=Array.isArray(I)&&I.length?I[0]:I;I=C9(I?I:null);return U?new iQf(U,t,I):null},k6H=function(I,U){return g.CQ(I.action,U)},yu=function(I,U){I="background-image: url("+I+");";
const t=[];U&&t.push(U);return{X:"div",Y:"iv-card-image",W:{style:I},j:t}},Qu=function(I){return I.customMessage?FB("div","iv-card-message",I.customMessage):""},f9=function(I){if(!I.metaInfo||I.metaInfo.length===0)return"";
const U=[];for(const t of I.metaInfo)U.push(FB("li","",t));return{X:"ul",Y:"iv-card-meta-info",j:U}},jQ=function(I,U,t,W){if(W)for(const E of U)I.B(E,W,t.id,t.sessionData,t.m5.click,5)},FB=function(I,U,t){U?typeof U==="string"?U={"class":U}:Array.isArray(U)&&(U={"class":U.join(" ")}):U={};
U.dir=g.vK(t);return{X:I,W:U,Fe:t}},D8f=function(I){if(!I.customMessage)return"";
const U=["iv-card-action","iv-card-primary-link"],t={};I.QR&&(U.push("iv-card-action-icon"),t.style="background-image: url("+I.QR+");");t.dir=g.vK(I.customMessage);const W=[{X:"span",Fe:I.customMessage}];I.showLinkIcon&&(W.push("\u00a0"),W.push({X:"span",Y:"iv-card-link-icon"}));return{X:"div",fl:U,W:t,j:W}},x8L=function(I){var U;
(U=I)&&!(U=I.length>1?I.charAt(0)==="/"&&I.charAt(1)!=="/":I==="/")&&(U=I.replace(/^(https?:)?\/\//,"").split("/",1),U=!U||U.length<1||!U[0]?[]:U[0].toLowerCase().split(".").reverse(),U=U[0]==="com"&&U[1]==="youtube"||U[0]==="be"&&U[1]==="youtu");return U?I.indexOf("/redirect?")===-1:!1},r$Y=function(I,U){return U?U:x8L(I)?"current":"new"},A6=function(I,U,t,W,E,Z,H){I.context.B.listen(U,"click",w=>{I.qd(t,W,E,Z||[],H||0,w)});
I.context.B.listen(U,"touchstart",()=>{I.Nd=!1});
I.context.B.listen(U,"touchmove",()=>{I.Nd=!0})},G6f=function(I){if(g.Q(I,g.Nf)?.url)return g.Q(I,g.Nf).url;
if((I=g.Q(I,g.VJ))&&I.videoId){let U="/watch?v="+I.videoId;I.playlistId&&(U+="&list="+I.playlistId);I.index&&(U+="&index="+I.index);I.startTimeSeconds&&(U+="&t="+I.startTimeSeconds);return U}return null},sT=function(I,U,t){return{MU:(I.impressionLoggingUrlsV2s||[]).map(W=>W.baseUrl||""),
click:(t.loggingUrls||[]).map(W=>W.baseUrl||""),
close:(U.dismissLoggingUrlsV2s||[]).map(W=>W.baseUrl||""),
qy:(U.impressionLoggingUrlsV2s||[]).map(W=>W.baseUrl||""),
t7:(U.clickLoggingUrlsV2s||[]).map(W=>W.baseUrl||"")}},oX=function(I,U){if(U.onClickCommand&&g.Q(U.onClickCommand,g.Yjk)?.targetId==="engagement-panel-error-corrections"){I.N=U;
var t=!0}else t=!1;if(!t||qHV(I,U))if(t=e0w(I,U)){var W={TZ:U,BC:t.element,uT:!1};if(U.onClickCommand)I.Z.K("web_infocards_teaser_show_logging_fix")&&(I.wC||Bxk(I),aX(I,U.id),t=I.findLastIndex(W),g.ow(I.cards,t,0,W));else{I.isInitialized||bQ8(I);aX(I,U.id);const E=I.findLastIndex(W);g.ow(I.cards,E,0,W);t.As(I.J,E);I.Js()}U.autoOpen?I.addCueRange(U.startMs,0x8000000000000,U.id,()=>{I.D||(I.B=W,Nt(I),TxQ(I,W),J6(I,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(t=I.context.Z.getCurrentTime()*1E3,t<5E3&&t>U.startMs&&
R08(I,W),I.addCueRange(U.startMs,U.startMs+1,U.id,()=>{R08(I,W)}),Nt(I))}},XB=function(I){I.D&&(I.j6.hide(),I.Rn.J(),g.Ih(I.context.Z.getRootNode(),g.bA.IV_DRAWER_OPEN),I.D=!1,UT(I.Z),I.G&&I.G.stop(),I.G=new g.bP(()=>{I.yQ&&(I.yQ.focus(),I.yQ=null)},330),I.G.start())},OQw=function(I,U){U=U.data;
U.autoOpenMs&&I.addCueRange(U.autoOpenMs,0x8000000000000,"",()=>{J6(I,"YOUTUBE_DRAWER_AUTO_OPEN")});
U.autoCloseMs&&I.addCueRange(U.autoCloseMs,0x8000000000000,"",()=>{XB(I)});
const t=U.headerText;g.Qt(I.oF,t);I.T&&(I.Z.K("player_tooltip_data_title_killswitch")?I.T.setAttribute("title",t):I.T.setAttribute("data-tooltip-title",t));U.eventId&&(I.eventId=U.eventId);I.u0=g.zY(U.trackingParams);I.U=g.zY(U.closeTrackingParams);I.cZ=g.zY(U.iconTrackingParams)},YB=function(I,U,t){let W=-1,E=-1;
for(let Z=0;Z<I.length;Z++){if(I[Z].height===U||I[Z].width===t)return I[Z];((I[Z].height||0)<U||(I[Z].width||0)<t)&&(W<0||(I[W].height||0)<(I[Z].height||0)||(I[W].width||0)<(I[Z].width||0))?W=Z:((I[Z].height||0)>=U||(I[Z].width||0)>=t)&&(E<0||(I[E].height||0)>(I[Z].height||0)||(I[E].width||0)>(I[Z].width||0))&&(E=Z)}return I[E>=0?E:W]},kB=function(I,U,t,W){return{feature:t.feature?t.feature:"cards",
src_vid:I.context.videoData.videoId,annotation_id:U,ei:I.context.videoData.eventId||"",itct:W.trackingParams||""}},nfY=function(I,U){const t=U.cardId?U.cardId:`cr:${I.V}`;
var W=I.Z.S().experiments.Cl("enable_error_corrections_infocard_web_client");if(!U.content&&U.teaser.simpleCardTeaserRenderer&&W){W=U.teaser.simpleCardTeaserRenderer;var E=U.icon?U.icon.infoCardIconRenderer:null;if(W.channelAvatar&&W.channelAvatar.thumbnails&&W.channelAvatar.thumbnails.length>0)var Z=YB(W.channelAvatar.thumbnails,22,22).url;U={id:t,timestamp:I.V,type:"simple",teaserText:g.Kf(W.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),
autoOpen:!!U.autoOpen,sessionData:{},sponsored:!1,m5:{},UH:null,qp:W.trackingParams?g.zY(W.trackingParams):null,cZ:E&&E.trackingParams?g.zY(E.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,QR:null,title:"",customMessage:"",url:null,onClickCommand:W.onTapCommand||null,z2:Z};oX(I,U)}else if(U.content?.simpleCardContentRenderer){if(!U.cueRanges.length)return;Z=U.content?.simpleCardContentRenderer;W=U.teaser.simpleCardTeaserRenderer;E=U.icon?U.icon.infoCardIconRenderer:null;U={id:t,
timestamp:I.V,type:"simple",teaserText:g.Kf(W.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:kB(I,t,U,Z),sponsored:!1,m5:sT(Z,W,Z.command),UH:Z.trackingParams?g.zY(Z.trackingParams):null,qp:W.trackingParams?g.zY(W.trackingParams):null,cZ:E&&E.trackingParams?g.zY(E.trackingParams):null,imageUrl:YB(Z.image.thumbnails,290,290).url,displayDomain:Z.displayDomain?g.Kf(Z.displayDomain):null,showLinkIcon:!!Z.showLinkIcon,
QR:null,title:Z.title?g.Kf(Z.title):"",customMessage:Z.callToAction?g.Kf(Z.callToAction):"",url:g.Q(Z.command,g.Nf).url?C9({pause_on_navigation:!I.context.videoData.isLivePlayback,target:"new",value:g.Q(Z.command,g.Nf).url}):null,onClickCommand:null};oX(I,U)}else if(U.content?.collaboratorInfoCardContentRenderer){if(!U.cueRanges.length)return;Z=U.content?.collaboratorInfoCardContentRenderer;W=U.teaser.simpleCardTeaserRenderer;E=U.icon?U.icon.infoCardIconRenderer:null;U={id:t,timestamp:I.V,type:"collaborator",
teaserText:g.Kf(W.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:kB(I,t,U,Z),sponsored:!1,m5:sT(Z,W,Z.endpoint),UH:Z.trackingParams?g.zY(Z.trackingParams):null,qp:W.trackingParams?g.zY(W.trackingParams):null,cZ:E&&E.trackingParams?g.zY(E.trackingParams):null,channelId:g.Q(Z.endpoint,g.nd).browseId,customMessage:Z.customText?g.Kf(Z.customText):null,profileImageUrl:YB(Z.channelAvatar.thumbnails,290,
290).url,title:Z.channelName?g.Kf(Z.channelName):"",metaInfo:[Z.subscriberCountText?g.Kf(Z.subscriberCountText):""],url:C9({pause_on_navigation:!I.context.videoData.isLivePlayback,target:"new",value:g.Q(Z.endpoint,g.nd).canonicalBaseUrl?g.Q(Z.endpoint,g.nd).canonicalBaseUrl:`/channel/${g.Q(Z.endpoint,g.nd).browseId}`}),onClickCommand:null};oX(I,U)}else if(U.content?.playlistInfoCardContentRenderer){if(!U.cueRanges.length)return;Z=U.content?.playlistInfoCardContentRenderer;W=U.teaser.simpleCardTeaserRenderer;
E=U.icon?U.icon.infoCardIconRenderer:null;U={id:t,timestamp:I.V,type:"playlist",teaserText:g.Kf(W.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:kB(I,t,U,Z),sponsored:!1,m5:sT(Z,W,Z.action),UH:Z.trackingParams?g.zY(Z.trackingParams):null,qp:W.trackingParams?g.zY(W.trackingParams):null,cZ:E&&E.trackingParams?g.zY(E.trackingParams):null,BU:YB(Z.playlistThumbnail.thumbnails,258,290).url,customMessage:Z.customMessage?
g.Kf(Z.customMessage):null,playlistVideoCount:g.Kf(Z.playlistVideoCount),title:Z.playlistTitle?g.Kf(Z.playlistTitle):"",metaInfo:[Z.channelName?g.Kf(Z.channelName):"",Z.videoCountText?g.Kf(Z.videoCountText):""],url:C9({pause_on_navigation:!I.context.videoData.isLivePlayback,target:"new",value:G6f(Z.action)}),onClickCommand:null};oX(I,U)}else if(U.content?.videoInfoCardContentRenderer){if(!U.cueRanges.length)return;Z=U.content?.videoInfoCardContentRenderer;W=U.teaser.simpleCardTeaserRenderer;E=U.icon?
U.icon.infoCardIconRenderer:null;U={id:t,timestamp:I.V,type:"video",teaserText:g.Kf(W.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:kB(I,t,U,Z),sponsored:!1,m5:sT(Z,W,Z.action),UH:Z.trackingParams?g.zY(Z.trackingParams):null,qp:W.trackingParams?g.zY(W.trackingParams):null,cZ:E&&E.trackingParams?g.zY(E.trackingParams):null,BU:YB(Z.videoThumbnail.thumbnails,258,290).url,videoDuration:Z.lengthString?
g.Kf(Z.lengthString):null,customMessage:Z.customMessage?g.Kf(Z.customMessage):null,title:Z.videoTitle?g.Kf(Z.videoTitle):"",metaInfo:[Z.channelName?g.Kf(Z.channelName):"",Z.viewCountText?g.Kf(Z.viewCountText):""],isLiveNow:!!Z.badge,url:C9({pause_on_navigation:!I.context.videoData.isLivePlayback,target:"new",value:G6f(Z.action)}),onClickCommand:null};oX(I,U)}I.V++},VkH=function(I,U){return g.CQ(I.cards,t=>t.TZ.id===U)},Nt=function(I){g.D(I.Z.getRootNode(),"ytp-cards-shopping-active",Mk0(I))},aX=function(I,
U){if(U=VkH(I,U))U===I.B&&(I.B=null),I.Z.removeCueRange(U.TZ.id),g.C1(U.BC),g.jk(I.cards,U),I.Js(),Nt(I)},J6=function(I,U,t){if(!I.D){I.j6.show();
I.hs=new g.bP(()=>{g.MV(I.context.Z.getRootNode(),g.bA.IV_DRAWER_OPEN)},0);
I.hs.start();I.Rn.L(I.J,"mousewheel",E=>{I.l0.start();E.preventDefault();E=E||window.event;let Z=0;E.type=="MozMousePixelScroll"?Z=0==(E.axis==E.HORIZONTAL_AXIS)?E.detail:0:window.opera?Z=E.detail:Z=E.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?E.wheelDeltaY/-30:E.wheelDeltaY/-1.2:E.wheelDelta/-1.6:E.wheelDeltaY/-3;if(E=Z)I.J.scrollTop+=E});
I.D=!0;var W=g.gW();W&&I.u0&&I.U&&g.IL(W,[I.u0,I.U]);U={TRIGGER_TYPE:U};for(const E of I.cards)E.uT||(E.uT=!0,PYk(I.context.logger,E.TZ.m5.MU,U)),W&&g.IL(W,[E.TZ.UH]);UT(I.Z);t&&(I.G=new g.bP(()=>{I.yQ=I.T;I.dk.focus()},330),I.G.start())}},bQ8=function(I){g.PD(I.fu(),[g.bA.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.zp(I.Z,I.A,5);I.Y5();I.T=g.Zu("ytp-cards-button",I.Z.getRootNode());I.dk=g.Zu("iv-drawer-close-button",I.A);I.isInitialized=!0},Bxk=function(I){I.mu.push(g.Es("iv-teaser-shown",I.RF,I));
I.mu.push(g.Es("iv-teaser-hidden",I.lK,I));I.mu.push(g.Es("iv-teaser-clicked",I.k$,I));I.wC=!0},qHV=function(I,U){I.N=U;
var t=I.Z.getVideoData();if(!t)return!1;t=g.oP(t);if(t?.markersMap)for(let E=0;t?.markersMap.length>E;E++){var W=t?.markersMap[E];if(W.key==="ERROR_CORRECTION_MARKERS"&&(W=W.value?.markers)&&W.length>0)return U.startMs=g.Q(W[0],g.chW)?.timeRangeStartMillis||0,I.N=null,!0}return!1},e0w=function(I,U){switch(U.type){case "simple":I=I.wk;
var t=U.displayDomain?{X:"div",Y:"iv-card-image-text",Fe:U.displayDomain}:void 0;var W=D8f(U);t={X:"div",fl:["iv-card"],j:[{X:"a",Y:"iv-click-target",W:{href:U.url?U.url.B()||"":""},j:[yu(U.imageUrl,t),{X:"div",Y:"iv-card-content",j:[FB("h2",void 0,U.title),W]}]}]};t=new g.V(t);jQ(I,g.W9("iv-click-target",t.element),U,U.url);U=t;break;case "collaborator":I=I.wk;t={X:"div",fl:["iv-card","iv-card-channel"],j:[{X:"a",fl:["iv-click-target"],W:{href:U.url.B()||"","data-ytid":U.channelId},j:[yu(U.profileImageUrl),
{X:"div",Y:"iv-card-content",j:[Qu(U),{X:"h2",Y:"iv-card-primary-link",Fe:U.title},f9(U)]}]}]};t=new g.V(t);jQ(I,g.W9("iv-click-target",t.element),U,U.url);U=t;break;case "playlist":I=I.wk;t={X:"div",fl:["iv-card","iv-card-playlist"],j:[{X:"a",Y:"iv-click-target",W:{href:U.url.B()||""},j:[yu(U.BU,{X:"div",Y:"iv-card-image-overlay",j:[{X:"span",Y:"iv-card-playlist-video-count",Fe:U.playlistVideoCount}]}),{X:"div",Y:"iv-card-content",j:[Qu(U),FB("h2","iv-card-primary-link",U.title),f9(U)]}]}]};t=new g.V(t);
jQ(I,g.W9("iv-click-target",t.element),U,U.url);U=t;break;case "productListing":I=I.wk;var E=U.offers.length!=0;t=["iv-card"];W="";var Z=D8f(U);E&&(t.push("iv-card-product-listing"),W="iv-card-primary-link",Z=U.offers[0],E=[],Z.price&&E.push({X:"div",Y:"iv-card-offer-price",Fe:Z.price}),Z.merchant&&E.push({X:"div",Y:"iv-card-offer-merchant",Fe:Z.merchant}),Z={X:"div",j:E});E=U.url?U.url.B()||"":"";t={X:"div",fl:t,W:{tabindex:"0"},j:[{X:"a",fl:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
U.imageUrl+");",href:E,"aria-hidden":"true",tabindex:"-1"}},{X:"div",Y:"iv-card-content",j:[U.sponsored?{X:"div",Y:"iv-card-sponsored",j:["Sponsored",{X:"div",Y:"iv-ad-info-container",j:[{X:"div",Y:"iv-ad-info",Fe:"{{adInfo}}"},{X:"div",Y:"iv-ad-info-icon-container",j:[{X:"div",Y:"iv-ad-info-icon"},{X:"div",Y:"iv-ad-info-callout"}]}]}]}:"",{X:"a",Y:"iv-click-target",W:{href:E},j:[FB("h2",W,U.title),Z]}]}]};t=new g.V(t);W=g.Sy("span");g.Qt(W,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
t.setContent(W,"adInfo");jQ(I,g.W9("iv-click-target",t.element),U,U.url);U=t;break;case "video":I=I.wk;t=U.isLiveNow?{X:"span",fl:["yt-badge","yt-badge-live"],Fe:"LIVE NOW"}:null;t={X:"div",fl:["iv-card","iv-card-video"],j:[{X:"a",Y:"iv-click-target",W:{href:U.url?.B()||""},j:[yu(U.BU,U.videoDuration?{X:"span",Y:"iv-card-video-duration",Fe:U.videoDuration}:void 0),{X:"div",Y:"iv-card-content",j:[Qu(U),FB("h2","iv-card-primary-link",U.title),f9(U),t]}]}]};t=new g.V(t);jQ(I,g.W9("iv-click-target",t.element),
U,U.url);U=t;break;default:return null}return U},R08=function(I,U){if(!g.VM(I.Z.getRootNode(),"ytp-cards-teaser-shown")){if(I.B!==U){var t=g.gW(),W=I.B?I.B.TZ.cZ:I.cZ;
t&&W&&g.UI(t,[W]);I.B=U;Nt(I)}(t=I.isInitialized&&I.fu().style.display=="none")||(t=I.context.Z.getPlayerState(),W=t===0&&I.context.Z.getCurrentTime()===0,t=!(t===1||t===3||W));t||U.TZ.teaserDurationMs&&I.Z.OM(!0,{teaserText:U.TZ.teaserText,durationMs:U.TZ.teaserDurationMs,onClickCommand:U.TZ.onClickCommand,z2:U.TZ.z2??null});I.PK.isActive()||((!I.D||!I.l0.isActive()&&I.QQ)&&TxQ(I,U),I.PK.start(910+U.TZ.teaserDurationMs))}},Mk0=function(I){return I.B?I.B.TZ.type==="productListing":I.Z.K("enable_wn_infocards")?
!!I.cards?.length&&g.mw(I.cards,U=>U.TZ.type==="productListing"):g.mw(I.cards,U=>U.TZ.type==="productListing")},TxQ=function(I,U){I.C.lU?(U=new HM([0,
I.J.scrollTop],[0,U.BC.offsetTop],600,ptf),I.context.D.listen(U,"animate",t=>{I.J.scrollTop=t.y}),I.context.D.listen(U,"finish",t=>{I.J.scrollTop=t.y}),U.play()):(I.C.gC(!0),I.J.scrollTop=U.BC.offsetTop,I.C.gC(!1))},D5=function(I){return I.B&&I.B.TZ?I.B.TZ:I.cards[0]&&I.cards[0].TZ?I.cards[0].TZ:null},I2t=function(I){const U=I.annotation.data;
"start_ms"in U&&"end_ms"in U&&I.addCueRange(Number(U.start_ms),Number(U.end_ms),I.annotation.id,()=>{I.show()},()=>{I.hide()})},U28=function(I,U){var t=vfQ(U).width;
g.P9(U,t);t=new lf(U,[t,U.offsetTop],[t-t,U.offsetTop],200,Lwt);g.J(I,t);I.context.D.listen(t,"begin",()=>{g.dj(U,!0)});
t.play()},xB=function(I,U,t){t.stopPropagation();
tp6(I);WnH(I,U);I.B.focus()},Eit=function(I){const U=I.annotation.data;
if(I.annotation.style==="cta")var t=6;else if(I.annotation.style==="video"||I.annotation.style==="playlist")t=7;I.G=U.collapsedelay_ms||I.G;const W=["iv-promo","iv-promo-inactive"];I.fu().setAttribute("aria-hidden","true");I.fu().setAttribute("aria-label","Promotion");I.fu().tabIndex=0;const E=I.annotation.cQ();let Z;var H=U.image_url;H&&(Z=I.createElement({X:"div",fl:["iv-promo-img","iv-click-target"]}),H=I.createElement({X:"img",W:{src:H,"aria-hidden":"true"}}),Z.appendChild(H),U.video_duration&&
!U.is_live?(H=I.createElement({X:"span",Y:"iv-promo-video-duration",Fe:U.video_duration}),Z.appendChild(H)):U.playlist_length&&(H=I.createElement({X:"span",Y:"iv-promo-playlist-length",Fe:U.playlist_length.toString()}),Z.appendChild(H)),E&&A6(I,Z,E,I.annotation.id,U.session_data,void 0,t));E?(H=I.createElement({X:"a",Y:"iv-promo-txt"}),g.Pq(H,E.B()),I.B=H):I.B=I.createElement({X:"div",Y:"iv-promo-txt"});let w,l,d,K;switch(I.annotation.style){case "cta":case "website":w=I.createElement({X:"p",j:[{X:"strong",
Fe:U.text_line_1}]});l=I.createElement({X:"p",j:[{X:"span",Y:"iv-promo-link",Fe:U.text_line_2}]});if(H=U.text_line_3)W.push("iv-promo-website-card-cta-redesign"),d=I.createElement({X:"button",fl:["iv-promo-round-expand-icon","ytp-button"]}),H=I.createElement({X:"button",fl:["iv-button","iv-promo-button"],j:[{X:"span",Y:"iv-button-content",Fe:H}]}),K=I.createElement({X:"div",Y:"iv-promo-button-container"}),K.appendChild(H),E&&A6(I,I.fu(),E,I.annotation.id,U.session_data,void 0,t);g.MV(I.B,"iv-click-target");
E&&A6(I,I.B,E,I.annotation.id,U.session_data,void 0,t);break;case "playlist":case "video":w=I.createElement({X:"p",j:[{X:"span",Fe:U.text_line_1}]}),l=I.createElement({X:"p",j:[{X:"strong",Fe:U.text_line_2}]}),U.is_live&&(w=l,l=I.createElement({X:"span",fl:["yt-badge","iv-promo-badge-live"],Fe:"LIVE NOW"})),g.MV(I.B,"iv-click-target"),E&&A6(I,I.B,E,I.annotation.id,U.session_data,void 0,t),W.push("iv-promo-video")}w&&I.B.appendChild(w);l&&I.B.appendChild(l);I.V.appendChild(I.B);K&&I.V.appendChild(K);
t=I.createElement({X:"div",Y:"iv-promo-actions"});I.J=I.createElement({X:"button",fl:["iv-promo-expand","ytp-button"]});I.J.title="Expand";I.context.B.listen(I.J,"click",v=>{xB(I,5E3,v)});
t.appendChild(I.J);g.dj(I.J,!1);I.context.B.listen(I.fu(),"mouseover",I.l0,I);I.context.B.listen(I.fu(),"mouseout",I.wk,I);I.context.B.listen(I.fu(),"touchend",v=>{xB(I,5E3,v)});
I.D=I.createElement({X:"button",fl:["iv-promo-close","ytp-button"]});I.D.title="Close";I.context.B.listen(I.D,"click",I.annotation.style==="cta"&&U.text_line_3?I.N:I.mu,I);t.appendChild(I.D);g.PD(I.fu(),W);Z&&(g.L1(I.fu(),Z),d&&Z.appendChild(d));g.L1(I.fu(),I.V);g.L1(I.fu(),t)},rz=function(I){I.A&&(g.k5.clearTimeout(I.A),I.A=null)},tp6=function(I){I.T.stop();
I.isCollapsed&&(g.Ub(I.fu(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),I.isCollapsed=!1,I.B&&I.B.removeAttribute("aria-hidden"),g.dj(I.J,!1),g.dj(I.D,!0))},WnH=function(I,U){I.A||(I.A=g.WR(function(){rz(this);
Ztt(this)},U,I))},Ztt=function(I){I.isCollapsed||I.U||I.A||(g.MV(I.fu(),"iv-promo-collapsed"),I.isCollapsed=!0,I.T.start())},PYk=function(I,U,t){U&&(t?Gj(I,U.map(W=>g.QM(W,t))):Gj(I,U))},Gj=function(I,U,t,W){let E=1,Z=void 0,H=-1;
if(t){let w=!1;Z=()=>{E--;E||w||(clearTimeout(H),w=!0,t())};
H=setTimeout(()=>{w=!0;t()},1E3)}for(const w of U||[])E++,g.eh(w,Z);
W&&(E++,W!==0&&I.Z.sendVideoStatsEngageEvent(W,Z))},Htk=function(I){return I==="annotation-editor"||I==="live-dashboard"},wqY=function(I){I.A&&(I.player.removeEventListener("videodatachange",I.A),I.A=null)},l2L=function(I){I=I.createElement({X:"div",
fl:["annotation","annotation-type-custom"]});g.dj(I,!1);return I},eQ=function(I,U){var t=!1,W=U.getElementsByTagName("annotations");
if(W&&!(W.length<1)&&(W=W[0].getAttribute("itct"))){var E=g.gW();if(E){var Z=g.mj();Z&&g.HY(g.ei)(void 0,E,Z,[g.zY(W)])}}U=U.getElementsByTagName("annotation");for(W=0;W<U.length;W++){var H=d2e(I,U[W]);E=null;try{a:{if(!H){E=null;break a}var w=H.id;Z=/.+/;const u=typeof w==="string"&&Z!=null&&w!=null&&w.match(Z)?w:"",z=gz(H.type,KnQ),y=gz(H.style,vix),a=aV0(H.data),Y=a.length!==0?JSON.parse(a):{};b:{var l=H.action;Z=YH8;if(l==null){var d=null;break b}if(g.Bk(l)){H=[];for(const k of l){const G=Z(k);
G&&H.push(G)}d=H;break b}const N=Z(l);d=N?[N]:[]}Z=d;E=u&&z?new cDH(u,z,y,Z,Y):null}}catch(u){}if(E)if(E.type==="branding"||E.type==="promotion"){Z=I;H=E;var K=l2L(Z),v=null;switch(H.type){case "branding":if(Z.player.S().iU)break;Z.player.K("web_player_overlay_positioned_layout")?(K.setAttribute("data-overlay-order","11"),Z.player.rJ(K,4,!0)):Z.J.element.appendChild(K);v=new $2$(K,qt(Z),H);break;case "promotion":g.zp(Z.player,K,4),v=new uke(K,qt(Z),H)}v&&v.on();if(Z=v)g.J(I,Z),I.G[E.id]=Z}else if(E.type===
"card"||E.type==="drawer"){I.B||(I.B=hh6(I),g.J(I,I.B));if(E.type==="card"){K=I.B;var c=(t=E)&&t.data&&t.data.card_type;E=t.data;if(c)switch(Z=E.tracking||{},Z={MU:Z.impression,click:Z.click,close:Z.close,qy:Z.teaser_impression,t7:Z.teaser_click},H=E.tracking_params||{},v=null,c){case "collaborator":t={id:t.id,timestamp:E.timestamp||0,type:E.card_type,teaserText:E.teaser_text,teaserDurationMs:E.teaser_duration_ms,startMs:E.start_ms,autoOpen:E.auto_open||!1,sessionData:E.session_data||{},sponsored:E.sponsored||
!1,m5:Z,UH:H.card?g.zY(H.card):null,qp:H.teaser?g.zY(H.teaser):null,cZ:H.icon?g.zY(H.icon):null,channelId:E.channel_id,customMessage:E.custom_message?E.custom_message:null,profileImageUrl:E.image_url,title:E.title,metaInfo:E.meta_info,url:C9({pause_on_navigation:E.pause_on_navigation,target:E.target||"new",value:E.url}),onClickCommand:null};oX(K,t);break;case "playlist":t={id:t.id,timestamp:E.timestamp||0,type:E.card_type,teaserText:E.teaser_text,teaserDurationMs:E.teaser_duration_ms,startMs:E.start_ms,
autoOpen:E.auto_open||!1,sessionData:E.session_data||{},sponsored:E.sponsored||!1,m5:Z,UH:H.card?g.zY(H.card):null,qp:H.teaser?g.zY(H.teaser):null,cZ:H.icon?g.zY(H.icon):null,BU:E.image_url,playlistVideoCount:E.playlist_video_count,customMessage:E.custom_message?E.custom_message:null,title:E.title,metaInfo:E.meta_info,url:C9({pause_on_navigation:E.pause_on_navigation,target:E.target||"new",value:E.url}),onClickCommand:null};oX(K,t);break;case "productListing":E.signin_url&&(v=C9({target:"current",
value:E.signin_url}));c=[];const u=E.offers||[];for(let z=0;z<u.length;z++)c.push(new SNY(g.g9(u[z].merchant),g.g9(u[z].price)));t={id:t.id,timestamp:E.timestamp||0,type:E.card_type,teaserText:E.teaser_text,teaserDurationMs:E.teaser_duration_ms,startMs:E.start_ms,autoOpen:E.auto_open||!1,sessionData:E.session_data||{},sponsored:E.sponsored||!1,m5:Z,UH:H.card?g.zY(H.card):null,qp:H.teaser?g.zY(H.teaser):null,cZ:H.icon?g.zY(H.icon):null,imageUrl:E.image_url,displayDomain:E.display_domain?E.display_domain:
null,showLinkIcon:!!E.show_link_icon,QR:E.button_icon_url?E.button_icon_url:null,title:E.title,customMessage:E.custom_message?E.custom_message:null,url:C9({pause_on_navigation:E.pause_on_navigation,target:E.target||"new",value:E.url}),bXl:v,FG0:E.signin_title?E.signin_title:void 0,wkl:E.signin_message?E.signin_message:void 0,offers:c,onClickCommand:null};oX(K,t);break;case "simple":t={id:t.id,timestamp:E.timestamp||0,type:E.card_type,teaserText:E.teaser_text,teaserDurationMs:E.teaser_duration_ms,
startMs:E.start_ms,autoOpen:E.auto_open||!1,sessionData:E.session_data||{},sponsored:E.sponsored||!1,m5:Z,UH:H.card?g.zY(H.card):null,qp:H.teaser?g.zY(H.teaser):null,cZ:H.icon?g.zY(H.icon):null,imageUrl:E.image_url,displayDomain:E.display_domain?E.display_domain:null,showLinkIcon:!!E.show_link_icon,QR:E.button_icon_url?E.button_icon_url:null,title:E.title,customMessage:E.custom_message?E.custom_message:null,url:C9({pause_on_navigation:E.pause_on_navigation,target:E.target||"new",value:E.url}),onClickCommand:null};
oX(K,t);break;case "video":t={id:t.id,timestamp:E.timestamp||0,type:E.card_type,teaserText:E.teaser_text,teaserDurationMs:E.teaser_duration_ms,startMs:E.start_ms,autoOpen:E.auto_open||!1,sessionData:E.session_data||{},sponsored:E.sponsored||!1,m5:Z,UH:H.card?g.zY(H.card):null,qp:H.teaser?g.zY(H.teaser):null,cZ:H.icon?g.zY(H.icon):null,BU:E.image_url,videoDuration:E.video_duration||null,customMessage:E.custom_message?E.custom_message:null,title:E.title,metaInfo:E.meta_info,isLiveNow:!!E.is_live_now,
url:C9({pause_on_navigation:E.pause_on_navigation,target:E.target||"new",value:E.url}),onClickCommand:null},oX(K,t)}}else OQw(I.B,E);t=!0}}t&&(UT(I.player),I.C())},zh$=function(I){const U=I.player.S();
I=I.player.getVideoData();return(U.annotationsLoadPolicy||I.annotationsLoadPolicy)===1&&!I.sK||U.u0.get(I.videoId)||I.dA()||g.YU(I)?!0:!1},Ln8=function(I,U){U=!U.isCued()&&!U.B(1024);
I.J.gC(U);I.D.gC(U)},Cak=function(I,U){const t=U.videoId;
var W=Z=>{var H=I.loadNumber;I.V=null;I.loaded&&I.loadNumber===H&&I.player.getVideoData().videoId===t&&(Z=g.jM(Z)&&Z.responseXML?Z.responseXML:null)&&(eQ(I,Z),g.MV(I.player.getRootNode(),"iv-module-loaded"))};
g.gN()&&(W=pqQ(I,W));const E={format:"XML",onFinish:W,onError:()=>{I.V=null},
urlParams:{}};U.isPharma&&(E.urlParams.pharma="1");E.method="POST";E.withCredentials=!0;(W=I.player.S().u0.get(t))&&m28(E,W);W=W&&W.jM;if(!U.Ze||W)I.A=()=>{if(!I.N)I.onVideoDataChange(E);const Z=I.player.getVideoData();Z?.xk()&&!I.mu&&giQ(I,Z)},I.player.addEventListener("videodatachange",I.A)},bf=function(I,U){var t=!1;
I.B||(I.B=hh6(I),g.J(I,I.B));for(var W of U.cards||[])W.cardRenderer&&(nfY(I.B,W.cardRenderer),t=!0);t&&(I.player.getVideoData()?.xk()||(t=I.B,W=U.headerText?g.Kf(U.headerText):"",g.Qt(t.oF,W),t.T&&(t.Z.K("player_tooltip_data_title_killswitch")?t.T.setAttribute("title",W):t.T.setAttribute("data-tooltip-title",W)),t.context.videoData.eventId&&(t.eventId=t.context.videoData.eventId),t.u0=U.trackingParams?g.zY(U.trackingParams):null,t.U=U.closeButton.infoCardIconRenderer.trackingParams?g.zY(U.closeButton.infoCardIconRenderer.trackingParams):
null,t.cZ=U.icon.infoCardIconRenderer.trackingParams?g.zY(U.icon.infoCardIconRenderer.trackingParams):null,I.C()),UT(I.player))},giQ=function(I,U){if(U=U.getWatchNextResponse()?.cards?.cardCollectionRenderer)I.mu=!0,bf(I,U),U.headerText&&I.tD&&(U=g.Kf(U.headerText),I.player.K("player_tooltip_data_title_killswitch")?I.tD.setAttribute("title",U):I.tD.setAttribute("data-tooltip-title",U))},pqQ=function(I,U){return(...t)=>{I.Xe()||I.on.push(g.Xt.xI(()=>{U(...t)}))}},m28=function(I,U){I.method="POST";
I.postParams=I.postParams||{};U.jM&&(I.postParams.ic_coll=U.jM);U.Ij&&(I.postParams.ic_track=U.Ij)},d2e=function(I,U){const t={};
for(var W of U.attributes)t[W.name]=W.nodeValue;for(W=0;W<U.childNodes.length;W++){var E=U.childNodes[W];if(g.R3(E)&&E.nodeType==1){var Z=void 0;if(t[E.tagName])Z=t[E.tagName];else if(E.tagName==="data"){E.childNodes.length>0&&(Z=E.childNodes[0].nodeValue,t[E.tagName]=typeof Z==="string"?Z.trim():Z);continue}else Z=[],t[E.tagName]=Z;E&&E.tagName==="TEXT"?E.childNodes.length===1&&E.childNodes[0].nodeType===3?Z.push(E.childNodes[0].nodeValue):Z.push(""):E&&Z.push(d2e(I,E))}}return t},qt=function(I){if(!I.U){const U=
new yDQ(I);
g.J(I,U);const t=new g.Zk(I);g.J(I,t);I.U=new Fnt(U,t,I.player.S(),I.player.getVideoData(),I.logger,I.player,I.KL)}return I.U},Q_V=function(I){const U=I.player.getVideoData();
if(U.Uw){var t=I.player.S().u0.get(U.videoId);if(t){var W={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(E,Z,H)=>{E=I.loadNumber;Z=U.videoId;I.loaded&&I.loadNumber===E&&I.player.getVideoData().videoId===Z&&(H=g.jM(H)&&H.responseXML?H.responseXML:null)&&eQ(I,H)}};
g.gN()&&(W.onFinish=pqQ(I,W.onFinish));W.postParams={ic_only:"1"};m28(W,t);I.N=!0;g.x9(U.Uw,W)}}},hh6=function(I){const U=new g.V({X:"div"});
g.dj(U.element,!1);const t=new f2L(I.player,U.element,qt(I));g.J(t,U);U.As(I.J.element);t.on();return t},j_k=function(I,U,t,W,E){if(!I.player.S().iU){var Z=[];
U.navigationEndpoint&&g.Q(U.navigationEndpoint,g.nd)&&g.Q(U.navigationEndpoint,g.nd).browseId&&Z.push(new iQf("openUrl","click",new J$k(`/channel/${g.Q(U.navigationEndpoint,g.nd).browseId}`,"new",!0,!0)));var H=U.watermark.thumbnails[0];W={channel_name:U.channelName,end_ms:U.endTimeMs,image_height:H.height,image_type:1,image_url:H.url,image_width:H.width,is_mobile:!1,session_data:{annotation_id:t,ei:E,feature:"iv",itct:U.trackingParams,src_vid:W},start_ms:U.startTimeMs};if(U.subscribeButton&&g.Q(U.subscribeButton,
g.ln)){W.channel_id=g.Q(U.subscribeButton,g.ln).channelId;U=g.Q(U.subscribeButton,g.ln);H=E=null;U.subscribed?(U.subscriberCountWithUnsubscribeText&&(E=g.Kf(U.subscriberCountWithUnsubscribeText)),U.subscriberCountText&&(H=g.Kf(U.subscriberCountText))):(U.subscriberCountText&&(E=g.Kf(U.subscriberCountText)),U.subscriberCountWithSubscribeText&&(H=g.Kf(U.subscriberCountWithSubscribeText)));const w=g.Q(U.signInEndpoint?.commandMetadata,g.wl)?.url||"";U={subscribeText:g.Kf(U.unsubscribedButtonText),subscribeCount:E||
"",unsubscribeText:g.Kf(U.subscribedButtonText),unsubscribeCount:H||"",enabled:U.enabled||!1,classic:!1,subscribed:U.subscribed||!1,feature:"iv",signInUrl:w};W.standalone_subscribe_button_data=U}Z=new cDH(t,"branding","branding",Z,W);W=l2L(I);I.player.K("web_player_overlay_positioned_layout")?(W.setAttribute("data-overlay-order","11"),I.player.rJ(W,4,!0)):I.J.element.appendChild(W);Z=new $2$(W,qt(I),Z);Z.on();g.J(Z,Z);I.G[t]=Z}};
g.nX.prototype.OM=g.jA(36,function(I,U){const t=g.j2(this.Dw());t&&t.OM(I,U)});
var WM={},ET=null;g.Ht(HM,g.WK);g.F=HM.prototype;g.F.getDuration=function(){return this.duration};
g.F.play=function(I){if(I||this.B==0)this.progress=0,this.coords=this.J;else if(this.isPlaying())return!1;Z5(this);this.startTime=I=g.UH();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.nE();this.Mk("play");this.isPaused()&&this.Mk("resume");this.B=1;const U=g.Vz(this);U in WM||(WM[U]=this);uew();h0t(this,I);return!0};
g.F.stop=function(I){Z5(this);this.B=0;I&&(this.progress=1);SH8(this,this.progress);this.onStop();this.pS()};
g.F.pause=function(){this.isPlaying()&&(Z5(this),this.B=-1,this.Mk("pause"))};
g.F.b0=function(){this.B==0||this.stop(!1);this.Mk("destroy");HM.Sz.b0.call(this)};
g.F.destroy=function(){this.dispose()};
g.F.rr=function(){this.Mk("animate")};
g.F.Mk=function(I){this.dispatchEvent(new z08(I,this))};
g.Ht(z08,g.HN);g.Ht(wz,HM);wz.prototype.D=function(){};
wz.prototype.rr=function(){this.D();wz.Sz.rr.call(this)};
wz.prototype.pS=function(){this.D();wz.Sz.pS.call(this)};
wz.prototype.nE=function(){this.D();wz.Sz.nE.call(this)};
g.Ht(lf,wz);lf.prototype.D=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var yDQ=class extends g.ZW{constructor(I){super();this.J=I||window;this.B=[]}listen(I,U,t,W){t=(0,g.Ml)(t,W||this.J);I=g.nC(I,U,t);this.B.push(I);return I}bR(I,U,t,W){t=(0,g.Ml)(t,W||this.J);I=c$Q(I,U,t);this.B.push(I);return I}Z5(I){g.VR(I);g.jk(this.B,I)}removeAll(){g.VR(this.B);this.B.length=0}b0(){this.removeAll();super.b0()}};var JDk=class extends g.p0{constructor(I){super(I);this.A=this.endscreen=null;this.J={};this.G={};this.T=this.D=null;this.U=[];this.B=null;this.mu=!0;this.V=0;I=I.S();this.C=g.Dp(I)||g.qy(I);this.events=new g.E9(this);g.J(this,this.events);this.events.L(this.player,g.EZ("creatorendscreen"),this.onCueRangeEnter);this.events.L(this.player,g.Zl("creatorendscreen"),this.onCueRangeExit);this.events.L(this.player,"resize",this.dC);this.events.L(window,"focus",this.N);this.load();const U=g.Sy("STYLE");(g.t1("HEAD")[0]||
document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.C1(U)});
U.sheet&&(U.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),U.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!cM(this)){var I=g.zlA(this.player.getVideoData());I?(I=vM(I,gft(this)),$B(this,I,!1)):Qw8(this)}}unload(){$B(this,null);this.A&&(this.A.abort(),this.A=null);super.unload()}LX(I,U){return cM(this)?I==="loadCustomEndscreenRenderer"?(I=vM(U,"new"),$B(this,I),!0):null:null}getOptions(){return cM(this)?["loadCustomEndscreenRenderer"]:[]}dC(){if(this.endscreen&&this.endscreen.elements){var I=this.player.getVideoContentRect();if(I&&I.width!==0&&I.height!==0){var U=this.player.getPlayerSize();
if(U&&U.width!==0&&U.height!==0){var t=I.width/I.height;var W=0;var E=-1;for(var Z=0;Z<ADw.length;Z++){var H=Math.abs(U.width-ADw[Z]);if(E===-1||W>=H)E=Z,W=H}W=s_f[E];this.D&&g.B9(this.D.element,"outline-width",Math.max(U.width,U.height)+"px");for(U=0;U<this.endscreen.elements.length;++U){Z=this.endscreen.elements[U].id;E=this.J[Z];H=this.G[Z];if(!E||!H)continue;const l=H.width*t/H.aspectRatio;var w=Math.round(H.width*I.width);Z=Math.round(l*I.height);const d=I.left+Math.round(H.left*I.width),K=I.top+
Math.round(H.top*I.height);g.wj(E.element,w,Z);g.P9(E.element,d,K);g.Ub(E.element,a2f);w>256||Z>256?g.MV(E.element,"ytp-ce-large-round"):w>96||Z>96?g.MV(E.element,"ytp-ce-medium-round"):g.MV(E.element,"ytp-ce-small-round");g.Ub(E.element,N5w);w=H.left+H.width/2;H=H.top+l/2;g.MV(E.element,w<=.5&&H<=.5?"ytp-ce-top-left-quad":w>.5&&H<=.5?"ytp-ce-top-right-quad":w<=.5&&H>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ub(E.element,s_f);g.MV(E.element,W);(E=g.EW(document,"div","ytp-ce-expanding-overlay-body",
E.element)[0])&&g.B9(E,"height",`${Z}px`)}}}}}onCueRangeEnter(I){if(this.endscreen)if(I.getId()==="ytp-ce-in-endscreen")p9(this,this.endscreen.impressionUrls),(I=g.gW())&&this.endscreen.visualElement&&g.P8(I,this.endscreen.visualElement),this.B&&(g.MV(this.B,"ytp-ce-element-show"),this.B.removeAttribute("aria-hidden"),this.player.i5()?g.MV(this.B,"ytp-ce-hide-button-lower"):g.Ih(this.B,"ytp-ce-hide-button-lower"));else{I=I.getId().substring(15);var U=this.J[I],t=this.G[I];g.MV(U.element,"ytp-ce-element-show");
U.element.removeAttribute("aria-hidden");U=this.player.getRootNode();g.MV(U,"ytp-ce-shown");p9(this,t.impressionUrls);(U=g.gW())&&g.P8(U,t.visualElement);this.player.S().U&&g.Of(this.player,"endscreenelementshown",I)}}onCueRangeExit(I){if(I.getId()==="ytp-ce-in-endscreen")this.B&&(g.Ih(this.B,"ytp-ce-element-show"),this.B.setAttribute("aria-hidden","true"));else{I=I.getId().substring(15);var U=this.J[I];g.Ih(U.element,"ytp-ce-element-show");U.element.setAttribute("aria-hidden","true");U=this.player.getRootNode();
g.Ih(U,"ytp-ce-shown");this.player.S().U&&g.Of(this.player,"endscreenelementhidden",I)}}N(I){I.target===window&&(new g.bP(()=>{for(const U of Object.values(this.J))g.Ub(U.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}gC(I){for(const U of Object.values(this.J))I?U.element.setAttribute("hidden",""):U.element.removeAttribute("hidden")}HT(I){this.B&&this.player.getRootNode().removeChild(this.B);
I&&(g.MV(I,"ytp-ce-hide-button-container"),this.B=I,g.zp(this.player,this.B,4))}},ADw=[346,426,470,506,570,640,853,1280,1920],s_f="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),N5w=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],a2f=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var J$k=class{constructor(I,U,t,W){this.value=I;this.target=U;this.showLinkIcon=t;this.J=W}B(){return this.value?this.value:null}},NxY={LA:"current",mD:"new"};var iQf=class{constructor(I,U,t){this.type=I;this.trigger=U;this.url=t}},ofw={CLOSE:"close",rP:"openUrl",SUBSCRIBE:"subscribe"},Xtk={Ak:"click",CLOSE:"close",e5:"hidden",XKA:"rollOut",t6n:"rollOver",csk:"shown"};var cDH=class{constructor(I,U,t,W,E){this.id=I;this.type=U;this.style=t;this.data=E;this.action=W||[]}cQ(){const I=k6H(this,U=>U.type==="openUrl"&&U.url!=null);
return I?I.url:null}},vix={ye:"anchored",CO:"branding",CHANNEL:"channel",Uh:"cta",J5:"highlightText",kV:"label",PLAYLIST:"playlist",POPUP:"popup",C00:"speech",SUBSCRIBE:"subscribe",wok:"title",VIDEO:"video",pod:"website"},KnQ={CO:"branding",Eh:"card",Oh:"drawer",k_:"highlight",K2:"marker",cf:"promotion",TEXT:"text",Qvs:"widget"};var oiY=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
Xqf=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var itY=class{constructor(I,U){this.context=I;this.B=U}};var SNY=class{constructor(I,U){this.merchant=I;this.price=U}};var YNt=class extends g.ZW{constructor(I,U){super();this.element=I;this.context=U;this.Nd=!1;this.Md=new Map;this.UJ=new Map;this.context.Z.addEventListener(g.EZ("annotations_module"),t=>{(t=this.Md.get(t))&&t.apply(this)});
this.context.Z.addEventListener(g.Zl("annotations_module"),t=>{(t=this.UJ.get(t))&&t.apply(this)})}addCueRange(I,U,t,W,E){I=new g.jd(I,U,{id:t,
namespace:"annotations_module"});W&&this.Md.set(I,W);E&&this.UJ.set(I,E);this.context.Z.d8([I],1)}on(){this.context.J.subscribe("resize",this.Js,this)}fu(){return this.element}qd(I,U,t,W,E,Z){if(this.Nd)return!1;Z&&(Z.stopPropagation(),Z.preventDefault());this.navigate(I,t,W,E);return!1}show(){}hide(){}destroy(){g.C1(this.fu())}Js(){}navigate(I,U,t,W){const E=I.B();if(E){var Z=r$Y(E,I.target),H=()=>{I.J&&this.context.Z.pauseVideo();const w=this.context.videoData.z_||!1,l=g.$9(E||"");w&&l&&(l.v||l.list)?
this.context.Z.fb(l.v,U,l.list,!1):g.IM(E||"",Z==="current"?"_top":void 0,U)};
Z==="new"&&(H(),H=null);Gj(this.context.logger,t,H,W);x8L(E)||(t=g.gW(),W=U.itct,t&&W&&g.t5(t,g.zY(W)))}}b0(){this.Md.clear();this.UJ.clear();super.b0()}createElement(I){I=new g.V(I);g.J(this,I);return I.element}};var f2L=class extends YNt{constructor(I,U,t){super(U,t);this.Z=I;this.eventId=null;this.wC=this.QQ=this.Gk=this.D=this.isInitialized=!1;this.cards=[];this.dk=this.T=this.yQ=this.G=this.hs=this.B=null;this.mu=[];this.N=this.U=this.cZ=this.u0=null;this.V=0;this.l0=new g.bP(()=>{},t.O.H5?4E3:3E3);
g.J(this,this.l0);this.PK=new g.bP(()=>{});
g.J(this,this.PK);this.wk=new itY(t,(W,E,Z,H,w,l)=>{A6(this,W,E,Z,H,w,l)});
this.C=new g.V({X:"div",Y:"iv-drawer",W:{id:"iv-drawer"},j:[{X:"div",Y:"iv-drawer-header",W:{"aria-role":"heading"},j:[{X:"span",Y:"iv-drawer-header-text"},{X:"button",fl:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{X:"div",Y:"iv-drawer-content"}]});g.J(this,this.C);this.A=this.C.element;this.j6=new g.jx(this.C,330);g.J(this,this.j6);this.oF=g.Zu("iv-drawer-header-text",this.A);this.J=g.Zu("iv-drawer-content",this.A);this.addCueRange(0,t.videoData.lengthSeconds*
1E3,"",()=>{this.Gk&&J6(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.Gk=this.D)&&XB(this)});
this.Rn=new g.E9(this);g.J(this,this.Rn);this.Z.addEventListener("videodatachange",this.O4.bind(this))}O4(){this.N&&oX(this,this.N)}isAvailable(){var I;if(I=!!this.cards.length)(I=this.Z.getRootNode())?(I=g.lO(I),I=173<I.width&&173<I.height):I=!1;return I}Js(){const I=this.isAvailable();g.dj(this.fu(),I);g.D(this.context.Z.getRootNode(),g.bA.IV_DRAWER_ENABLED,I);UT(this.Z)}destroy(){this.Z.OM(!1);try{this.Z.getRootNode().removeChild(this.A)}catch(I){}g.ZE(this.mu);this.Rn.J();this.hs&&this.hs.dispose();
this.G&&this.G.dispose();super.destroy()}Y5(){this.context.B.listen(g.Zu("iv-drawer-close-button",this.A),"click",this.SN,this);this.context.B.listen(this.J,"touchend",()=>{this.l0.start()});
this.context.B.listen(this.J,"scroll",this.Y$,this);this.context.J.subscribe("onHideControls",()=>{this.QQ=!0});
this.context.J.subscribe("onShowControls",()=>{this.QQ=!1});
this.context.J.subscribe("onVideoAreaChange",()=>{this.QQ=g.VM(this.Z.getRootNode(),"ytp-autohide")});
this.mu.push(g.Es("iv-button-shown",this.Po,this));this.mu.push(g.Es("iv-button-hidden",this.iU,this));Bxk(this)}findLastIndex(I){if(this.cards.length===0)return 0;const U=g.yL(this.cards,t=>I.TZ.startMs>t.TZ.startMs||I.TZ.startMs===t.TZ.startMs&&I.TZ.timestamp>=t.TZ.timestamp?!0:!1);
return U===-1?0:U+1}SN(){if(this.D){Gj(this.context.logger,D5(this).m5.close);var I=g.gW();I&&this.U&&g.t5(I,this.U);XB(this)}}Y$(){g.D(this.A,"iv-drawer-scrolled",this.J.scrollTop>0)}Po(){const I=g.gW();var U=D5(this);U=U?U.cZ:this.cZ;I&&U&&g.IL(I,[U])}iU(){const I=g.gW();var U=D5(this);U=U?U.cZ:this.cZ;I&&U&&g.UI(I,[U])}RF(){const I=D5(this);Gj(this.context.logger,I.m5.qy);const U=g.gW();if(U&&I)if(this.Z.K("web_infocards_teaser_show_logging_fix")){const t=[];I.qp&&t.push(I.qp);I.cZ&&t.push(I.cZ);
t.length>0&&g.IL(U,t)}else g.IL(U,[I.qp,I.cZ])}lK(){const I=g.gW(),U=D5(this);I&&U&&g.UI(I,[U.qp])}k$(I){const U=D5(this),t=g.gW();this.B?I?(I=this.context.logger,Gj(I,U.m5.t7),I.Z.sendVideoStatsEngageEvent(4,void 0),t&&U.qp&&g.t5(t,U.qp)):(I=this.context.logger,Gj(I,U.m5.t7),I.Z.sendVideoStatsEngageEvent(4,void 0),t&&U.cZ&&g.t5(t,U.cZ)):(I=this.context.logger,Gj(I,U.m5.t7),I.Z.sendVideoStatsEngageEvent(4,void 0),t&&this.cZ&&g.t5(t,this.cZ))}};var kJ8=class extends YNt{constructor(I,U,t){super(I,U);this.annotation=t;this.isActive=!1}on(){super.on();I2t(this)}show(){super.show();const I=g.gW();var U=this.annotation.data;I&&U&&(U=U.session_data)&&g.IL(I,[g.zY(U.itct)])}hide(){super.hide();const I=g.gW();var U=this.annotation.data;I&&U&&(U=U.session_data)&&g.UI(I,[g.zY(U.itct)])}};var $2$=class extends kJ8{constructor(I,U,t){super(I,U,t);this.B=null;this.D=!1;this.J=null}show(){if(!this.isActive){super.show();if(!this.D){g.MV(this.fu(),"iv-branding");const I=this.annotation.data;this.B=this.createElement({X:"img",fl:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:I.image_url,width:I.image_width,height:I.image_height}});g.dj(this.B,!1);const U=this.createElement({X:"button",fl:["branding-img-container","ytp-button"]});U.appendChild(this.B);this.fu().appendChild(U);
const t=this.annotation.cQ();t&&A6(this,U,t,this.annotation.id,I.session_data);this.D=!0}g.dj(this.fu(),!0);this.isActive=!0;if(this.B){try{U28(this,this.B)}catch{}g.MV(this.context.Z.getRootNode(),"ytp-branding-shown");this.context.Z.getRootNode().style.setProperty("--branding-image-width",`${this.B.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.dj(this.fu(),!1),this.isActive=!1,g.Ih(this.context.Z.getRootNode(),"ytp-branding-shown"))}destroy(){this.J&&(this.J.dispose(),this.J=
null);g.Ih(this.context.Z.getRootNode(),"ytp-branding-shown");super.destroy()}};var Fnt=class{constructor(I,U,t,W,E,Z,H){this.B=I;this.D=U;this.O=t;this.videoData=W;this.logger=E;this.Z=Z;this.J=H}};var uke=class extends kJ8{constructor(I,U,t){super(I,U,t);this.U=this.isCollapsed=this.C=!1;this.G=5E3;this.J=this.D=this.B=this.A=null;this.V=this.createElement({X:"div",fl:["iv-promo-contents"]});this.T=new g.bP(()=>{this.B.setAttribute("aria-hidden","true");g.dj(this.D,!1);g.dj(this.J,!0)},700,this);
g.J(this,this.T)}show(){this.isActive||(super.show(),this.C||(Eit(this),this.C=!0),g.dj(this.fu(),!0),g.WR(function(){g.Ih(this.fu(),"iv-promo-inactive")},100,this),this.fu().removeAttribute("aria-hidden"),this.isActive=!0,rz(this),tp6(this),WnH(this,this.G))}hide(){this.isActive&&(g.MV(this.fu(),"iv-promo-inactive"),this.isActive=!1,this.fu().setAttribute("aria-hidden","true"))}qd(I,U,t,W,E,Z){return this.isCollapsed?!1:super.qd(I,U,t,W,E,Z)}l0(I){this.U=!0;
xB(this,500,I)}wk(){this.U=!1;Ztt(this)}mu(I){I.stopPropagation();this.hide()}N(I){I.stopPropagation();rz(this);this.isCollapsed=!0;g.MV(this.fu(),"iv-promo-collapsed-no-delay");this.T.start()}destroy(){this.T.dispose();super.destroy()}};var D2t=class{constructor(I){this.Z=I}};g.g7("annotations_module",class extends g.p0{constructor(I){super(I);this.mu=this.N=!1;this.loadNumber=0;this.G={};this.logger=new D2t(this.player);this.T=new g.E9(this);this.V=this.A=null;this.events=new g.E9(this);this.tD=this.U=this.B=null;this.on=[];g.J(this,this.T);this.T.L(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.T.L(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.T.L(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.T.L(this.player,"resize",t=>{this.publish("resize",t)});
this.T.L(this.player,"presentingplayerstatechange",t=>{this.publish("presentingplayerstatechange",t)});
this.subscribe("presentingplayerstatechange",this.l0,this);this.subscribe("resize",this.C,this);this.player.S().u0.subscribe("vast_info_card_add",this.wk,this);g.J(this,this.events);this.Js=this.createElement({X:"div",Y:"video-custom-annotations"});this.J=new g.V({X:"div",fl:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.J);g.zp(this.player,this.J.element,4);this.J.hide();this.D=new g.V({X:"div",fl:["ytp-iv-video-content"]});g.J(this,this.D);I=this.createElement({X:"div",Y:"video-annotations"});
I.appendChild(this.Js);this.D.element.appendChild(I);this.tN()?this.load():this.player.K("web_fix_annotations")&&(this.A=()=>{this.loaded||this.Xe()||!this.tN()||(wqY(this),this.load())},this.player.addEventListener("videodatachange",this.A));
const U=this.createElement({X:"style"});(g.t1("HEAD")[0]||document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.C1(U)});
if(I=U.sheet){for(const t of oiY)I.insertRule(t,0);for(const t of Xqf)I.insertRule(t,0)}}LX(I,U){if(!Htk(this.player.S().playerStyle))return null;switch(I){case "loadCustomAnnotationsXml":return(I=g.EY(U))&&eQ(this,I),!0;case "removeCustomAnnotationById":return U&&this.B&&(aX(this.B,U),UT(this.player)),!0}return null}getOptions(){return Htk(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}tN(){const I=this.player.getVideoData(),U=I.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return I.z_||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.K("web_fix_annotations")?zh$(this)?U?.isWatermarkEnforced===!0?!0:U?.isAnnotationsEnabled??!1:!1:zh$(this)}C(){if(this.D){var I=this.player.sJ().getVideoContentRect(!0);g.wj(this.D.element,I.width,I.height);g.P9(this.D.element,I.left,I.top)}if(this.B){var U=this.player.zL();I=this.B;U=U.width;g.D(I.A,"iv-drawer-small",U<=426);g.D(I.A,"iv-drawer-big",U>=1280)}}l0(I){Ln8(this,I.state);I.state.B(2)&&(this.i5()&&this.cE()&&this.player.getPresentingPlayerType()!==
2&&this.Br(!1),this.OM(!1))}load(){super.load();Ln8(this,this.player.getPlayerStateObject());this.loadNumber++;const I=this.player.getVideoData();Cak(this,I);g.zp(this.player,this.D.element,4);this.C();var U=g.YU(I);const t=I.dA();if(this.player.K("web_fix_annotations")){if(U&&(U.featuredChannel&&j_k(this,U.featuredChannel,U.annotationId||"branding",I.videoId||null,I.eventId||null),U=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,U?.isWatermarkEnforced&&!U?.isAnnotationsEnabled))return;
t&&bf(this,t)}else t&&bf(this,t),U&&U.featuredChannel&&j_k(this,U.featuredChannel,U.annotationId||"branding",I.videoId||null,I.eventId||null);this.tD=g.Zu("ytp-cards-button",this.player.getRootNode());I.xk()&&giQ(this,I)}onVideoDataChange(){}unload(){this.player.RW("annotations_module");for(const I of Object.keys(this.G))this.G[I].destroy();this.U=null;this.B&&(this.B.destroy(),this.B=null,UT(this.player));this.N=!1;this.V&&(this.V.abort(),this.V=null);this.mu=!1;this.G={};this.J.hide();super.unload();
this.D.detach();wqY(this)}wk(I){I===this.player.getVideoData().videoId&&(this.loaded?Q_V(this):this.load())}i5(){return this.B?.isAvailable()||this.mu}cE(){return!!this.B&&this.B.D}Br(I,U=!1,t){this.i5();this.B&&(I?t?J6(this.B,t,U):J6(this.B,"YOUTUBE_DRAWER_AUTO_OPEN",U):XB(this.B))}OM(I,U){this.player.publish(I?"cardsteasershow":"cardsteaserhide",U)}b0(){this.player.S().u0.unsubscribe("vast_info_card_add",this.wk,this);g.Ih(this.player.getRootNode(),g.bA.IV_DRAWER_OPEN);var I=this.on,U=g.Xt;for(let t=
0,W=I.length;t<W;t++)U.Cp(I[t]);this.on.length=0;super.b0()}createElement(I){I=new g.V(I);g.J(this,I);return I.element}});g.g7("creatorendscreen",JDk);})(_yt_player);
