(function(g){var window=this;'use strict';var rDt=async function(I,U,t){I.J=g.x9(U,t)},BM=function(I){I.isActive()||I.start()},Tj=function(I,U){return U?I.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},GJ8=function(I){return g.Ut(I)||I.K("web_enable_caption_language_preference_stickiness")},qNt=function(I,U){const t=new g.Ff;
t.languageCode=I.languageCode;t.languageName=I.languageName;t.name=I.name;t.displayName=I.displayName;t.kind=I.kind;t.isDefault=!1;t.B=I.B;t.isTranslateable=I.isTranslateable;t.vssId=I.vssId;t.url=I.url;t.translationLanguage=U;I.xtags&&(t.xtags=I.xtags);I.captionId&&(t.captionId=I.captionId);return t},eh8=async function(I,U){I=I+"|"+U;
U=await g.dD();if(!U)throw g.Ds("gct");return(await g.DR(U)).get("captions",I)},btw=function(I,U,t){eh8(I,U).then(W=>{W&&t(W.trackData,new g.Ff(W.metadata))})},RX=function(I){if(!B5w.test(I))throw Error("'"+I+"' is not a valid hex color");
I.length==4&&(I=I.replace(T5L,"#$1$1$2$2$3$3"));I=I.toLowerCase();I=parseInt(I.slice(1),16);return[I>>16,I>>8&255,I&255]},Rh0=function(){var I={};
let U="suggest_correction"in g.$A?g.$A.suggest_correction:"Edit caption";U=U||"";for(let t in I){const W=()=>String(I[t]);
U=U.replace(new RegExp("\\$\\{"+t+"\\}","gi"),W);U=U.replace(new RegExp("\\$"+t,"gi"),W)}return U},OT=function(){return g.Ey("yt-player-caption-display-settings")},Ot8=function(I,U){let t=g.kf(I.segments,U);
t>=0||t<0&&(-t-1)%2===1||(t=-t-1,t>0&&U-I.segments[t-1]===1&&t<I.segments.length&&I.segments[t]-U===1?(g.fQ(I.segments,t),g.fQ(I.segments,t-1)):t>0&&U-I.segments[t-1]===1?I.segments[t-1]=U:t<I.segments.length&&I.segments[t]-U===1?I.segments[t]=U:(g.ow(I.segments,t,0,U),g.ow(I.segments,t+1,0,U)))},niQ=function(I){return I.B&&I.B.T?I.B.T+I.player.jN()<I.player.getCurrentTime():!1},Vpw=function(I,U){if(I.policy.dg&&I.player.Wy()){var t=g.$3(U,I.policy,{});
t.set("pot",I.player.Wy());t=t.cQ()}else t=g.$3(U,I.policy,{}).cQ();const W={format:"RAW",withCredentials:!0};if(I.policy.yQ){W.method="POST";const H=U.A;H&&Object.keys(H).length>0?W.postBody=g.rV(H,g.EE):W.postBody=(0,g.Vl)([120,0])}I.T&&(W.responseType="arraybuffer");let E=++I.on;const Z=(0,g.q)();I.J=g.Rb(t,W,3,100,-1,H=>{H.errorCode==="net.timeout"&&I.player.EJ("capnt",{rn:E++})}).then(H=>{if(I.policy.yP&&E%100===1){var w=(0,g.q)();
I.player.EJ("caprsp",{rn:E,ms:w-Z,kb:(H.xhr.responseText.length/1024).toFixed()})}a:{H=H.xhr;I.Xe();if(I.D){var l=!(I.T?H.response:H.responseText)||H.status>=400;if(w=g.KVz(H)){H=g.$3(I.D,I.policy,{});I.D.NE(H,w);Vpw(I,I.D);break a}l?I.player.EJ("capfail",{status:H.status}):(g.t8("fcb_r",(0,g.q)(),I.player.getVideoData()?.N||""),w=I.D.zg[0],l=w.ZK,I.U!=null&&I.G!==l&&(I.T?I.U(H.response,(w.startTime+I.player.jN())*1E3):I.U(H.responseText,(w.startTime+I.player.jN())*1E3),I.G=l))}I.D=null;I.J=null}}).V3(H=>
{I.D=null;
I.J=null;I.player.EJ("capfail",{rn:E,status:H.xhr?.status})});
I.D=U;Ot8(I.A,I.D.zg[0].ZK)},Mpw=function(I,U){return U!=null&&U in I.J.B?I.J.B[U]:null},PaY=function(I,U,t){const W=[];
for(const E in I.J.B){if(!I.J.B.hasOwnProperty(E))continue;const Z=I.J.B[E];if(g.Fl(Z,t||null)){const H=Z.info.captionTrack;H&&H.languageCode===U&&W.push(Z)}}return W.length?W[0]:null},UFe=function(I,U){const t=[];
for(const E in I.J.B)if(I.J.B.hasOwnProperty(E)){var W=I.J.B[E];if(g.Fl(W,U||null)){let Z=W.info.id,H=Z,w=`.${Z}`,l="",d="";if(W=W.info.captionTrack)Z=W.languageCode,H=W.displayName,w=W.vssId,l=W.kind,d=W.id;else{{W=Z;let K=g.orA.get(W);K==null&&(K=ICe[W]||ICe[W.replace(/-/g,"_")],g.orA.set(W,K));W=K}H=W||H}t.push(new g.Ff({id:E,languageCode:Z,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:l,captionId:d}))}}return t},tet=function(I,U,t,W){let E=U/360*16;
U>=I&&(I=640,W>t*1.3&&(I=480),E=t/I*16);return E},WHw=function(I){let U=1+.25*(I.fontSizeIncrement||0);
if(I.offset===0||I.offset===2)U*=.8;return U},EEt=function(I,U){let t="vertical-rl";
I.B.OL===1&&(t="vertical-lr");g.lo&&(t=t==="vertical-lr"?"tb-lr":"tb-rl");g.B9(U,"-o-writing-mode",t);g.B9(U,"-webkit-writing-mode",t);g.B9(U,"writing-mode",t);g.B9(U,"text-orientation","upright");g.MV(U,"ytp-vertical-caption");I.J.params.ZP===3&&(g.B9(U,"text-orientation",""),g.B9(U,"transform","rotate(180deg)"))},ZWw=function(I,U){const t={};
var W=U.background?U.background:I.B.Oo.background;if(U.backgroundOpacity!=null||U.background){var E=U.backgroundOpacity!=null?U.backgroundOpacity:I.B.Oo.backgroundOpacity;W=RX(W);t.background="rgba("+W[0]+","+W[1]+","+W[2]+","+E+")";I.Y$&&(t["box-decoration-break"]="clone",t["border-radius"]=`${I.Md/8}px`)}if(U.fontSizeIncrement!=null||U.offset!=null)t["font-size"]=`${I.hs*WHw(U)}px`;W=1;E=U.color||I.B.Oo.color;if(U.color||U.textOpacity!=null)E=RX(E),W=U.textOpacity==null?I.B.Oo.textOpacity:U.textOpacity,
E="rgba("+E[0]+","+E[1]+","+E[2]+","+W+")",t.color=E,t.fill=E;var Z=U.charEdgeStyle;Z===0&&(Z=void 0);if(Z){E=`rgba(34, 34, 34, ${W})`;let l=`rgba(204, 204, 204, ${W})`;U.oQ&&(l=E=U.oQ);const d=I.hs/16/2,K=Math.max(d,1);var H=Math.max(2*d,1),w=Math.max(3*d,1);const v=Math.max(5*d,1);W=[];switch(Z){case 4:for(;w<=v;w+=d)W.push(`${H}px ${H}px ${w}px ${E}`);break;case 1:H=window.devicePixelRatio>=2?.5:1;for(Z=K;Z<=w;Z+=H)W.push(`${Z}px ${Z}px ${E}`);break;case 2:W.push(`${K}px ${K}px ${l}`);W.push(`-${K}px -${K}px ${E}`);
break;case 3:for(w=0;w<5;w++)W.push(`0 0 ${H}px ${E}`)}t["text-shadow"]=W.join(", ")}E="";switch(U.fontFamily){case 1:E='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:E='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:E='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:E='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:E='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:E=g.cF()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:E='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}E&&(t["font-family"]=E);E=U.offset;E==null&&(E=I.B.Oo.offset);switch(E){case 0:t["vertical-align"]="sub";break;case 2:t["vertical-align"]="super"}U.fontFamily===7&&(t["font-variant"]="small-caps");U.bold&&(t["font-weight"]="bold");U.italic&&(t["font-style"]="italic");U.underline&&
(t["text-decoration"]="underline");U.cj&&(t.visibility="hidden");U.G8===1&&I.D&&(t["text-combine-upright"]="all",t["text-orientation"]="mixed",E=g.HI||g.ir,I.J.params.ZP===3?t.transform=E?"rotate(90deg)":"rotate(180deg)":E&&(t.transform="rotate(-90deg)"));if(U.textEmphasis===1||U.textEmphasis===2||U.textEmphasis===3||U.textEmphasis===4||U.textEmphasis===5)if(g.HI)t["font-weight"]="bold";else switch(t["text-emphasis-style"]="filled circle",t["text-emphasis-color"]="currentcolor",t["webkit-text-emphasis"]=
"filled circle",U.textEmphasis){case 4:case 3:t["text-emphasis-position"]="under left";t["webkit-text-emphasis-position"]="under left";break;case 5:case 2:t["text-emphasis-position"]="over right",t["webkit-text-emphasis-position"]="over right"}return t},n9=function(I){I=I.split("px");
return I.length>0?(I=Number(I[0]))?I:0:0},lCk=function(I,U,t){I.Js=I.Js||!!t;
const W={};Object.assign(W,I.B.Oo);Object.assign(W,t||U.B);Object.assign(W,I.lK.Oo);(t=!I.V)&&HWQ(I);let E=I.u0&&I.yQ&&g.Z2(W,I.yQ)?I.u0:wTY(I,W);const Z=typeof U.text==="string",H=Z?U.text.split("\n"):[U.text];for(let l=0;l<H.length;l++){var w=l>0||!U.append;const d=H[l];w&&!t?(HWQ(I),E=wTY(I,W)):w&&t&&(t=!1);d&&(E.appendChild(Z?g.zA(d):d),Z||d.tagName!=="RUBY"||d.childElementCount!==4||g.HI||!g.OW(d.children[2],"text-emphasis")||(w=I.D?"padding-right":"padding-top",g.OW(d.children[2],"text-emphasis-position")&&
(w=I.D?"padding-left":"padding-bottom"),g.v9?g.B9(E,w,"1em"):g.B9(E,w,"0.5em")))}I.yQ=W;I.u0=E;I.G.push(U)},HWQ=function(I){I.V=g.Sy("SPAN");
g.B9(I.V,{display:"block"});g.MV(I.V,"caption-visual-line");I.A.appendChild(I.V)},wTY=function(I,U){const t=g.Sy("SPAN");
g.B9(t,{display:"inline-block","white-space":"pre-wrap"});g.B9(t,ZWw(I,U));t.classList.add("ytp-caption-segment");I.V.appendChild(t);t.previousElementSibling&&(g.B9(t.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.B9(t,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return t},KHw=function(I,U,t){if(I===255&&U===255||!I&&!U)return{E6:I,
Sa:U,result:0};I=dFL[I];U=dFL[U];if(I&128){var W;if(W=!(U&128))W=U,W=t.Gc()&&t.Sa===W;if(W)return{E6:I,Sa:U,result:1}}else if(U&128&&1<=I&&I<=31)return{E6:I,Sa:U,result:2};return{E6:I,Sa:U,result:3}},cpQ=function(I,U,t,W){U===255&&t===255||!U&&!t?(++I.D===45&&I.reset(),I.A.J.clear(),I.T.J.clear()):(I.D=0,vEe(I.A,U,t,W))},$Ff=function(I,U){I.B.sort((t,W)=>{const E=t.time-W.time;
return E===0?t.order-W.order:E});
for(const t of I.B)I.time=t.time,t.type===0?cpQ(I,t.L1,t.SU,U):t.type===1&&I.J&496&&vEe(I.T,t.L1,t.SU,U);I.B.length=0},LHx=function(I,U){switch(I){case 0:return uOf[(U&127)-32];
case 1:return hy$[U&15];case 2:return Sm0[U&31];case 3:return zyV[U&31]}return 0},Vu=function(I,U){if(I.style.type===3){var t=0,W=0,E=I.T.time+0,Z="",H="",w=E;
for(var l=1;l<=15;++l){var d=!1;for(var K=W?W:1;K<=32;++K){var v=I.D[l][K];if(v.B!==0){t===0&&(t=l,W=K);d=String.fromCharCode(v.B);var c=v.timestamp;c<E&&(E=c);v.timestamp=w;H&&(Z+=H,H="");Z+=d;d=!0}if((v.B===0||K===32)&&d){H="\n";break}else if(W&&!d)break}if(t&&!d)break}Z&&U.A(t,W,E,w,Z)}else for(W=t=0,Z=E=I.T.time+0,H=1;H<=15;++H)for(w="",l=1;l<=32;++l)if(K=I.D[H][l],v=K.B,v!==0&&(t===0&&(t=H,W=l),d=String.fromCharCode(v),c=K.timestamp,c<=E&&(E=c),w+=d,K.reset()),l===32||v===0)w&&U.A(t,W,E,Z,w),
E=Z,w="",W=t=0},Mt=function(I){return I.D[I.row][I.J]},PM=function(I,U,t){U>=2&&I.J>1&&(--I.J,Mt(I).B=0);
const W=Mt(I);W.timestamp=I.T.time+0;W.B=LHx(U,t);I.J<32&&I.J++},pTe=function(I,U,t,W){for(let H=0;H<W;H++)for(let w=0;w<=32;w++){var E=I.D[U+H][w],Z=I.D[t+H][w];
E.B=Z.B;E.timestamp=Z.timestamp}},IO=function(I,U,t){for(let W=0;W<t;W++)for(let E=0;E<=32;E++)I.D[U+W][E].reset()},Ug=function(I){I.row=I.B>0?I.B:1;
I.J=1;IO(I,0,15)},mFx=function(I){I.style.set(1);
I.B=I.A;I.B.B=0;I.B.style=I.style;I.D.mode=1<<I.B.A},tH=function(I,U,t){const W=I.J;
let E=!1;switch(I.style.get()){case 4:case 1:case 2:I.style.get()===4&&W.B>0||(Vu(W,t),Ug(I.J),Ug(I.A),W.row=15,W.B=U,E=!0)}I.style.set(3);I.B=W;I.B.style=I.style;I.D.mode=1<<W.A;E?W.J=1:W.B!==U&&(W.B>U?(Vu(W,t),IO(W,W.row-W.B,U)):W.row<U&&(U=W.B),W.B=U)},gEH=function(I){I.style.set(4);
I.B=I.text;I.B.style=I.style;I.D.mode=1<<I.B.A},vEe=function(I,U,t,W){I.J.update();
U=KHw(U,t,I.J);switch(U.result){case 0:return;case 1:case 2:return}var E=U.E6;U=U.Sa;if(32<=E||!E)I.B.mode&I.B.J&&(t=E,t&128&&(t=127),U&128&&(U=127),I=I.A.B,t&96&&PM(I,0,t),U&96&&PM(I,0,U),t!==0&&U!==0&&I.style.type===3&&Vu(I,W));else if(E&16)a:if(!I.J.matches(E,U)&&(t=I.J,t.E6=E,t.Sa=U,t.state=2,t=E&8?I.G:I.D,I.A=t,I.B.mode=1<<(I.T<<2)+(t.T<<1)+(t.style.type===4?1:0),(I.B.mode|1<<(I.T<<2)+(t.T<<1)+(t.style.type!==4?1:0))&I.B.J))if(U&64){W=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(E&7)<<1|U>>5&1];
I=U&16?((U&14)>>1)*4:0;U=t.B;switch(t.style.get()){case 4:W=U.row;break;case 3:if(W!==U.row){if(W<U.B&&(W=U.B,W===U.row))break;var Z=1+U.row-U.B;const H=1+W-U.B;pTe(U,H,Z,U.B);t=Z;E=U.B;H<Z?(Z=H+E-Z,Z>0&&(t+=Z,E-=Z)):(Z=Z+E-H,Z>0&&(E-=Z));IO(U,t,E)}}U.row=W;U.J=I+1}else switch(E&7){case 1:switch(U&112){case 32:PM(t.B,0,32);break a;case 48:U===57?(W=t.B,Mt(W).B=0,W.J<32&&W.J++):PM(t.B,1,U&15)}break;case 2:U&32&&PM(t.B,2,U&31);break;case 3:U&32&&PM(t.B,3,U&31);break;case 4:case 5:if(32<=U&&U<=47)switch(U){case 32:mFx(t);
break;case 33:W=t.B;W.J>1&&(--W.J,Mt(W).B=0);break;case 36:W=t.B;I=Mt(W);for(U=0;U<=15;U++)for(t=0;t<=32;t++)if(W.D[U][t]===I){for(;t<=32;t++)W.D[U][t].reset();break}break;case 37:tH(t,2,W);break;case 38:tH(t,3,W);break;case 39:tH(t,4,W);break;case 40:PM(t.B,0,32);break;case 41:W=t;W.style.set(2);W.B=W.J;W.B.B=0;W.B.style=W.style;W.D.mode=1<<W.B.A;break;case 42:W=t;I=W.text;I.B=15;I.style.set(4);Ug(I);gEH(W);break;case 43:gEH(t);break;case 44:I=t;U=I.J;switch(I.style.get()){case 1:case 2:case 3:Vu(U,
W)}IO(U,0,15);break;case 45:b:{U=t;I=U.B;switch(U.style.get()){default:case 2:case 1:break b;case 4:if(I.row<15){++I.row;I.J=1;break b}break;case 3:}I.B<2&&(I.B=2,I.row<I.B&&(I.row=I.B));U=I.row-I.B+1;Vu(I,W);pTe(I,U,U+1,I.B-1);IO(I,I.row,1)}break;case 46:IO(t.A,0,15);break;case 47:I=t,Vu(I.J,W),I.A.updateTime(I.D.time+0),W=I.A,I.A=I.J,I.J=W,mFx(I)}break;case 7:switch(U){case 33:case 34:case 35:W=t.B,(W.J+=U&3)>32&&(W.J=32)}}},yp6=function(I,U,t,W,E,Z,H){var w=Z[0];
let l=H[w.getAttribute("p")];if(l.zZ===1){var d=Z[1],K=Z[2];Z=Z[3];w.getAttribute("t");d.getAttribute("t");K.getAttribute("t");Z.getAttribute("t");w.getAttribute("p");d.getAttribute("p");Z.getAttribute("p");H=H[K.getAttribute("p")];w=ClV(w.textContent,d.textContent,K.textContent,Z.textContent,H);return new Wg(I,U,E,t,w,W,l)}switch(l.zZ){case 9:case 10:l.textEmphasis=1;break;case 11:l.textEmphasis=2;break;case 12:l.textEmphasis=3;break;case 13:l.textEmphasis=4;break;case 14:l.textEmphasis=5}return new Wg(I,
U,E,t,w.textContent||"",W,l)},ClV=function(I,U,t,W,E){var Z=g.cF();
const H=Z?g.Sy("DIV"):g.Sy("RUBY"),w=g.Sy("SPAN");w.textContent=I;H.appendChild(w);I=Z?g.Sy("DIV"):g.Sy("RP");I.textContent=U;H.appendChild(I);U=Z?g.Sy("DIV"):g.Sy("RT");U.textContent=t;H.appendChild(U);t=E.zZ;if(t===10||t===11||t===12||t===13||t===14)if(g.B9(U,"text-emphasis-style","filled circle"),g.B9(U,"text-emphasis-color","currentcolor"),g.B9(U,"webkit-text-emphasis","filled circle"),E.zZ===11||E.zZ===13)g.B9(U,"webkit-text-emphasis-position","under left"),g.B9(U,"text-emphasis-position","under left");
t=!0;if(E.zZ===4||E.zZ===7||E.zZ===12||E.zZ===14)g.B9(H,"ruby-position","over"),g.B9(H,"-webkit-ruby-position","before");else if(E.zZ===5||E.zZ===6||E.zZ===11||E.zZ===13)g.B9(H,"ruby-position","under"),g.B9(H,"-webkit-ruby-position","after"),t=!1;E=Z?g.Sy("DIV"):g.Sy("RP");E.textContent=W;H.appendChild(E);Z&&(W=t,g.B9(H,{display:"inline-block",position:"relative"}),Z=H.firstElementChild.nextElementSibling,g.B9(Z,"display","none"),Z=Z.nextElementSibling,g.B9(Z,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.B9(H.lastElementChild,"display","none"),W?(g.B9(H,"padding-top","0.6em"),g.B9(Z,"top","0")):(g.B9(H,"padding-bottom","0.6em"),g.B9(Z,"bottom","0")));return H},FHH=function(I){const U="_"+Eg++;
return new Zn(0,0x8000000000000,0,U,I)},Hg=function(I,U){I=I.getAttribute(U);
if(I!=null)return Number(I)},wI=function(I,U){I=I.getAttribute(U);
if(I!=null)return I==="1"},lJ=function(I,U){I=Hg(I,U);
return I!==void 0?I:null},Ki=function(I,U){I=I.getAttribute(U);
if(I!=null)return dI.test(I),I},Q0w=function(I,U){const t={},W=U.getAttribute("ws");
Object.assign(t,W?I.C[W]:I.A);I=lJ(U,"mh");I!=null&&(t.QC=I);I=lJ(U,"ju");I!=null&&(t.textAlign=I);I=lJ(U,"pd");I!=null&&(t.ZP=I);I=lJ(U,"sd");I!=null&&(t.OL=I);I=Ki(U,"wfc");I!=null&&(t.windowColor=I);U=Hg(U,"wfo");U!==void 0&&(t.windowOpacity=U/255);return t},fCH=function(I,U){const t={},W=U.getAttribute("wp");
W&&Object.assign(t,I.U[W]);I=lJ(U,"ap");I!=null&&(t.Us=I);I=Hg(U,"cc");I!=null&&(t.gp=I);I=Hg(U,"ah");I!=null&&(t.E4=I);I=Hg(U,"rc");I!=null&&(t.oN=I);U=Hg(U,"av");U!=null&&(t.R1=U);return t},j0Y=function(I,U,t,W){let E={};
Object.assign(E,fCH(I,U));Object.assign(E,Q0w(I,U));W?g.Z2(E,I.A)?(W=I.T,E=I.A):W="_"+Eg++:W=U.getAttribute("id")||"_"+Eg++;I=Hg(U,"t")+t;U=Hg(U,"d")||0x8000000000000;if(E.ZP===2||E.ZP===3)t=E.oN,E.oN=E.gp,E.gp=t;return new Zn(I,U,0,W,E)},vg=function(I){I=g.DC(Math.round(I),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-I.length)+I},ApL=function(I,U,t,W,E){W===0&&(W=0x8000000000000);
const Z={};U.wpWinPosId&&Object.assign(Z,I.A.get(U.wpWinPosId));U.wsWinStyleId&&Object.assign(Z,I.T.get(U.wsWinStyleId));I=U.rcRowCount;I!==void 0&&(Z.oN=I);U=U.ccColCount;U!==void 0&&(Z.gp=U);if(Z.ZP===2||Z.ZP===3)U=Z.oN,Z.oN=Z.gp,Z.gp=U;return new Zn(t,W,0,E,Z)},cg=function(I){const U=I.byteOffset;
I.byteOffset+=1;return I.B.getUint8(U)},$_=function(I){const U=I.byteOffset;
I.byteOffset+=4;return I.B.getUint32(U)},N9w=function(I){if(typeof I==="string")return!1;
I=new s0x(I,0);return aCL(I)},aCL=function(I){if(!(I.byteOffset<I.B.byteLength)||$_(I)!==1380139777)return!1;
I.version=cg(I);if(I.version>1)return!1;cg(I);cg(I);cg(I);return!0},Jpk=function(I,U){if(!U)return"";
I.D&&I.J.params.OL!==1&&(U*=-1);return`translate${I.D?"X":"Y"}(${U}px)`},oE$=function(I){I.wk=Array.from(I.element.getElementsByClassName("caption-visual-line"));
for(var U=I.J.params.oN,t=0,W=0,E=I.wk.length-1;t<U&&E>-1;){var Z=I.wk[E];W+=I.D?Z.offsetWidth:Z.offsetHeight;t++;E--}I.C=W;U=Math;t=U.max;isNaN(I.l0)&&((W=I.B.gp)?(E=g.Sy("SPAN"),g.Qt(E,"\u2013".repeat(W)),g.B9(E,ZWw(I,I.B.Oo)),I.A.appendChild(E),I.l0=E.offsetWidth,I.A.removeChild(E)):I.l0=0);W=I.A;I.N=t.call(U,I.l0,I.k$,(I.D?W.offsetHeight:W.offsetWidth)+1)},XTf=function(I,U){oE$(I);
var t=I.wk.reduce((W,E)=>(I.D?E.offsetWidth:E.offsetHeight)+W,0);
t=I.C-t;if(t!==I.QQ){const W=t>0&&I.QQ===0,E=t<I.QQ;U||isNaN(t)||W||!E||(g.MV(I.element,"ytp-rollup-mode"),I.L(I.element,"transitionend",I.qd));g.B9(I.A,"transform",Jpk(I,t));I.QQ=t}oE$(I)},Ymw=function(I,U){I.B=(t,W)=>{if(t.info.D){var E=t;
if(I.b_.length>0){for(E=I.b_.shift();I.b_.length>0;)E=E.G(I.b_.shift());E=E.G(t)}if(E){t=E;try{var Z=g.Qc(t)*1E3}catch(u){Z=t.info.startTime*1E3}try{var H=g.t4_(t)*1E3}catch(u){H=t.info.duration*1E3}if(Z<0||H<0)Z<0&&(Z=t.info.startTime*1E3),H<0&&(H=t.info.duration*1E3);t.info.startTime=Z/1E3;t.info.A=Z/1E3;t.info.duration=H/1E3;t.info.U=H/1E3;const {formatId:w,ZK:l,startTimeMs:d,durationMs:K}=I.AQ(E);Z={formatId:w,startTimeMs:d,durationMs:K,zs:l,WZ:l};H=iWw(I.J3,Z.startTimeMs);const v=(t=H>=0?I.J3[H]:
null)?t.startTimeMs+t.durationMs:0,c=Z.startTimeMs+Z.durationMs;!t||Z.startTimeMs-v>I.J?I.J3.splice(H+1,0,Z):(t.durationMs=Math.max(v,c)-t.startTimeMs,t.WZ=Math.max(t.WZ,Z.WZ));W(I.J3);Z=g.Cz(E);W=I.D;Z=Z.buffer.slice(Z.byteOffset,Z.byteLength+Z.byteOffset);E=E.info.A;W.mu?W.U==null?g.gf(W.logger,350058965,"Null loaded track meta data at captions data received"):U.Bt(Z,W.U,E*1E3):g.gf(W.logger,350058965,"Null Representation at captions data received")}else g.gf(I.logger,350058965,"Empty slice")}else I.b_.push(t)};
I.Z.addEventListener("sabrCaptionsDataLoaded",I.B)},iWw=function(I,U){I=g.kf(I,{startTimeMs:U},(t,W)=>t.startTimeMs-W.startTimeMs);
return I>=0?I:-I-2},kv0=function(I,U){if(!g.gz_(I)||I.B!=null&&g.ym(U,I.B)&&I.B.B.rawcc!=null)return!1;
U=!!I.B&&I.B.isManifestless&&Object.values(I.B.B).some(t=>g.Fl(t,"386"));
I=!!I.B&&!I.B.isManifestless&&g.A5S(I.B);return U||I},DFY=function(I,U,t){const W=[];
for(const E in I.J.B){if(!I.J.B.hasOwnProperty(E))continue;const Z=I.J.B[E];if(g.Fl(Z,t||null)){const H=Z.info.captionTrack;H&&H.languageCode===U&&W.push(Z)}}return W.length?W[0]:null},xFY=function(I,U){const t=[];
for(const E in I.J.B)if(I.J.B.hasOwnProperty(E)){var W=I.J.B[E];if(g.Fl(W,U||null)){let Z=W.info.id,H=Z,w=`.${Z}`,l="",d="";if(W=W.info.captionTrack)Z=W.languageCode,H=W.displayName,w=W.vssId,l=W.kind,d=W.id;t.push(new g.Ff({id:E,languageCode:Z,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:l,captionId:d}))}}return t},Gvk=function(I){const U=rpQ.length;
if(I.byteLength<U)return!1;I=new Uint8Array(I,0,U);for(let t=0;t<U;t++)if(rpQ[t]!==I[t])return!1;return!0},uJ=function(I){I=I.split(":");
let U=0;for(const t of I)U=U*60+Number(t);return U*1E3},qmL=function(I,U,t,W){W=Object.assign({QC:0},W);
return new Zn(I,U,t,"_"+Eg++,W)},eyL=function(I,U,t,W,E,Z,H,w,l){switch(H.tagName){case "b":w.bold=!0;
break;case "i":w.italic=!0;break;case "u":w.underline=!0}for(let K=0;K<H.childNodes.length;K++){var d=H.childNodes[K];if(d.nodeType===3)d=new Wg(U,t,W,E.id,d.nodeValue,Z||K>0,g.tD(w)?void 0:w),l.push(d),E.B.push(d);else{const v={};Object.assign(v,w);eyL(I,U,t,W,E,!0,d,v,l)}}},B96=function(I,U,t){if(typeof U==="string"||N9w(U))return[{trackData:U,
fm:t}];if(typeof U==="string"&&U.substring(0,6)==="WEBVTT"||typeof U!=="string"&&Gvk(U))return[{trackData:U,fm:t}];const W=new DataView(U);if(W.byteLength<=8||W.getUint32(4)!==1718909296)return[];var E=g.w83(W);if(I.qt&&E){var Z=g.MJl(E),H=g.PzI(E);E=E.Qf;Z&&E&&I.qt.b2(E,Z,H)}I=g.jV(W,1835295092);if(!I||!I.length||!I[0].size)return[];Z=[];for(H=0;H<I.length;H++)E=I[H],E=new Uint8Array(U,E.dataOffset,E.size-(E.dataOffset-E.offset)),E=g.ye(E),Z.push({trackData:E,fm:t+H*1E3});bWt(W,Z,t);return Z=Z.filter(w=>
!!w.trackData)},Ry$=function(I,U,t){I.B||(I.B=new T9H);
I=I.B.D(U,t);Math.random()<.01&&g.ae(Error("Deprecated subtitles format in web player: WebVTT"));return I},bWt=function(I,U,t){var W=g.yy(I,0,1836476516);
let E=9E4;W&&(E=g.Fh(W)||9E4);W=0;const Z=g.jV(I,1836019558);for(let w=0;w<Z.length;w++){var H=Z[w];w<U.length&&(H=g.yy(I,H.dataOffset,1953653094))&&(H=g.yy(I,H.dataOffset,1952867444))&&(H=g.fV(H)/E*1E3,w===0&&(W=H),U[w].fm=H-W+t||t*w*1E3)}},OWQ=function(I){const U={};
if(I=g.pd(I))U.lang=I,g.IjW.test(I)&&(U.ZP=1);return U},nEH=function(I){const U=!!I.Z.iK()?.wk();
return I.D==="HLS"&&U?!0:I.hs&&U&&I.D!=="LIVE"&&I.D!=="SABR_LIVE"},SC=function(I,U,t=!1){const W=hH.Oo;
I.T={};Object.assign(I.T,hH);I.T.Oo={};Object.assign(I.T.Oo,W);I.G={Oo:{}};var E=U.backgroundOverride?I.G:I.T,Z=U.background||W.background;dI.test(Z);E.Oo.background=Z;E=U.colorOverride?I.G:I.T;Z=U.color||W.color;dI.test(Z);E.Oo.color=Z;E=U.windowColorOverride?I.G:I.T;Z=U.windowColor||hH.windowColor;dI.test(Z);E.windowColor=Z;E=U.backgroundOpacityOverride?I.G:I.T;Z=U.backgroundOpacity;Z==null&&(Z=W.backgroundOpacity);E.Oo.backgroundOpacity=Z;E=U.fontSizeIncrementOverride?I.G:I.T;Z=U.fontSizeIncrement;
Z==null&&(Z=W.fontSizeIncrement);E.Oo.fontSizeIncrement=Z;Z=U.fontStyleOverride?I.G:I.T;E=U.fontStyle;E==null&&(E=W.bold&&W.italic?3:W.bold?1:W.italic?2:0);Z=Z.Oo;switch(E){case 1:Z.bold=!0;delete Z.italic;break;case 2:delete Z.bold;Z.italic=!0;break;case 3:Z.bold=!0;Z.italic=!0;break;default:delete Z.bold,delete Z.italic}E=U.textOpacityOverride?I.G:I.T;Z=U.textOpacity;Z==null&&(Z=W.textOpacity);E.Oo.textOpacity=Z;E=U.windowOpacityOverride?I.G:I.T;Z=U.windowOpacity;Z==null&&(Z=hH.windowOpacity);E.windowOpacity=
Z;E=U.charEdgeStyleOverride?I.G:I.T;Z=U.charEdgeStyle;Z==null&&(Z=W.charEdgeStyle);E.Oo.charEdgeStyle=Z;E=U.fontFamilyOverride?I.G:I.T;Z=U.fontFamily;Z==null&&(Z=W.fontFamily);E.Oo.fontFamily=Z;I.loaded&&I.dk();t&&g.Wi("yt-player-caption-display-settings",U,2592E3)},zR=function(I,U,t){U&&!I.mu?(U=FHH({ZP:0,
lang:"en"}),I.mu=[U,new Wg(U.start,U.end-U.start,0,U.id,t??"Captions look like this")],I.player.d8(I.mu)):!U&&I.mu&&(VeH(I,I.mu),I.mu=null)},Mek=function(I){if(!I.Z.isInline())return g.Ey("yt-player-sticky-caption")},Li=function(I){let U=void 0;
const t=g.K$().OJ(65);if(g.Ut(I.O)&&t!=null){if(Mek(I)!=null)return!1;U=!t}return U},Pl6=function(I){if(I.O.SI===1||I.videoData.Id===1||g.sf(I.videoData,"yt:cc")==="alwayson")return!0;
let U;I.videoData.captionTracks.length&&(U=I.getAudioTrack().J);if(I.O.SI===2){if(g.Ut(I.O))var t=Mek(I);else if(I.storage)try{t=I.storage.get("module-enabled")}catch(E){I.storage.remove("module-enabled")}else t=null;if(t!=null)return!!t}t=Tj(I.player.getAudioTrack(),g.Ut(I.O));const W=g.sf(I.videoData,"yt:cc");if(Li(I)===void 0){if(t==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return W?W==="on":!0;if(t==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return W==="on"}else return W==="on";return U==="ON"||
g.sf(I.videoData,"yt:cc")==="on"},pi=function(I,U=!1){if(I.B&&!U||!I.videoData.captionTracks.length)return!1;
I=I.getAudioTrack();return!!I.B||I.J==="FORCED_ON"},Iuw=function(I,U){if(I.B){var t=I.Z.iK().fu().textTracks,W=null;
I.D==="HLS"?W=I.B.getId():W=I.B.toString();for(let Z=0;Z<t.length;Z++){var E=t[Z];E.id===W&&(U?E.mode!=="showing"&&(E.mode="showing",E=I.B,I.Fw(E,!!E,mP(I)?"g":I.V?"m":"s")):E.mode==="showing"&&(E.mode="disabled"))}}},mP=function(I){const U=gI(I);
return!!U&&I.B===U},Uue=function(I,U){if(I.D==="HLS")return!1;
g.Dx(I.videoData)&&(U=!0);U||(U=I.D==="TTS"?!1:I.D==="INNERTUBE"?!1:!0);return U||I.O.K("web_deprecate_always_includes_asr_setting")&&g.Ut(I.O)?!0:!!g.K$().OJ(66)},gI=function(I){return I.C&&I.C.B},Ci=function(I,U){if(!I.J)return null;
if(I.C&&I.C.A)return I.C.A;U=Uue(I,U);U=g.U8(I.J.B,U);let t=null;if(GJ8(I.O)){var W=I.Z.isInline()?void 0:g.Ey("yt-player-caption-sticky-language");var E=[W,I.videoData.captionsLanguagePreference,I.O.captionsLanguagePreference,g.sf(I.videoData,"yt:cc_default_lang")];let w=!1;for(let l=0;l<E.length;l++){const d=E[l];if(d){w=!0;for(var Z=0;Z<U.length;Z++)if(g.pd(U[Z])===d)return U[Z];for(Z=0;Z<U.length;Z++)if(g.pd(U[Z]).split("-")[0]===d.split("-")[0])return U[Z]}}if(w&&I.J&&(E=I.J.C,E.length))for(var H of E)if(H.languageCode===
W){t=H;break}}else for(H=[I.videoData.captionsLanguagePreference,I.O.captionsLanguagePreference,g.sf(I.videoData,"yt:cc_default_lang")],W=0;W<H.length;W++)for(E=0;E<U.length;E++)if(g.pd(U[E])===H[W])return U[E];H=null;I.C&&I.C.D&&(H=I.C.D);H||(H=U.find(w=>w.isDefault)||null);
H||(H=U[0]||gI(I));H&&t&&g.pd(H).split("-")[0]!==t.languageCode.split("-")[0]&&(H=qNt(H,t));return H},fi=function(I,U,t){I.loaded&&I.unload();
t!=null&&(I.V=t,I.V&&(g.Ut(I.O)?yS(I,!!U):FH(I,!!U)));U!==null||pi(I,!0)||I.Fw(U,!!U,I.V?"m":"s");I.B=U;pi(I)&&(I.B=gI(I));QS(I,I.B??void 0);I.load()},yS=function(I,U){I.Z.isInline()||g.Wi("yt-player-sticky-caption",U,2592E3)},FH=function(I,U){if(I.storage)try{I.storage.set("module-enabled",U)}catch(t){}},QS=function(I,U){I.O.K("html5_modify_caption_vss_logging")&&(I.videoData.IN=U)},WUt=function(I,U){var t=I.on[U.id];
t&&t.J!==U&&(t.dispose(),delete I.on[U.id],t=null);t||(t=tyf(I,U))&&(I.on[U.id]=t)},EV6=function(I,U){const t=U.windowId;
I.Rn[t]||(I.Rn[t]=[]);I.Rn[t].push(U)},tyf=function(I,U){const t=Z1L(I);
if(!t)return null;var W=I.B?g.pd(I.B):null;W&&g.IjW.test(W)&&(U.params.ZP=1);var E=I.PK.getPlayerSize();W=E.height*I.N.height;E=E.width*I.N.width;I.O.playerStyle!=="google-live"||I.T.isDefault||Object.assign(U.params,I.T);switch(U.params.QC!=null?U.params.QC:U.B.length>1?1:0){case 1:return new H1w(U,I.T,I.G,t.width,t.height,E,W,I.O.experiments,I.Md.bind(I),I.Z);case 2:return new w9L(U,I.T,I.G,t.width,t.height,E,W,I.O.experiments,I.Md.bind(I),I.Z);default:return new jC(U,I.T,I.G,t.width,t.height,E,
W,I.O.experiments,I.Md.bind(I),I.Z)}},Z1L=function(I){let U=I.PK.getVideoContentRect(!0).height,t=I.PK.getVideoContentRect(!0).width;
if(!U||!t)return null;U*=I.N.height;t*=I.N.width;return{width:t,height:U}},VeH=function(I,U){I.player.xY(U);
for(const t of U)g.jk(I.Js,t);BM(I.u0)},luV=function(I,U){if(!I.J)return{};
if(U){g.tD(U)||I.GA(U.vss_id,"m");if(I.A&&I.D!=="HLS"||!g.R3(U))return;if(g.tD(U)){fi(I,null,!0);return}let W;var t=g.U8(I.J.B,!0);for(let E=0;E<t.length;E++){const Z=t[E];Z.languageCode!==U.languageCode||W&&(Z.languageName!==U.languageName||(Z.captionId||"")!==(U.captionId||"")||g.zL(Z)!==U.displayName)||(W=U.translationLanguage?qNt(Z,U.translationLanguage):Z)}I.Vy(U.position);!W||W===I.B&&I.loaded||(U=g.q4(),t=g.pd(W),U.length&&t===U[U.length-1]||(U.push(t),g.Wi("yt-player-caption-language-preferences",
U)),GJ8(I.O)&&!I.Z.isInline()&&g.Wi("yt-player-caption-sticky-language",t,2592E3),fi(I,W,!0))}else return I.loaded&&I.B&&!mP(I)?g.Ld(I.B):{};return""};
g.JX.prototype.b2=g.jA(65,function(I,U,t){this.J.set(I,{Rt:U,lW:t})});
g.o9.prototype.b2=g.jA(64,function(I,U,t){this.mu.b2(I,U,t)});
g.m5.prototype.N=g.jA(63,function(){return!1});
g.m5.prototype.A=g.jA(62,function(){});
g.gh.prototype.A=g.jA(61,function(I,U,t){this.Xe();U=this.G(I,U);const W=this.xA.S().K("html5_report_captions_ctmp_qoe"),E=(0,g.q)();this.D();rDt(this,U,{format:"RAW",onSuccess:Z=>{this.J=null;if(W){var H=(Z.responseText.length/1024).toFixed();const w=(0,g.q)();this.videoData.EJ("capresp",{ms:w-E,kb:H})}H=Z.getResponseHeader&&Z.getResponseHeader("Content-Length")?Number(Z.getResponseHeader("Content-Length")):0;t.Bt(Z.responseText,I,void 0,void 0,H)},
onError:W?Z=>{this.videoData.EJ("capfail",{status:Z?.status??0})}:void 0,
withCredentials:!0})});
g.C0.prototype.A=g.jA(60,function(I,U,t){this.Xe();U=this.G(I,U);this.D();this.J=g.x9(U,{format:"RAW",onSuccess:W=>{this.J=null;const E=W.getResponseHeader&&W.getResponseHeader("Content-Length")?Number(W.getResponseHeader("Content-Length")):0;t.Bt(W.responseText,I,void 0,void 0,E)},
withCredentials:!0})});
g.JZ.prototype.V=g.jA(59,function(){const I=g.EW(document,"track",void 0,this.B);for(let U=0;U<I.length;U++)g.C1(I[U])});
g.ic.prototype.V=g.jA(58,function(){this.mediaElement.V()});
g.JZ.prototype.l0=g.jA(57,function(){return!(!this.B.textTracks||!this.B.textTracks.addEventListener)});
g.ic.prototype.l0=g.jA(56,function(){return this.mediaElement.l0()});
g.JZ.prototype.wk=g.jA(55,function(){return!!this.B.textTracks});
g.ic.prototype.wk=g.jA(54,function(){return this.mediaElement.wk()});
g.JZ.prototype.mu=g.jA(53,function(I){for(let U=0;U<I.length;U++)this.B.appendChild(I[U])});
g.ic.prototype.mu=g.jA(52,function(I){this.mediaElement.mu(I)});
g.nX.prototype.Ev=g.jA(40,function(I){return g.oG(this.app,{playerType:void 0}).Ev(I)});
g.tC.prototype.Ev=g.jA(39,function(I){return this.BK.i$.Ev(I)});
g.vo.prototype.Ev=g.jA(38,function(I){return this.Do().some(U=>U.namespace===I)});
g.sj.prototype.Ev=g.jA(37,function(){return!1});
g.nX.prototype.GA=g.jA(35,function(I,U){this.app.S6().GA(I,U)});
g.tC.prototype.GA=g.jA(34,function(I,U){this.BK.GA(I,U)});
g.l7.prototype.GA=g.jA(33,function(I,U){I=[I,U];g.Fr(this,g.jG(this.provider),"cfi",I)});
g.K0.prototype.GA=g.jA(32,function(I,U){this.qoe&&this.qoe.GA(I,U)});
g.le.prototype.GA=g.jA(31,function(I,U){this.Lu.GA(I,U)});
g.sj.prototype.GA=g.jA(30,function(){});
g.nX.prototype.Fw=g.jA(29,function(I,U,t){this.app.S6().Fw(I,U,t)});
g.tC.prototype.Fw=g.jA(28,function(I,U,t){this.BK.Fw(I,U,t)});
g.l7.prototype.Fw=g.jA(27,function(I,U,t){if(this.u0!==I||this.oF!==U)U=U==="rawcc"?"":U,t=[I,U,this.u0,t],g.Fr(this,g.jG(this.provider),"cfs",t),this.u0=I,this.oF=U});
g.K0.prototype.Fw=g.jA(26,function(I,U,t){this.qoe&&this.qoe.Fw(I,U,t)});
g.le.prototype.Fw=g.jA(25,function(I,U,t){this.Lu.Fw(I,U,t)});
g.sj.prototype.Fw=g.jA(24,function(){});
g.kw.prototype.lz=g.jA(3,function(I){return(I=this.D(I))?I.B:0});
g.xw.prototype.lz=g.jA(2,function(){return 0});
var T5L=/#(.)(.)(.)/,B5w=/^#(?:[0-9a-f]{3}){1,2}$/i,ICe={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},duY={en:"English"},KUw=class extends g.m5{constructor(I){super(I);this.J=new Set}T(I){var U=this.xA.iK();if(U&&U.fu()){U=U.fu().textTracks;for(const t of U)t.kind==="subtitles"&&!this.J.has(t.language)&&t.language&&(g.CZ(this.B,new g.Ff({languageCode:t.language,languageName:t.language,kind:t.kind,id:t.id,displayName:duY[t.label]||t.label,vss_id:`.${t.language}`})),this.J.add(t.language))}g.U8(this.B).length>
0&&I.Og()}},vVf=class{constructor(){this.segments=[]}contains(I){I=g.kf(this.segments,I);return I>=0||I<0&&(-I-1)%2===1}length(){return this.segments.length/2}},c1w=class extends g.ZW{constructor(I,U,t,W,E,Z){super();this.policy=I;this.player=U;this.vK=t;this.U=W;this.T=E;this.N=Z;this.A=new vVf;this.G=-1;this.J=this.D=this.B=null;this.on=0;this.V=new g.bP(this.mu,1E3,this);this.events=new g.E9(this);g.J(this,this.V);g.J(this,this.events);this.events.L(U,"SEEK_COMPLETE",this.C);this.C();this.mu()}b0(){super.b0();
this.J&&this.J.cancel()}C(){this.seekTo(this.player.getCurrentTime())}seekTo(I){I-=this.player.jN();const U=this.B;this.B=g.KQ(this.vK.G(I).zg);U!==this.B&&this.N&&this.N()}reset(){this.A=new vVf;this.G=-1;this.J&&(this.J.cancel(),this.J=null)}mu(){this.Xe();var I;if(I=this.B!=null)I=this.B,I=I.vK.A(I);if(I&&!this.J&&!(this.B&&this.B.startTime-this.player.getCurrentTime()>30)){I=this.B;I=I.vK.u0(I);const E=I.zg[0];if(this.player.getVideoData()?.enableServerStitchedDai){var U=this.player.VN();if(U){var t=
E.vK.info.id;const Z=E.ZK;var W=I.zg[0].A;if(this.policy.yQ){if(U=g.Y0A(U,W,Z,t,3))I.A=U}else if(t=U.Cs(W,Z,t,3))if(W=2,U.h1.has(Z)?W=0:g.HX(U,Z)&&(W=1),U=W,U===0)t&&(I.B=new g.Q9(t));else if(U===2){this.V.start();niQ(this)&&this.seekTo(this.player.getCurrentTime());return}}}E.vK.index.Cb(E.ZK)?(this.A.contains(I.zg[0].ZK)||Vpw(this,I),this.B=g.KQ(I.zg)):niQ(this)&&this.seekTo(this.player.getCurrentTime())}this.V.start()}},$ue=class extends g.m5{constructor(I,U){super(U);this.J=I;this.Z=U;this.U=
null;this.mu=!1;this.logger=new g.m7("caps");this.on=g.ym(this.Z,this.J)}A(I,U,t){this.D();U=Mpw(this,I.getId());U||(U=I.languageCode,U=this.J.isManifestless?PaY(this,U,"386"):PaY(this,U));if(U){var W=(U.index.lz(U.index.UA())-U.index.getStartTime(U.index.UA()))*1E3,E=new g.Cnl(this.Z.S());this.U=new c1w(E,this.Z,U,(Z,H)=>{t.Bt(Z,I,H,W)},this.on||g.ma(U.info),()=>{this.U&&this.U.reset();
this.mu=!0})}}N(){const I=this.mu;
this.mu=!1;return I}T(I){var U=this.Z.S().K("html5_fallback_if_rawcc_missing");const t=this.J.B.rawcc!=null;if(!this.on||!t&&U)U=this.J.isManifestless?UFe(this,"386"):UFe(this);else{if(!t){g.gf(this.logger,386248249,"rawcc used but unavailable");return}U=[new g.Ff({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Ff({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const W of U)g.CZ(this.B,
W);I.Og()}D(){this.U&&(this.U.dispose(),this.U=null)}G(){return""}},dI=/^#(?:[0-9a-f]{3}){1,2}$/i;var uPx=["left","right","center","justify"];var jC=class extends g.V{constructor(I,U,t,W,E,Z,H,w,l,d){const K=d.isInline()&&!0,v={};Object.assign(v,U);Object.assign(v,I.params);Object.assign(v,t);const c={};Object.assign(c,U.Oo);I.params.Oo&&Object.assign(c,I.params.Oo);Object.assign(c,t.Oo);K&&(v.windowOpacity=.6,c.backgroundOpacity=0);v.Oo=c;const u=v.ZP===1,z=[{X:"span",Y:"captions-text",W:{style:"word-wrap: normal; display: block;"}}];(w=w.Cl("caption_edit_on_hover")&&d.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand)&&
z.unshift({X:"button",Y:"caption-edit",W:{tabindex:"0","aria-label":Rh0()},j:[{X:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{X:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({X:"div",Y:"caption-window",W:{id:`${"caption-window"}-${I.id}`,dir:u?"rtl":"ltr",tabindex:"0",lang:v.lang},j:z});this.G=
[];this.Js=!1;this.J=I;this.yQ=this.u0=null;this.gS=Z;this.KL=H;this.V=null;this.maxWidth=Z*.96;this.maxHeight=H*.96;this.B=v;this.lK=t;this.on=U;this.A=this.e6("captions-text");this.Y$=this.A.style.getPropertyValue("box-decoration-break")!==""||this.A.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.hs=tet(W,E,Z,H);this.Po=l;w&&(this.T=this.e6("caption-edit"),this.L(this.T,"click",()=>{this.Po()}));
this.type=0;this.Md=this.hs*WHw(c);this.dk=K;I=new g.Wb(this.element,!0);g.J(this,I);I.subscribe("dragstart",this.nL,this);I.subscribe("dragmove",this.Xt,this);I.subscribe("dragend",this.D5,this);this.j6=this.UJ=this.Nd=this.PK=0;I="";this.B.windowOpacity&&(I=RX(this.B.windowColor),I="rgba("+I[0]+","+I[1]+","+I[2]+","+this.B.windowOpacity+")");U={"background-color":I,display:this.B.isVisible===!1?"none":"","text-align":uPx[this.B.textAlign]};this.Y$&&(U["border-radius"]=I?`${this.Md/8}px`:"");(this.D=
this.J.params.ZP===2||this.J.params.ZP===3)&&EEt(this,this.element);g.B9(this.element,U);K&&this.element.parentElement?.style.setProperty("--caption-window-color",I);switch(this.B.Us){case 0:case 1:case 2:g.MV(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.MV(this.element,"ytp-caption-window-bottom")}}nL(I,U){this.UJ=I;this.j6=U;const t=g.Zf(this.element,this.element.parentElement);this.PK=I-t.x;this.Nd=U-t.y}Xt(I,U){if(I!==this.UJ||U!==this.j6){g.VM(this.element,"ytp-dragging")||
g.MV(this.element,"ytp-dragging");var t=g.lO(this.element);I=I-this.PK-.02*this.gS;var W=U-this.Nd-.02*this.KL,E=(I+t.width/2)/this.maxWidth*3;E=Math.floor(g.DC(E,0,2));var Z=(W+t.height/2)/this.maxHeight*3;Z=Math.floor(g.DC(Z,0,2));U=E+Z*3;I=(I+E/2*t.width)/this.maxWidth;I=g.DC(I,0,1)*100;t=(W+Z/2*t.height)/this.maxHeight;t=g.DC(t,0,1)*100;this.J.params.Us=U;this.J.params.R1=t;this.J.params.E4=I;this.J.params.isDefault=!1;this.B.Us=U;this.B.R1=t;this.B.E4=I;this.B.isDefault=!1;this.on.Us=U;this.on.R1=
t;this.on.E4=I;this.on.isDefault=!1;this.RF()}}D5(){g.Ih(this.element,"ytp-dragging")}RF(){this.U(this.G)}U(I){var U=this.dk?0:Math.min(this.wC(),this.maxWidth),t=this.oF(),W=this.dk;if(W){var E=getComputedStyle(this.A.parentNode);E=n9(E.borderLeftWidth)+n9(E.borderRightWidth)+n9(E.paddingLeft)+n9(E.paddingRight)}else E=0;const Z=E;E="";this.J.params.ZP===3&&(E="rotate(180deg)");var H=W?`calc(${"96%"} - ${Z}px)`:"96%";g.B9(this.element,{top:0,left:0,right:"",bottom:"",width:U?`${U}px`:"",height:t?
`${t}px`:"","max-width":H,"max-height":H,margin:"",transform:""});this.Rn(I);E={transform:E,top:"",left:"",width:U?`${U}px`:"",height:t?`${t}px`:"","max-width":"","max-height":""};var w=this.B.E4*.96+2;H=this.B.Us;switch(H){case 0:case 3:case 6:(W=this.B.Oo.fontSizeIncrement)&&W>0&&this.B.ZP!==2&&this.B.ZP!==3&&(w=Math.max(w/(1+W*2),2));E.left=`${w}%`;break;case 1:case 4:case 7:E.left=`${w}%`;w=this.A.offsetWidth;U||w?(U=U||w+1,E.width=`${U}px`,E["margin-left"]=W?`${U/-2-Z/2}px`:`${U/-2}px`):E.transform+=
" translateX(-50%)";break;case 2:case 5:case 8:E.right=`${100-w}%`}W=this.B.R1*.96+2;switch(H){case 0:case 1:case 2:E.top=`${W}%`;break;case 3:case 4:case 5:E.top=`${W}%`;(t=t||this.element.clientHeight)?(E.height=`${t}px`,E["margin-top"]=`${t/-2}px`):E.transform+=" translateY(-50%)";break;case 6:case 7:case 8:E.bottom=`${100-W}%`}g.B9(this.element,E);if(this.T){t=this.A.offsetHeight;W=1;for(U=0;U<I.length;U++)E=I[U],typeof E.text==="string"&&(W+=E.text.split("\n").length-1,E.append||U===0||W++);
t/=W;this.T.style.height=`${t}px`;this.T.style.width=`${t}px`;this.element.style.paddingLeft=`${t+5}px`;this.element.style.paddingRight=`${t+5}px`;I=Number(this.element.style.marginLeft.replace("px",""))-t-5;t=Number(this.element.style.marginRight.replace("px",""))-t-5;this.element.style.marginLeft=`${I}px`;this.element.style.marginRight=`${t}px`}}Rn(I){let U;for(U=0;U<I.length&&I[U]===this.G[U];U++);if(this.Js||this.G.length>U)U=0,this.Js=!1,this.G=[],this.V=this.yQ=this.u0=null,g.p1(this.A);for(;U<
I.length;U++)lCk(this,I[U])}wC(){return 0}oF(){return 0}toString(){return super.toString()}};var SWe=class{constructor(){this.D=this.time=this.mode=this.J=0;this.A=new hbL(this);this.T=new hbL(this);this.B=[];this.clear()}clear(){this.D=this.time=this.mode=0;this.B=[];this.reset()}reset(){this.mode=0;this.A.reset(0);this.T.reset(1)}},dFL=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],zbx=class{constructor(){this.type=0}set(I){this.type=I}get(){return this.type}},LUx=class{constructor(){this.state=this.Sa=this.E6=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Gc(){return this.state!==0}matches(I,U){return this.Gc()&&I===this.E6&&U===this.Sa}},p9Y=class{constructor(){this.timestamp=this.B=0}reset(){this.timestamp=
this.B=0}},AH=class{constructor(I){this.T=I;this.D=[];this.B=this.J=this.row=0;this.style=new zbx;this.A=0;for(I=0;I<=15;I++){this.D[I]=[];for(let U=0;U<=32;U++)this.D[I][U]=new p9Y}}updateTime(I){for(let U=1;U<=15;++U)for(let t=1;t<=32;++t)this.D[U][t].timestamp=I}debugString(){let I="\n";for(let U=1;U<=15;++U){for(let t=1;t<=32;++t){const W=this.D[U][t];I=W.B===0?I+"_":I+String.fromCharCode(W.B)}I+="\n"}return I}reset(I){for(let U=0;U<=15;U++)for(let t=0;t<=32;t++)this.D[U][t].reset();this.A=I;
this.B=0;this.J=this.row=1}},uOf=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],hy$=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Sm0=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],zyV=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],muw=class{constructor(I){this.D=I;this.T=0;this.style=new zbx;this.G=new AH(this.D);this.V=new AH(this.D);this.text=new AH(this.D);this.J=this.G;this.A=this.V;this.B=this.J}reset(I,U){this.T=U;this.style.set(2);this.J=this.G;this.A=this.V;this.B=this.J;const t=(I<<2)+(U<<1);this.G.reset(t);this.V.reset(t);
this.text.reset((I<<2)+(U<<1)+1)}},hbL=class{constructor(I){this.B=I;this.T=0;this.D=new muw(this.B);this.G=new muw(this.B);this.J=new LUx;this.A=this.D}reset(I){this.T=I;this.J.clear();this.A=this.D;this.D.reset(I,0);this.G.reset(I,1)}};var gVe=class{A(){}};var Wg=class extends g.jd{constructor(I,U,t,W,E,Z=!1,H=null){super(I,I+U,{priority:t,namespace:"captions"});this.windowId=W;this.text=E;this.append=Z;this.B=H}toString(){return super.toString()}};var sg=class extends g.ZW{reset(){}};var Zn=class extends g.jd{constructor(I,U,t,W,E){super(I,I+U,{priority:t,namespace:"captions"});this.id=W;this.params=E;this.B=[]}toString(){return super.toString()}},Eg=0;var C6k=class extends sg{constructor(I){super();this.A=I;this.pens={};this.U={};this.C={};this.T="_"+Eg++;this.V={};this.J=this.B=null;this.G=!0}reset(){this.V={};this.J=this.B=null;this.G=!0}D(I,U){I=I.firstChild;I.getAttribute("format");U=U||0;Number.isFinite(U);I=Array.from(I.childNodes);for(var t of I)if(t.nodeType===1)switch(t.tagName){case "head":var W=t;break;case "body":var E=t}if(W){W=Array.from(W.childNodes);for(var Z of W)if(Z.nodeType===1)switch(Z.tagName){case "pen":t=Z.getAttribute("id");
W=this.pens;I={};var H=Z.getAttribute("p");H&&Object.assign(I,this.pens[H]);H=wI(Z,"b");H!=null&&(I.bold=H);H=wI(Z,"i");H!=null&&(I.italic=H);H=wI(Z,"u");H!=null&&(I.underline=H);H=lJ(Z,"et");H!=null&&(I.charEdgeStyle=H);H=lJ(Z,"of");H!=null&&(I.offset=H);H=Ki(Z,"bc");H!=null&&(I.background=H);H=Ki(Z,"ec");H!=null&&(I.oQ=H);H=Ki(Z,"fc");H!=null&&(I.color=H);H=lJ(Z,"fs");H!=null&&H!==0&&(I.fontFamily=H);H=Hg(Z,"sz");H!==void 0&&(I.fontSizeIncrement=H/100-1);H=Hg(Z,"bo");H!==void 0&&(I.backgroundOpacity=
H/255);H=Hg(Z,"fo");H!==void 0&&(I.textOpacity=H/255);H=lJ(Z,"rb");H!=null&&H!==10&&H!==0&&(I.zZ=H>10?H-1:H);H=lJ(Z,"hg");H!=null&&(I.G8=H);W[t]=I;break;case "ws":W=Z.getAttribute("id");this.C[W]=Q0w(this,Z);break;case "wp":W=Z.getAttribute("id"),this.U[W]=fCH(this,Z)}}if(E){Z=[];E=Array.from(E.childNodes);for(y of E)if(y.nodeType===1)switch(y.tagName){case "w":this.B=j0Y(this,y,U,!1);(E=this.V[this.B.id])&&E.end>this.B.start&&(E.end=this.B.start);this.V[this.B.id]=this.B;Z.push(this.B);break;case "p":var w=
y;I=U;E=[];W=w.getAttribute("w")||this.T;t=!!wI(w,"a");I=(Hg(w,"t")||0)+I;H=Hg(w,"d")||5E3;t||(!this.G&&this.J&&this.J.windowId===W&&this.J.end>I&&(this.J.end=I),this.J&&this.J.text==="\n"&&(this.J.text=""));const a=t?6:5;var l=w.getAttribute("p");l=l?this.pens[l]:null;const Y=Array.from(w.childNodes);Y.length&&(this.G=w.getAttribute("d")!=null);for(w=0;w<Y.length;w++){var d=Y[w],K=void 0;w>0&&(t=!0);let N;d.nodeType===1&&(N=d);if(N&&N.tagName==="s"){if((d=(d=N.getAttribute("p"))?this.pens[d]:null)&&
d.zZ&&(d.zZ===1?(d=Y.slice(w,w+4),d.length===4&&(K=yp6(I,H,W,t,a,d,this.pens),w+=3)):K=yp6(I,H,W,t,a,[N],this.pens)),!K){var v=N;K=I;d=H;var c=W,u=t;const k=v.textContent?v.textContent:"";var z=v.getAttribute("p");z=z?this.pens[z]:null;v=Hg(v,"t")||0;K=new Wg(K+v,d-v,a,c,k,u,z)}}else K=new Wg(I,H,a,W,d.textContent||"",t,l);E.push(K);this.J=K}if(E.length>0){E[0].windowId===this.T&&(this.B=j0Y(this,y,U,!0),Z.push(this.B));for(const N of E)N.windowId=this.B.id,this.B.B.push(N),Z.push(N)}}var y=Z}else y=
[];return y}};var y1e=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),FUL=class extends sg{constructor(I){super();this.G=I;this.B=new Map;this.A=new Map;this.T=new Map;this.J=new Map}reset(){this.J.clear()}D(I,U){I=JSON.parse(I);if(!I)return[];if(I.pens){var t=I.pens,W=0;for(var E of t){t={};var Z=E.pParentId;Z&&Object.assign(t,this.B.get(Z));E.bAttr&&(t.bold=!0);E.iAttr&&(t.italic=!0);E.uAttr&&(t.underline=!0);Z=E.ofOffset;Z!=null&&(t.offset=Z);E.szPenSize!==void 0&&(t.fontSizeIncrement=E.szPenSize/100-1);
Z=E.etEdgeType;Z!=null&&(t.charEdgeStyle=Z);E.ecEdgeColor!==void 0&&(t.oQ=vg(E.ecEdgeColor));Z=E.fsFontStyle;Z!=null&&Z!==0&&(t.fontFamily=Z);E.fcForeColor!==void 0&&(t.color=vg(E.fcForeColor));E.foForeAlpha!==void 0&&(t.textOpacity=E.foForeAlpha/255);E.bcBackColor!==void 0&&(t.background=vg(E.bcBackColor));E.boBackAlpha!==void 0&&(t.backgroundOpacity=E.boBackAlpha/255);(Z=E.rbRuby)&&Z!==10&&(t.zZ=Z>10?Z-1:Z,t.textEmphasis=y1e.get(t.zZ));E.hgHorizGroup&&(t.G8=E.hgHorizGroup);this.B.set(W++,t)}}if(I.wsWinStyles){W=
I.wsWinStyles;E=0;for(var H of W)W={},(t=H.wsParentId)?Object.assign(W,this.T.get(t)):Object.assign(W,this.G),H.mhModeHint!==void 0&&(W.QC=H.mhModeHint),H.juJustifCode!==void 0&&(W.textAlign=H.juJustifCode),H.pdPrintDir!==void 0&&(W.ZP=H.pdPrintDir),H.sdScrollDir!==void 0&&(W.OL=H.sdScrollDir),H.wfcWinFillColor!==void 0&&(W.windowColor=vg(H.wfcWinFillColor)),H.wfoWinFillAlpha!==void 0&&(W.windowOpacity=H.wfoWinFillAlpha/255),this.T.set(E++,W)}if(I.wpWinPositions){E=I.wpWinPositions;H=0;for(var w of E)E=
{},(W=w.wpParentId)&&Object.assign(E,this.A.get(W)),w.ahHorPos!==void 0&&(E.E4=w.ahHorPos),w.apPoint!==void 0&&(E.Us=w.apPoint),w.avVerPos!==void 0&&(E.R1=w.avVerPos),w.ccCols!==void 0&&(E.gp=w.ccCols),w.rcRows!==void 0&&(E.oN=w.rcRows),this.A.set(H++,E)}if(I.events){I=I.events;w=[];for(const G of I)if(H=(G.tStartMs||0)+U,E=G.dDurationMs||0,G.id)W=String(G.id),I=ApL(this,G,H,E,W),w.push(I),this.J.set(W,I);else{G.wWinId?W=G.wWinId.toString():(W="_"+Eg++,I=ApL(this,G,H,E,W),w.push(I),this.J.set(W,I));
I=w;var l=G;E===0&&(E=5E3);t=this.J.get(W);const Ec=(Z=!!l.aAppend)?6:5,wA=l.segs;let x5=null;l.pPenId&&(x5=this.B.get(l.pPenId));for(l=0;l<wA.length;l++){var d=wA[l],K=d.utf8;if(K){var v=d.tOffsetMs||0;let pm=null;d.pPenId&&(pm=this.B.get(d.pPenId));if((t.params.QC!=null?t.params.QC:t.B.length>1?1:0)===2&&Z&&K==="\n")continue;d=null;var c=[],u;if(u=pm&&pm.zZ===1){u=wA;var z=l;if(z+3>=u.length||!u[z+1].pPenId||!u[z+2].pPenId||!u[z+3].pPenId)u=!1;else{var y=u[z+1].pPenId;(y=this.B.get(y))&&y.zZ&&y.zZ===
2?(y=u[z+2].pPenId,y=this.B.get(y),!y||!y.zZ||y.zZ<3?u=!1:(y=u[z+3].pPenId,u=(y=this.B.get(y))&&y.zZ&&y.zZ===2?!0:!1)):u=!1}}if(u)v=wA[l+1].utf8,d=wA[l+3].utf8,u=wA[l+2].utf8,z=this.B.get(wA[l+2].pPenId),K=ClV(K,v,u,d,z),d=new Wg(H,E,Ec,W,K,Z,pm),l+=3;else{if(K.indexOf("<")>-1){c=pm;u=x5;z=H;y=E;var a=v,Y=Ec,N=Z;const rA=[];var k=g.EY(`<html>${K}</html>`);if(!k.getElementsByTagName("parsererror").length&&k.firstChild?.childNodes.length)for(const nm of k.firstChild.childNodes){k=nm.textContent?.replace(/\n/g,
"")??"";if(nm.nodeType===3&&(!k||k.match(/^ *$/)!=null))continue;const jp={};Object.assign(jp,c||u);switch(nm?.tagName){case "b":jp.bold=!0;break;case "i":jp.italic=!0;break;case "u":jp.underline=!0}rA.push(new Wg(z+a,y-a,Y,t.id,k,N,jp))}c=rA}c.length||(c=[new Wg(H+v,E-v,Ec,t.id,K,Z,pm||x5)])}if(c.length)for(const rA of c)I.push(rA),t.B.push(rA);else d&&(I.push(d),t.B.push(d))}Z=!0}}U=w}else U=[];return U}};var QR0=class extends g.m5{constructor(I,U,t){super(I);this.videoData=U;this.audioTrack=t;this.C=U.pH}A(I,U,t){btw(this.videoData.videoId,I.vssId,t.Bt)}T(I){if(this.audioTrack)for(const U of this.audioTrack.captionTracks)g.CZ(this.B,U);I.Og()}};var H1w=class extends jC{constructor(I,U,t,W,E,Z,H,w,l,d){super(I,U,t,W,E,Z,H,w,l,d);this.type=1}Rn(I){const U=this.J.B;super.Rn(I);let t,W;for(I=I.length;I<U.length;I++){const E=U[I];let Z;W&&E.B===t?Z=W:(Z={},Object.assign(Z,E.B),Object.assign(Z,fuf),t=E.B,W=Z);lCk(this,E,Z)}}},fuf={cj:!0};var s0x=class extends gVe{constructor(I,U){super();this.trackData=I;this.G=U;this.version=this.T=this.D=this.byteOffset=0;this.J=[];this.B=new DataView(this.trackData)}A(I,U,t,W,E){if(t<W){const Z="_"+Eg++;t=t/1E3-this.G;W=W/1E3-this.G;I=new Zn(t,W-t,5,Z,{textAlign:0,Us:0,E4:U*2.5,R1:I*5.33});E=new Wg(t,W-t,5,Z,E);this.J.push(I);this.J.push(E)}}},jRt=class extends sg{constructor(I,U){super();this.J=I;this.A=U;this.track=this.A.languageName==="CC3"?4:0;this.B=new SWe;this.B.J=1<<this.track}D(I){I=
new s0x(I,this.J);if(aCL(I)){for(;I.byteOffset<I.B.byteLength;)for(I.version===0?I.D=$_(I)*(1E3/45):I.version===1&&(I.D=$_(I)*4294967296+$_(I)),I.T=cg(I);I.T>0;I.T--){var U=cg(I);const t=cg(I),W=cg(I);U&4&&(U&3)===this.track&&(this.track===0||this.track===1)&&(U=this.B,U.B.push({time:I.D,type:this.track,L1:t,SU:W,order:U.B.length}))}$Ff(this.B,I);return I.J}return[]}reset(){this.B.clear()}};var w9L=class extends jC{constructor(I,U,t,W,E,Z,H,w,l,d){super(I,U,t,W,E,Z,H,w,l,d);this.type=2;this.wk=[];this.N=this.C=this.QQ=0;this.l0=NaN;this.k$=0;this.iU=null;this.SN=new g.bP(this.qd,433,this);this.T&&(d.createClientVe(this.T,this,167342),this.L(this.T,"click",()=>{d.logClick(this.T)}),I=new g.Wb(this.element,!0),g.J(this,I),I.subscribe("hoverstart",()=>{d.logVisibility(this.T,!0)},this));
g.MV(this.element,"ytp-caption-window-rollup");g.J(this,this.SN);g.B9(this.element,"overflow","hidden")}RF(){g.BD(this.SN)}qd(){this.element.removeEventListener("transitionend",this.qd,!1);g.Ih(this.element,"ytp-rollup-mode");this.U(this.iU,!0)}oF(){return this.D?this.N:this.C}wC(){return this.D?this.C:this.N}U(I,U){this.iU=I;if(this.J.params.oN){var t=0;for(let W=0;W<this.G.length&&t<I.length;W++)this.G[W]===I[t]&&t++;t>0&&t<I.length&&(I=this.G.concat(I.slice(t)));this.k$=this.N;this.C=this.N=0;
super.U(I);XTf(this,U)}super.U(I)}};var A1V=class{constructor(I,U,t,W){this.Z=I;this.D=U;this.logger=t;this.Tk=W;this.J3=[];this.b_=[];this.B=null;this.aF={lSs:()=>this.B,
Zq:()=>this.J3};
I=g.ri(this.Z.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.J=I>0?I:10}unload(){this.B!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.B),this.B=null);this.J3=[];this.Z.publish("sabrCaptionsBufferedRangesUpdated",this.J3)}AQ(I){return{formatId:g.Cu(I.info.vK.info,this.Tk),ZK:I.info.ZK+(this.Tk?0:1),startTimeMs:I.info.A*1E3,durationMs:I.info.U*1E3}}};var sRk=class extends g.m5{constructor(I,U){super(U);this.J=I;this.Z=U;this.logger=new g.m7("caps");this.U=this.mu=null;this.on=new A1V(this.Z,this,this.logger,this.J.Tk)}A(I,U,t){this.D();U=I.getId();U=U!=null&&U in this.J.B?this.J.B[U]:null;U||(U=I.languageCode,U=this.J.isManifestless?DFY(this,U,"386"):DFY(this,U));U&&(this.U=I,this.mu=U,Ymw(this.on,t),this.Z.publish("sabrCaptionsTrackChanged",g.Cu(U.info,this.J.Tk)))}T(I){var U=this.J.isManifestless?xFY(this,"386"):xFY(this);for(const t of U)g.CZ(this.B,
t);I.Og()}D(){this.U&&(this.U=this.mu=null,this.on.unload(),this.Z.publish("sabrCaptionsTrackChanged",null))}G(){return""}};var rpQ="WEBVTT".split("").map(I=>I.charCodeAt(0)),T9H=class extends sg{constructor(){super()}D(I,U){I instanceof ArrayBuffer&&(I=g.ye(new Uint8Array(I)));
const t=[];I=I.split(auk);for(let z=1;z<I.length;z++){var W=I[z],E=U;if(W!==""&&!Nc0.test(W)){var Z=aO.exec(W);if(Z&&Z.length>=4){var H=uJ(Z[1]),w=uJ(Z[2])-H;H+=E;var l=(Z=Z[3])?Z.split(" "):[];Z={};var d=null;var K="";var v=null,c="";for(const y of l)if(l=y.split(":"),l.length===2){var u=l[1];switch(l[0]){case "line":l=u.split(",");l[0].endsWith("%")&&(d=l[0],Z.R1=Number.parseInt(d,10),l.length===2&&(K=l[1].trim()));break;case "position":l=u.split(",");v=l[0];Z.E4=Number.parseInt(v,10);l.length===
2&&(c=l[1].trim());break;case "align":switch(u){case "start":Z.textAlign=0;break;case "middle":Z.textAlign=2;break;case "end":Z.textAlign=1}}}d||K||(K="end");if(!v)switch(Z.textAlign){case 0:Z.E4=0;break;case 1:Z.E4=100;break;case 2:Z.E4=50}if(Z.textAlign!=null){d=0;switch(K){case "center":d+=3;break;case "end":d+=6;break;default:d+=0}switch(c){case "line-left":d+=0;break;case "center":d+=1;break;case "line-right":d+=2;break;default:switch(Z.textAlign){case 0:d+=0;break;case 2:d+=1;break;case 1:d+=
2}}K=d<0||d>8?7:d;Z.Us=K}W=W.substring(aO.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");c=Z;Z=W;W={};if(Z.indexOf("<")<0&&Z.indexOf("&")<0)E=qmL(H,w,5,c),w=new Wg(H,w,5,E.id,Z,!1,g.tD(W)?void 0:W),t.push(E),t.push(w),E.B.push(w);else for(K=Z.split(J1t),K.length===1?(Z=5,c=qmL(H,w,Z,c)):(d=Z=6,c=Object.assign({gp:32},c),c=new Zn(H,w,d,"_"+Eg++,c)),t.push(c),d=H,v=0;v<K.length;v++)if(l=K[v],v%2===0){u=g.EY(`<html>${l}</html>`);let y;u.getElementsByTagName("parsererror").length?(y=u.createElement("span"),
y.appendChild(u.createTextNode(l))):y=u.firstChild;eyL(this,d,w-(d-H),Z,c,v>0,y,W,t)}else d=uJ(l)+E}aO.lastIndex=0}}return t}},Nc0=/^NOTE/,auk=/(?:\r\n|\r|\n){2,}/,aO=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),J1t=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var oVf=class extends g.ZW{constructor(I,U){super();this.Z=I;this.O=U;this.B=null;this.qt=this.Z.VN();this.logger=new g.m7("caps")}clear(){this.B&&this.B.dispose();this.B=null}reset(){this.B&&this.B.reset()}b0(){super.b0();this.clear()}};var hH={windowColor:"#080808",windowOpacity:0,textAlign:2,Us:7,E4:50,R1:100,isDefault:!0,Oo:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.g7("captions",class extends g.p0{constructor(I){super(I);this.Z=I;this.Js=[];this.on={};this.Rn={};this.V=!1;this.D="NONE";this.J=this.C=this.mu=this.QQ=this.UJ=null;this.Nd={Og:()=>{this.Og()},
Bt:(W,E,Z,H,w=0)=>{const l=Number(this.videoData.S().Wo().B.OJ(g.Qcz)??0);w>0&&l>0&&this.videoData.lengthSeconds>0&&w/this.videoData.lengthSeconds>l?this.Z.EJ("tts",{dropcap:w}):this.Bt(W,E,Z,H)}};
this.B=null;this.O=this.Z.S();this.videoData=this.Z.getVideoData();this.PK=this.Z.sJ();this.T={Oo:{}};this.G={Oo:{}};this.videoData.RF()?this.D="OFFLINE":g.Jcz(this.videoData,this.Z)?this.D="HLS":kv0(this.videoData,this.Z)?this.D="SABR_LIVE":g.oIS(this.videoData,this.Z)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.k$&&(this.D="TTS");this.hs=this.O.controlsType==="3";this.qd=new oVf(this.Z,this.O);this.wk=new g.E9(this);this.U=new g.V({X:"div",Y:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});this.N={top:0,right:0,bottom:0,left:0,width:1,height:1};let U=null;const t=g.kp("yt-html5-player-modules::subtitlesModuleData");t&&(U=new g.Fu(t));this.storage=U;this.j6=!!I.iK()?.l0();this.A=nEH(this);this.l0=!this.A&&this.hs&&this.j6&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.J(this,this.qd);this.A?this.yQ=this.u0=null:(this.u0=new g.Gf(this.wC,void 0,this),g.J(this,this.u0),this.yQ=new g.bP(this.Y$,2E3,this),g.J(this,this.yQ));g.J(this,this.wk);g.zp(this.player,
this.U.element,4);g.J(this,this.U);this.A||this.wk.L(I,"resize",this.dk);(this.oF=g.ka(this.O)&&!g.b0()&&!this.Z.isFullscreen()&&!this.A&&!this.l0)&&this.wk.L(I,"resize",this.k$);this.wk.L(I,"onPlaybackAudioChange",this.Gk);this.wk.L(I,g.EZ("captions"),W=>{this.onCueRangeEnter(W)});
this.wk.L(I,g.Zl("captions"),W=>{this.onCueRangeExit(W)});
SC(this,OT()||{});g.PS(this.player,"onCaptionsModuleAvailable");this.D==="HLS"&&this.A&&(I=this.Z.iK().fu(),this.j6&&this.wk.L(I.textTracks,"addtrack",this.RF))}b0(){if(this.A||this.l0){const I=this.Z.iK();I&&!I.Xe()&&I.V()}else zR(this,!1);super.b0()}Vq(){return this.O.K("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"}tN(){if(this.hs)return this.A||this.l0;if(this.D==="HLS")return this.A;var I=this.getAudioTrack();if(this.Vq()){if(!I.captionTracks.length)return!1;
if(!this.J)return!0}I=Tj(I,g.Ut(this.O));return I==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:I==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?pi(this):Li(this)||pi(this)?!0:Pl6(this)}load(){super.load();this.C=this.getAudioTrack();if(this.J)this.B&&(this.qd.clear(),this.A?Iuw(this,!0):this.player.getPresentingPlayerType()!==3&&this.J.A(this.B,"json3",this.Nd),this.D!=="HLS"&&this.A||this.l0||mP(this)||g.PS(this.player,"captionschanged",g.Ld(this.B)));else{let I;this.D==="OFFLINE"?I=new QR0(this.player,this.videoData,
this.getAudioTrack()):this.D==="SABR_LIVE"?I=new sRk(this.videoData.B,this.player):this.D==="HLS"?I=new KUw(this.player):this.D==="LIVE"?I=new $ue(this.videoData.B,this.player):this.D==="INNERTUBE"?I=new g.gh(this.player,this.videoData,this.getAudioTrack()):I=new g.C0(this.player,this.videoData.k$,this.videoData.videoId,g.FAc(this.videoData),this.videoData.rA,this.videoData.eventId);this.J=I;g.J(this,this.J);this.J.T(this.Nd)}}unload(){this.A&&this.B?Iuw(this,!1):(this.yQ&&this.yQ.U4(),this.player.RW("captions"),
this.Js=[],this.J&&this.J.D(),this.qd.clear(),this.mu&&this.player.d8(this.mu),this.dk());super.unload();this.player.fv();g.PS(this.player,"captionschanged",{})}create(){this.tN()&&this.load();var I;a:{if(this.O.K("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(I=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const U of I)if(U.kind==="asr"&&U.languageCode===
"en"){I=!0;break a}I=!1}I&&this.Z.publish("showpromotooltip",this.U.element)}Og(){var I=Tj(this.player.getAudioTrack(),g.Ut(this.O));var U=I==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Ci(this,this.V):I==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&pi(this)?gI(this):Li(this)||this.V||Pl6(this)?Ci(this,this.V):pi(this)?gI(this):null;if(this.D!=="HLS"&&this.A||this.l0){const t=g.U8(this.J.B,!0);I=[];for(let W=0;W<t.length;W++){const E=t[W],Z=g.Sy("TRACK");Z.setAttribute("kind","subtitles");Z.setAttribute("label",
g.zL(E));Z.setAttribute("srclang",g.pd(E));Z.setAttribute("id",E.toString());this.l0||Z.setAttribute("src",this.J.G(E,"vtt"));E===U&&Z.setAttribute("default","1");I.push(Z)}U=this.Z.iK();U.mu(I);I=U.fu();this.j6&&this.wk.L(I.textTracks,"change",this.SN)}else!this.B&&U&&fi(this,U),g.PS(this.player,"onCaptionsTrackListChanged"),g.IJ(this.player,"onApiChange")}getTrackById(I){const U=g.U8(this.J.B,!0);for(let t=0;t<U.length;t++)if(U[t].toString()===I)return U[t];return null}SN(){const I=this.Z.iK().fu().textTracks;
let U=null;for(let t=0;t<I.length;t++)I[t].mode==="showing"&&(U=this.getTrackById(I[t].id));(this.loaded?this.B:null)!==U&&fi(this,U,!0)}RF(){this.J?.T(this.Nd)}uP(){!this.B&&this.A||this.unload()}Bt(I,U,t,W){if(I){QS(this,this.B??void 0);this.J.N()&&(this.Js=[],this.Z.RW("captions"),BM(this.u0),this.qd.reset());a:{var E=this.qd;W=W||0;t=B96(E,I,t||0);I=[];try{for(const Y of t){const N=Y.trackData,k=Y.fm,G=E.O.K("safari_live_drm_captions_fix");if(typeof N!=="string"){t=I;var Z=t.concat;if(G&&Gvk(N))var H=
Ry$(E,N,k);else{var w=E,l=U,d=N,K=k,v=W;if(!N9w(d))throw Error("Invalid binary caption track data");w.B||(w.B=new jRt(v,l));H=w.B.D(d,K)}var c=Z.call(t,H)}else{if(N.substring(0,6)==="WEBVTT")var u=I.concat(Ry$(E,N,k));else{t=I;var z=t.concat;b:{l=E;w=U;if(N[0]==="{")try{l.B||(l.B=new FUL(OWQ(w)));var y=l.B.D(N,k);break b}catch(x5){g.b(x5);y=[];break b}const Ec=g.EY(N);if(!Ec||!Ec.firstChild){const x5=Error("Invalid caption track data");x5.params=N;throw x5;}if(Ec.firstChild.tagName==="timedtext"){if(Number(Ec.firstChild.getAttribute("format"))===
3){d=Ec;l.B||(l.B=new C6k(OWQ(w)));y=l.B.D(d,k);break b}const x5=Error("Unsupported subtitles format in web player (Format2)");x5.params=N;throw x5;}if(Ec.firstChild.tagName==="transcript"){const x5=Error("Unsupported subtitles format in web player (Format1)");x5.params=N;throw x5;}const wA=Error("Invalid caption track data");wA.params=N;throw wA;}u=z.call(t,y)}c=u}I=c}var a=I;break a}catch(Y){g.gf(E.logger,187101178,`Captions parsing failed: ${Y.message}. `);E.clear();a=[];break a}a=void 0}U=a;U.length>
0&&(a=this.B,this.Fw(a,!!a,mP(this)?"g":this.V?"m":"s"));this.player.d8(U,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");!this.V||this.l0||mP(this)||g.Be(this.O)||g.Ya(this.O)||g.TD(this.O)||this.O.on==="shortspage"||this.player.isInline()||(this.yQ.U4(),U=FHH({Us:0,E4:5,R1:5,oN:2,textAlign:0,ZP:0,lang:"en"}),this.QQ=[U],a=["Click "," for settings"],this.UJ||(E=new g.gl(g.QX()),g.J(this,E),this.UJ=E.element),E=U.end-U.start,(c=g.zL(this.B))&&this.QQ.push(new Wg(U.start,E,0,U.id,c)),this.QQ.push(new Wg(U.start,
E,0,U.id,a[0]),new Wg(U.start,E,0,U.id,this.UJ,!0),new Wg(U.start,E,0,U.id,a[1],!0)),this.player.d8(this.QQ),this.yQ.cL());!this.V||this.l0||mP(this)||(g.Ut(this.O)?yS(this,!0):FH(this,!0),this.C&&(this.C.A=this.B),this.player.fv());this.V=!1}}onCueRangeEnter(I){this.Js.push(I);BM(this.u0)}onCueRangeExit(I){g.jk(this.Js,I);this.J instanceof $ue&&this.J.on&&this.player.xY([I]);BM(this.u0)}getCaptionWindowContainerId(){return this.U.element.id}Y$(){VeH(this,this.QQ);this.QQ=null}wC(){if(!this.oF||!this.A){this.u0.stop();
g.Wq(this.Rn);this.Js.sort(g.WO);var I=this.Js;if(this.mu){const U=g.h$(I,function(t){return this.mu.indexOf(t)===-1},this);
U.length&&(I=U)}for(const U of I)U instanceof Zn?WUt(this,U):EV6(this,U);for(const [U,t]of Object.entries(this.on)){const W=U,E=t;this.Rn[W]?(E.element.parentNode||(E instanceof w9L||E instanceof H1w||g.hW(this.on,(Z,H)=>{H!==W&&Z.J.params.Us===E.J.params.Us&&Z.J.params.E4===E.J.params.E4&&Z.J.params.R1===E.J.params.R1&&(Z.dispose(),delete this.on[H]);return H===W},this),this.U.element.appendChild(E.element)),E.U(this.Rn[W])):(E.dispose(),delete this.on[W])}}}rB(){SC(this,{},!0);
g.PS(this.player,"captionssettingschanged")}f3(){var I=hH.Oo;I={background:I.background,backgroundOpacity:I.backgroundOpacity,charEdgeStyle:I.charEdgeStyle,color:I.color,fontFamily:I.fontFamily,fontSizeIncrement:I.fontSizeIncrement,fontStyle:I.bold&&I.italic?3:I.bold?1:I.italic?2:0,textOpacity:I.textOpacity,windowColor:hH.windowColor,windowOpacity:hH.windowOpacity};const U=OT()||{};U.background!=null&&(I.background=U.background);U.backgroundOverride!=null&&(I.backgroundOverride=U.backgroundOverride);
U.backgroundOpacity!=null&&(I.backgroundOpacity=U.backgroundOpacity);U.backgroundOpacityOverride!=null&&(I.backgroundOpacityOverride=U.backgroundOpacityOverride);U.charEdgeStyle!=null&&(I.charEdgeStyle=U.charEdgeStyle);U.charEdgeStyleOverride!=null&&(I.charEdgeStyleOverride=U.charEdgeStyleOverride);U.color!=null&&(I.color=U.color);U.colorOverride!=null&&(I.colorOverride=U.colorOverride);U.fontFamily!=null&&(I.fontFamily=U.fontFamily);U.fontFamilyOverride!=null&&(I.fontFamilyOverride=U.fontFamilyOverride);
U.fontSizeIncrement!=null&&(I.fontSizeIncrement=U.fontSizeIncrement);U.fontSizeIncrementOverride!=null&&(I.fontSizeIncrementOverride=U.fontSizeIncrementOverride);U.fontStyle!=null&&(I.fontStyle=U.fontStyle);U.fontStyleOverride!=null&&(I.fontStyleOverride=U.fontStyleOverride);U.textOpacity!=null&&(I.textOpacity=U.textOpacity);U.textOpacityOverride!=null&&(I.textOpacityOverride=U.textOpacityOverride);U.windowColor!=null&&(I.windowColor=U.windowColor);U.windowColorOverride!=null&&(I.windowColorOverride=
U.windowColorOverride);U.windowOpacity!=null&&(I.windowOpacity=U.windowOpacity);U.windowOpacityOverride!=null&&(I.windowOpacityOverride=U.windowOpacityOverride);return I}DE(I,U){const t={};Object.assign(t,OT());Object.assign(t,I);SC(this,t,U);g.PS(this.player,"captionssettingschanged")}dk(){!this.A&&this.loaded&&(g.tW(this.on,function(I,U){I.dispose();delete this.on[U]},this),this.wC())}LX(I,U){switch(I){case "fontSize":if(isNaN(U))break;
I=g.DC(U,-2,4);this.DE({fontSizeIncrement:I});return I;case "reload":U&&!this.A&&fi(this,this.B,!0);break;case "stickyLoading":U!==void 0&&this.O.U&&(g.Ut(this.O)?yS(this,!!U):FH(this,!!U));break;case "track":return luV(this,U);case "tracklist":return this.J?g.Sk(g.U8(this.J.B,!(!U||!U.includeAsr)),t=>g.Ld(t)):[];
case "translationLanguages":return this.J?this.J.C.map(t=>Object.assign({},t)):[];
case "sampleSubtitles":this.A||U===void 0||zR(this,!!U);break;case "sampleSubtitlesCustomized":this.A||zR(this,!!U,U);break;case "recommendedTranslationLanguages":return g.q4();case "defaultTranslationSourceTrackIndices":return this.J?this.J.wk:[]}}getOptions(){const I="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.O.U&&I.push("stickyLoading");return I}Dr(){let I=this.B;if(this.Z.Ev("captions")){if(this.O.K("html5_modify_caption_vss_logging"))return(I=this.videoData.IN??
null)?{cc:g.u_m(I)}:{};if(I){let U=I.vssId;I.translationLanguage&&U&&(U=`t${U}.${g.pd(I)}`);return{cc:U}}}return{}}Ej(){this.isSubtitlesOn()?(g.Ut(this.O)?yS(this,!1):FH(this,!1),QS(this),fi(this,null,!0)):this.jf()}jf(){const I=mP(this)||!this.B?Ci(this,!0):this.B;I&&this.GA(I.vssId,"m");this.isSubtitlesOn()||fi(this,mP(this)||!this.B?Ci(this,!0):this.B,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.B&&!mP(this)}Gk(){const I=mP(this);pi(this,I)?fi(this,this.getAudioTrack().B,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.Vq()&&(this.V=!1,this.B=null,this.J&&(this.J.dispose(),this.J=null)),this.tN()&&(I?fi(this,Ci(this,!1),!1):this.load()))}Vy(I){I&&(this.N={top:I.top,right:I.right,bottom:I.bottom,left:I.left,width:1-I.left-I.right,height:1-I.top-I.bottom},this.U.element.style.top=`${this.N.top*100}%`,this.U.element.style.left=`${this.N.left*100}%`,this.U.element.style.width=`${this.N.width*100}%`,this.U.element.style.height=`${this.N.height*100}%`,this.U.element.style.position="absolute",
I=Z1L(this))&&(this.U.element.style.width=`${I.width}px`,this.U.element.style.height=`${I.height}px`)}onVideoDataChange(I,U){I==="newdata"&&(this.videoData=U,this.loaded&&this.unload(),this.V=!1,this.B=null,this.J&&(this.J.dispose(),this.J=null,g.PS(this.player,"captionschanged",{})),this.tN()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}k$(){const I=this.Z.iK();I&&!I.Xe()&&I.V();this.Z.isFullscreen()?(this.A=this.hs=!0,this.loaded&&this.Og()):(this.hs=this.O.controlsType==="3",
this.A=nEH(this));fi(this,this.B)}Md(){const I=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;I&&g.Of(this.player,"innertubeCommand",I)}Fw(I,U,t){const W=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let E="";I&&(E=I.vssId,E=E.replace(W,""));let Z="";I&&I.getId()&&(Z=I.getId()||"");I&&I.getXtags()&&(I=I.getXtags(),I=I.replace(W,""),Z=Z.concat(`;${I}`));this.D==="HLS"&&(Z="");this.Z.Fw(U?E:"",U?Z:"",t)}GA(I,U){I=(I||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");I.length>0&&this.Z.GA(I,U)}});})(_yt_player);
