(function(g){var window=this;'use strict';var x_=function(I){I.publish("autonavvisibility")},W8x=function(I,U){g.Of(I,"onAutonavCoundownStarted",U)},rI=function(I){return I.isBackground()&&I.Rl()},Ec0=function(I,U){U=U.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
I.N=U?.navigationEndpoint;U=U?.trackingParams;I.playButton&&U&&I.Z.setTrackingParams(I.playButton.element,U)},eC=function(I){const U=GR(I);
var t=Math,W=t.min;var E=I.V?Date.now()-I.V:0;t=W.call(t,E,U);qv(I,Math.ceil((U-t)/1E3));U-t<=500&&I.B()?I.select(!0):I.B()&&I.C.start()},bJ=function(I){var U=I.Z.zL(!0,I.Z.isFullscreen());
g.D(I.container.element,"ytp-autonav-endscreen-small-mode",I.xU(U));g.D(I.container.element,"ytp-autonav-endscreen-is-premium",!!I.suggestion&&!!I.suggestion.xB);g.D(I.Z.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!I.Z.vZ());g.D(I.Z.getRootNode(),"countdown-running",I.B());g.D(I.container.element,"ytp-player-content",I.Z.vZ());g.B9(I.overlay.element,{width:`${U.width}px`});if(!I.B()){I.Z.vZ()?qv(I,Math.round(GR(I)/1E3)):qv(I);U=!!I.suggestion&&!!I.suggestion.Lv;const t=I.Z.vZ()||!U;g.D(I.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!t&&U);g.D(I.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",t&&!U);I.G.gC(I.Z.vZ());g.D(I.element,"ytp-enable-w2w-color-transitions",!!I.Z.getVideoData()?.watchToWatchTransitionRenderer)}},qv=function(I,U=-1){I=I.A.e6("ytp-autonav-endscreen-upnext-header");
g.p1(I);if(U>=0){U=String(U);const t="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],W="Up next in $SECONDS".indexOf(t);if(W>=0){I.appendChild(g.zA("Up next in $SECONDS".slice(0,W)));const E=g.Sy("span");g.np(E,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Qt(E,U);I.appendChild(E);I.appendChild(g.zA("Up next in $SECONDS".slice(W+t.length)));return}}g.Qt(I,"Up next")},GR=function(I){return I.Z.isFullscreen()?(I=I.Z.getVideoData()?.G6,I===-1||I===void 0?8E3:I):I.Z.bA()>=0?I.Z.bA():
g.ri(I.Z.S().experiments,"autoplay_time")||1E4},Bg=function(I,U){U=ZhQ(I,U);
var t=Math,W=t.min;var E=(0,g.q)()-I.V;t=W.call(t,E,U);U=U===0?1:Math.min(t/U,1);I.Js.setAttribute("stroke-dashoffset",`${-211*(U+1)}`);U>=1&&I.B()&&I.api.getPresentingPlayerType()!==3?I.select(!0):I.B()&&I.A.start()},ZhQ=function(I,U){return U?U:I.api.isFullscreen()?(I=I.api.getVideoData()?.G6,I===-1||I===void 0?8E3:I):I.api.bA()>=0?I.api.bA():g.ri(I.api.S().experiments,"autoplay_time")||1E4},TR=function(I){const U=I.vZ();
U!==I.V&&(I.V=U,x_(I.player),I.V?(I.J!==I.B&&I.J.hide(),I.table.hide()):(I.J!==I.B&&I.J.show(),I.table.show()))},RO=function(I){return g.LE(I.player)&&I.A()&&!I.T},Og=function(I){const U=I.vZ();
U!==I.C&&(I.C=U,x_(I.player))},ni=function(I){return g.LE(I.player)&&I.A()&&!I.G},VS=function(I){const U=I.vZ();
U!==I.on&&(I.on=U,x_(I.player))},HhH=function(I){I=I.S();
return I.Y$&&!I.fJ&&!I.disableOrganicUi},wU0=function(I){const U=I.player.getVideoData();
if(!U||I.B===U.fJ&&I.J===U.oF)return!1;I.B=U.fJ;I.J=U.oF;return!0},lff=function(I){I.player.RW("endscreen");
var U=I.player.getVideoData();U=new g.jd(Math.max((U.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const t=new g.jd(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});I.player.d8([U,t])};
g.nX.prototype.bA=g.jA(9,function(){return this.app.bA()});
g.i7.prototype.bA=g.jA(8,function(){return this.getVideoData().ag});
g.O9.prototype.m0=g.jA(7,function(I){this.u5().m0(I)});
g.$N.prototype.m0=g.jA(6,function(I){this.Kk!==I&&(this.Kk=I,this.SJ())});
var dNe=class extends g.V{constructor(I){const U=I.S(),t=U.A;super({X:"a",Y:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:t?U.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{X:"div",fl:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},j:[{X:"div",W:{"aria-label":"{{timestamp}}"},fl:["ytp-autonav-timestamp"],Fe:"{{duration}}"},
{X:"div",fl:["ytp-autonav-live-stamp"],Fe:"Live"},{X:"div",fl:["ytp-autonav-upcoming-stamp"],Fe:"Upcoming"},{X:"div",Y:"ytp-autonav-list-overlay",j:[{X:"div",Y:"ytp-autonav-mix-text",Fe:"Mix"},{X:"div",Y:"ytp-autonav-mix-icon"}]}]},{X:"div",fl:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Fe:"{{title}}"},{X:"div",fl:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Fe:"{{author}}"},{X:"div",fl:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
Fe:"{{views_and_publish_time}}"}]});this.Z=I;this.suggestion=null;this.B=t;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.Z.fb(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.AG||void 0)&&this.Z.logClick(this.element)}onClick(I){g.NI(I,this.Z,this.B,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(I){switch(I.keyCode){case 13:case 32:I.defaultPrevented||(this.select(),I.preventDefault())}}};var Mv=class extends g.V{constructor(I,U=!1){super({X:"div",Y:"ytp-autonav-endscreen-countdown-overlay"});this.yQ=U;this.cancelCommand=this.N=void 0;this.V=0;this.container=new g.V({X:"div",Y:"ytp-autonav-endscreen-countdown-container"});g.J(this,this.container);this.container.As(this.element);U=I.S();const t=U.A;this.Z=I;this.suggestion=null;this.onVideoDataChange("newdata",this.Z.getVideoData());this.L(I,"videodatachange",this.onVideoDataChange);this.A=new g.V({X:"div",Y:"ytp-autonav-endscreen-upnext-container",
W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{X:"div",Y:"ytp-autonav-endscreen-upnext-header"},{X:"div",Y:"ytp-autonav-endscreen-upnext-alternative-header",Fe:"{{autoplayAlternativeHeader}}"},{X:"a",Y:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:t?U.C:""},j:[{X:"div",Y:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},j:[{X:"div",W:{"aria-label":"{{timestamp}}"},
fl:["ytp-autonav-timestamp"],Fe:"{{duration}}"},{X:"div",fl:["ytp-autonav-live-stamp"],Fe:"Live"},{X:"div",fl:["ytp-autonav-upcoming-stamp"],Fe:"Upcoming"}]},{X:"div",Y:"ytp-autonav-endscreen-video-info",j:[{X:"div",Y:"ytp-autonav-endscreen-premium-badge"},{X:"div",Y:"ytp-autonav-endscreen-upnext-title",Fe:"{{title}}"},{X:"div",Y:"ytp-autonav-endscreen-upnext-author",Fe:"{{author}}"},{X:"div",Y:"ytp-autonav-view-and-date",Fe:"{{views_and_publish_time}}"},{X:"div",Y:"ytp-autonav-author-and-view",Fe:"{{author_and_views}}"}]}]}]});
g.J(this,this.A);this.A.As(this.container.element);t||this.L(this.A.e6("ytp-autonav-endscreen-link-container"),"click",this.wk);this.Z.createClientVe(this.container.element,this,115127);this.Z.createClientVe(this.A.e6("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({X:"div",Y:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.As(this.container.element);this.G=new g.V({X:"div",Y:"ytp-autonav-endscreen-button-container"});g.J(this,this.G);this.G.As(this.container.element);
this.cancelButton=new g.V({X:"button",fl:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],W:{"aria-label":"Cancel autoplay"},Fe:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.As(this.G.element);this.cancelButton.listen("click",this.Js,this);this.Z.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.V({X:"a",fl:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},Fe:"Play Now"});g.J(this,this.playButton);this.playButton.As(this.G.element);this.playButton.listen("click",this.wk,this);this.Z.createServerVe(this.playButton.element,this.playButton,!0);(U=this.Z.getVideoData())&&Ec0(this,U);this.C=new g.bP(()=>{eC(this)},500);
g.J(this,this.C);this.on();this.L(I,"autonavvisibility",this.on);this.Z.K("web_autonav_color_transition")&&(this.L(I,"autonavchange",this.l0),this.L(I,"onAutonavCoundownStarted",this.u0))}U(I){this.suggestion!==I&&(this.suggestion=I,g.w7(this.A,I),this.playButton.updateValue("url",this.suggestion.Q3()),bJ(this))}B(){return this.V>0}T(){this.B()||(this.V=Date.now(),eC(this),W8x(this.Z,GR(this)),g.D(this.Z.getRootNode(),"countdown-running",this.B()))}D(){this.J();eC(this);const I=this.A.e6("ytp-autonav-endscreen-upnext-header");
I&&g.Qt(I,"Up next")}J(){this.B()&&(this.C.stop(),this.V=0)}select(I=!1){this.Z.nextVideo(!1,I);this.J()}wk(I){g.NI(I,this.Z)&&(I.currentTarget===this.playButton.element?this.Z.logClick(this.playButton.element):I.currentTarget===this.A.e6("ytp-autonav-endscreen-link-container")&&(I=this.A.e6("ytp-autonav-endscreen-link-container"),this.Z.logVisibility(I,!0),this.Z.logClick(I)),this.N?(g.Of(this.Z,"innertubeCommand",this.N),this.J()):this.select())}Js(){this.Z.logClick(this.cancelButton.element);g.KE(this.Z,
!0);this.cancelCommand&&g.Of(this.Z,"innertubeCommand",this.cancelCommand)}onVideoDataChange(I,U){Ec0(this,U);this.cancelCommand=U.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}u0(I){if(this.Z.getVideoData()?.watchToWatchTransitionRenderer){var U=this.Z.getVideoData().watchToWatchTransitionRenderer;const t=U?.fromColorPaletteDark,W=U?.toColorPaletteDark;t&&W&&(U=this.element,U.style.setProperty("--w2w-start-background-color",
g.RL(t.surgeColor)),U.style.setProperty("--w2w-start-primary-text-color",g.RL(t.primaryTitleColor)),U.style.setProperty("--w2w-start-secondary-text-color",g.RL(t.secondaryTitleColor)),U.style.setProperty("--w2w-end-background-color",g.RL(W.surgeColor)),U.style.setProperty("--w2w-end-primary-text-color",g.RL(W.primaryTitleColor)),U.style.setProperty("--w2w-end-secondary-text-color",g.RL(W.secondaryTitleColor)),U.style.setProperty("--w2w-animation-duration",`${I}ms`));g.D(this.element,"ytp-w2w-animate",
!0)}}l0(I){this.Z.K("web_autonav_color_transition")&&I!==2&&g.D(this.element,"ytp-w2w-animate",!1)}on(){const I=this.Z.vZ();this.yQ&&this.lU!==I&&this.gC(I);bJ(this);this.Z.logVisibility(this.container.element,I);this.Z.logVisibility(this.cancelButton.element,I);this.Z.logVisibility(this.A.e6("ytp-autonav-endscreen-link-container"),I);this.Z.logVisibility(this.playButton.element,I)}xU(I){return I.width<400||I.height<459}};var Pg=class extends g.V{constructor(I,U){super({X:"div",fl:["html5-endscreen","ytp-player-content",U||"base-endscreen"]});this.created=!1;this.player=I}create(){this.created=!0}destroy(){this.created=!1}A(){return!1}vZ(){return!1}N(){return!1}};var I6=class extends g.V{constructor(I){super({X:"div",fl:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},j:[{X:"div",Y:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{X:"span",Y:"ytp-upnext-top",j:[{X:"span",Y:"ytp-upnext-header",Fe:"Up Next"},{X:"span",Y:"ytp-upnext-title",Fe:"{{title}}"},{X:"span",Y:"ytp-upnext-author",Fe:"{{author}}"}]},{X:"a",Y:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},j:[{X:"svg",W:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},j:[{X:"circle",Y:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{X:"circle",Y:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{X:"path",Y:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{X:"span",Y:"ytp-upnext-bottom",j:[{X:"span",Y:"ytp-upnext-cancel"},
{X:"span",Y:"ytp-upnext-paused",Fe:"Autoplay is paused"}]}]});this.api=I;this.cancelButton=null;this.Js=this.e6("ytp-svg-autoplay-ring");this.C=this.notification=this.A=this.suggestion=null;this.N=new g.bP(this.G,5E3,this);this.V=0;var U=this.e6("ytp-upnext-cancel");this.cancelButton=new g.V({X:"button",fl:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},Fe:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.listen("click",this.wk,this);this.cancelButton.As(U);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.J(this,this.N);this.api.createClientVe(this.element,this,18788);U=this.e6("ytp-upnext-autoplay-icon");this.L(U,"click",this.l0);this.api.createClientVe(U,this,115130);this.on();this.L(I,"autonavvisibility",this.on);this.L(I,"mdxnowautoplaying",this.u0);this.L(I,"mdxautoplaycanceled",this.yQ);g.D(this.element,"ytp-upnext-mobile",this.api.S().J)}G(){this.notification&&(this.N.stop(),this.Z5(this.C),this.C=null,this.notification.close(),
this.notification=null)}U(I){this.suggestion=I;g.w7(this,I,"hqdefault.jpg")}on(){this.gC(this.api.vZ());this.api.logVisibility(this.element,this.api.vZ());this.api.logVisibility(this.e6("ytp-upnext-autoplay-icon"),this.api.vZ());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.vZ())}QQ(){window.focus();this.G()}T(I){this.B()||(g.Hw("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.V=(0,g.q)(),this.A=new g.bP(()=>{Bg(this,I)},25),Bg(this,I),W8x(this.api,ZhQ(this,
I)));
g.Ih(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}B(){return!!this.A}D(){this.J();this.V=(0,g.q)();Bg(this);g.MV(this.element,"ytp-upnext-autoplay-paused")}J(){this.B()&&(this.A.dispose(),this.A=null)}select(I=!1){if(this.api.S().K("autonav_notifications")&&I&&window.Notification&&typeof document.hasFocus==="function"){const U=Notification.permission;U==="default"?Notification.requestPermission():U!=="granted"||document.hasFocus()||(this.G(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.rQ()}),this.C=this.L(this.notification,"click",this.QQ),this.N.start())}this.J();this.api.nextVideo(!1,I)}l0(I){!g.FP(this.cancelButton.element,I.target)&&g.NI(I,this.api)&&(this.api.vZ()&&this.api.logClick(this.e6("ytp-upnext-autoplay-icon")),this.select())}wk(){this.api.vZ()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.KE(this.api,!0)}u0(I){this.api.getPresentingPlayerType();this.show();this.T(I)}yQ(){this.api.getPresentingPlayerType();
this.J();this.hide()}b0(){this.J();this.G();super.b0()}};var vcw=class extends Pg{constructor(I){super(I,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.V({X:"div",Y:"ytp-suggestion-panel",j:[{X:"div",fl:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Fe:"More videos"}]});this.C=new g.V({X:"div",Y:"ytp-suggestions-container"});this.videos=[];this.D=null;this.V=this.U=!1;this.J=new Mv(this.player);g.J(this,this.J);this.J.As(this.element);I.getVideoData().oF?this.B=this.J:(this.B=new I6(I),g.zp(this.player,
this.B.element,4),g.J(this,this.B));this.overlay=new g.V({X:"div",Y:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.As(this.element);this.T=new g.E9(this);g.J(this,this.T);g.J(this,this.table);this.table.As(this.element);this.table.show();g.J(this,this.C);this.C.As(this.table.element);this.hide()}create(){super.create();this.T.L(this.player,"appresize",this.G);this.T.L(this.player,"onVideoAreaChange",this.G);this.T.L(this.player,"videodatachange",this.onVideoDataChange);
this.T.L(this.player,"autonavchange",this.on);this.T.L(this.player,"onAutonavCancelled",this.wk);this.onVideoDataChange()}show(){super.show();(this.U||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.KE(this.player,!1);g.LE(this.player)&&this.A()&&!this.D?(TR(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||rI(this.player.CX())&&this.player.K("web_player_pip_logging_fix")?this.B.select(!0):this.B.T():this.videoData.autonavState===3&&this.B.D()):(g.KE(this.player,
!0),TR(this));this.G()}hide(){super.hide();this.B.D();TR(this)}G(){var I=this.player.zL(!0,this.player.isFullscreen());TR(this);bJ(this.J);g.D(this.element,"ytp-autonav-cancelled-small-mode",this.xU(I));g.D(this.element,"ytp-autonav-cancelled-tiny-mode",this.UK(I));g.D(this.element,"ytp-autonav-cancelled-mini-mode",I.width<=400||I.height<=360);this.overlay&&g.B9(this.overlay.element,{width:`${I.width}px`});if(!this.V)for(I=0;I<this.videos.length;I++)g.D(this.videos[I].element,"ytp-suggestion-card-with-margin",
I%2===1)}onVideoDataChange(){var I=this.player.getVideoData();if(this.videoData!==I&&I){this.videoData=I;I=this.videoData.suggestions;var U=this.videoData.mu();U&&(this.B.U(U),this.B!==this.J&&this.J.U(U));if(I&&I.length)for(let W=0;W<K8H.length;++W){var t=K8H[W];I&&I[t]&&(this.videos[W]=new dNe(this.player),U=this.videos[W],t=I[t],U.suggestion!==t&&(U.suggestion=t,g.w7(U,t)),g.J(this,this.videos[W]),this.videos[W].As(this.C.element))}this.G()}}on(I){I===1?(this.U=!1,this.D=this.videoData.clientPlaybackNonce,
this.B.J(),this.lU&&this.G()):(this.U=!0,this.vZ()&&(I===2?this.B.T():I===3&&this.B.D()))}wk(I){if(I)this.on(1);else this.D=null,this.U=!1}A(){return this.videoData.autonavState!==1}xU(I){return(I.width<910||I.height<459)&&!this.UK(I)&&!(I.width<=400||I.height<=360)}UK(I){return I.width<800&&!(I.width<=400||I.height<=360)}vZ(){return this.lU&&g.LE(this.player)&&this.A()&&!this.D}},K8H=[1,3,2,4];var cB8=class extends Pg{constructor(I){super(I,"videowall-endscreen");this.Z=I;this.stills=[];this.T=this.videoData=null;this.G=this.C=!1;this.on=null;g.MV(this.element,"modern-videowall-endscreen");this.J=new g.E9(this);g.J(this,this.J);this.V=new g.bP(()=>{g.MV(this.element,"ytp-show-tiles")},0);
g.J(this,this.V);this.table=new g.gl({X:"div",Y:"ytp-modern-endscreen-content"});g.J(this,this.table);this.table.As(this.element);I.getVideoData().oF?this.B=new Mv(I,!0):this.B=new I6(I);g.J(this,this.B);g.zp(this.player,this.B.element,4);I.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var I=this.player.getVideoData();I&&(this.videoData=I);this.D();this.J.L(this.player,"appresize",this.D);this.J.L(this.player,"onVideoAreaChange",this.D);this.J.L(this.player,"videodatachange",
this.onVideoDataChange);this.J.L(this.player,"autonavchange",this.U);this.J.L(this.player,"onAutonavCancelled",this.wk);I=this.videoData.autonavState;I!==this.on&&this.U(I);this.J.L(this.element,"transitionend",this.l0)}destroy(){this.J.J();g.E3(this.stills);this.stills=[];super.destroy();g.Ih(this.element,"ytp-show-tiles");this.V.stop();this.on=this.videoData.autonavState}A(){return this.videoData.autonavState!==1}show(){const I=this.lU;super.show();g.Ih(this.element,"ytp-show-tiles");this.player.S().J?
g.BD(this.V):this.V.start();(this.G||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.KE(this.player,!1);RO(this)?(Og(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||rI(this.player.CX())&&this.player.K("web_player_pip_logging_fix")?this.B.select(!0):this.B.T():this.videoData.autonavState===3&&this.B.D()):(g.KE(this.player,!0),Og(this));I!==this.lU&&this.player.logVisibility(this.element,!0)}hide(){const I=this.lU;super.hide();this.B.D();Og(this);I!==this.lU&&this.player.logVisibility(this.element,
!1)}l0(I){I.target===this.element&&this.D()}D(){const I=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.mu()];if(I.length){var U=this.Z.zL(!0,this.Z.isFullscreen()),t=Math.floor((U.width-64+16)/(g.DC(U.width*.27,250,450)+16));U=Math.min(3,Math.floor((U.height-64)/((U.width-64-(t-1)*16)/t*.5625+70)));g.Ub(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.MV(this.element,`ytp-modern-endscreen-limit-rows-${U}`);
g.D(this.element,"ytp-modern-endscreen-single-item",t===1);g.D(this.element,"ytp-modern-endscreen-row-0",U===0);t=this.table.element;t.ariaLive="polite";this.B.U(this.videoData.mu());this.B instanceof Mv&&bJ(this.B);g.D(this.element,"ytp-endscreen-takeover",RO(this));Og(this);U=0;t.ariaBusy="true";var W=I.length;for(let E=0;E<W;E++){const Z=E%W;let H=this.stills[E];H||(H=new g.j1W(this.player),this.stills[E]=H,t.appendChild(H.element));g.up5(H,I[Z]);U++}this.stills.length=U}}onVideoDataChange(){const I=
this.player.getVideoData({playerType:1});this.videoData!==I&&(I?.mu()?(this.videoData=I,this.D()):this.player.EJ("missg",{vid:I?.videoId||"",cpn:I?.clientPlaybackNonce||""}))}N(){return this.B.B()}U(I){I===1?(this.G=!1,this.T=this.videoData.clientPlaybackNonce,this.B.J(),this.lU&&this.D()):(this.G=!0,this.lU&&RO(this)&&(I===2?this.B.T():I===3&&this.B.D()))}wk(I){if(I){for(I=0;I<this.stills.length;I++)this.Z.logVisibility(this.stills[I].element,!0);this.U(1)}else this.T=null,this.G=!1;this.D()}vZ(){return this.lU&&
RO(this)}};var $NL=class extends Pg{constructor(I){super(I,"subscribecard-endscreen");this.B=new g.V({X:"div",Y:"ytp-subscribe-card",j:[{X:"img",Y:"ytp-author-image",W:{src:"{{profilePicture}}"}},{X:"div",Y:"ytp-subscribe-card-right",j:[{X:"div",Y:"ytp-author-name",Fe:"{{author}}"},{X:"div",Y:"html5-subscribe-button-container"}]}]});g.J(this,this.B);this.B.As(this.element);const U=I.getVideoData();this.subscribeButton=new g.IF("Subscribe",null,"Unsubscribe",null,!0,!1,U.nB,U.subscribed,"trailer-endscreen",null,
I,!1);g.J(this,this.subscribeButton);this.subscribeButton.As(this.B.e6("html5-subscribe-button-container"));this.L(I,"videodatachange",this.YA);this.YA();this.hide()}YA(){const I=this.player.getVideoData();this.B.update({profilePicture:I.profilePicture,author:I.author});this.subscribeButton.channelId=I.nB;var U=this.subscribeButton;I.subscribed?U.B():U.J()}};var u2t=class extends g.V{constructor(I){const U=I.S(),t=g.BO||g.ZR?{style:"will-change: opacity"}:void 0,W=U.A,E=["ytp-videowall-still"];U.J&&E.push("ytp-videowall-show-text");super({X:"a",fl:E,W:{href:"{{url}}",target:W?U.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},j:[{X:"div",Y:"ytp-videowall-still-image",W:{style:"{{background}}"}},{X:"span",Y:"ytp-videowall-still-info",W:{"aria-hidden":"true"},j:[{X:"span",Y:"ytp-videowall-still-info-bg",
j:[{X:"span",Y:"ytp-videowall-still-info-content",W:t,j:[{X:"span",Y:"ytp-videowall-still-info-title",Fe:"{{title}}"},{X:"span",Y:"ytp-videowall-still-info-author",Fe:"{{author_and_views}}"},{X:"span",Y:"ytp-videowall-still-info-live",Fe:"Live"},{X:"span",Y:"ytp-videowall-still-info-duration",Fe:"{{duration}}"}]}]}]},{X:"span",fl:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},j:[{X:"span",Y:"ytp-videowall-still-listlabel-icon"},"Playlist",{X:"span",
Y:"ytp-videowall-still-listlabel-length",j:[" (",{X:"span",Fe:"{{playlist_length}}"},")"]}]},{X:"span",fl:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},j:[{X:"span",Y:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{X:"span",Y:"ytp-videowall-still-listlabel-length",Fe:" (50+)"}]}]});this.suggestion=null;this.J=W;this.api=I;this.B=new g.E9(this);g.J(this,this.B);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.B.L(I,"videodatachange",
this.onVideoDataChange);I.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.fb(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.AG||void 0)&&this.api.logClick(this.element)}onClick(I){if(g.r8(this.api.S())&&this.api.K("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let U=this.suggestion.Q3();const t={};g.u$(this.api,t);U=g.pw(U,t);g.JY(U,this.api,I)}else g.NI(I,this.api,
this.J,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(I){switch(I.keyCode){case 13:case 32:I.defaultPrevented||(this.select(),I.preventDefault())}}onVideoDataChange(){const I=this.api.getVideoData(),U=this.api.S();this.J=I.z_?!1:U.A}};var hQY=class extends Pg{constructor(I){super(I,"videowall-endscreen");this.Z=I;this.T=0;this.stills=[];this.G=this.videoData=null;this.V=this.on=!1;this.wk=null;this.D=new g.E9(this);g.J(this,this.D);this.U=new g.bP(()=>{g.MV(this.element,"ytp-show-tiles")},0);
g.J(this,this.U);var U=new g.V({X:"button",fl:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},j:[g.$Z()]});g.J(this,U);U.As(this.element);U.listen("click",this.u0,this);this.table=new g.gl({X:"div",Y:"ytp-endscreen-content"});g.J(this,this.table);this.table.As(this.element);U=new g.V({X:"button",fl:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},j:[g.up()]});g.J(this,U);U.As(this.element);U.listen("click",this.Js,this);I.getVideoData().oF?this.B=new Mv(I,!0):this.B=
new I6(I);g.J(this,this.B);g.zp(this.player,this.B.element,4);I.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var I=this.player.getVideoData();I&&(this.videoData=I);this.J();this.D.L(this.player,"appresize",this.J);this.D.L(this.player,"onVideoAreaChange",this.J);this.D.L(this.player,"videodatachange",this.onVideoDataChange);this.D.L(this.player,"autonavchange",this.C);this.D.L(this.player,"onAutonavCancelled",this.l0);I=this.videoData.autonavState;I!==this.wk&&this.C(I);
this.D.L(this.element,"transitionend",this.yQ)}destroy(){this.D.J();g.E3(this.stills);this.stills=[];super.destroy();g.Ih(this.element,"ytp-show-tiles");this.U.stop();this.wk=this.videoData.autonavState}A(){return this.videoData.autonavState!==1}show(){const I=this.lU;super.show();g.Ih(this.element,"ytp-show-tiles");this.player.S().J?g.BD(this.U):this.U.start();(this.V||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.KE(this.player,!1);ni(this)?(VS(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||rI(this.player.CX())&&this.player.K("web_player_pip_logging_fix")?this.B.select(!0):this.B.T():this.videoData.autonavState===3&&this.B.D()):(g.KE(this.player,!0),VS(this));I!==this.lU&&this.player.logVisibility(this.element,!0)}hide(){const I=this.lU;super.hide();this.B.D();VS(this);I!==this.lU&&this.player.logVisibility(this.element,!1)}yQ(I){I.target===this.element&&this.J()}J(){var I=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.mu()];if(I.length){g.MV(this.element,
"ytp-endscreen-paginate");var U=this.Z.zL(!0,this.Z.isFullscreen()),t=g.W7(this.Z);t&&(t=t.Bk()?48:32,U.width-=t*2);var W=U.width/U.height,E=96/54,Z=t=2,H=Math.max(U.width/96,2),w=Math.max(U.height/54,2),l=I.length;var d=l*4;for(d-=4;d>0&&(t<H||Z<w);){var K=t/2,v=Z/2,c=t<=H-2&&d>=v*4,u=Z<=w-2&&d>=K*4;if((K+1)/v*E/W>W/(K/(v+1)*E)&&u)d-=K*4,Z+=2;else if(c)d-=v*4,t+=2;else if(u)d-=K*4,Z+=2;else break}E=!1;d>=12&&l*4-d<=6&&(Z>=4||t>=4)&&(E=!0);d=t*96;H=Z*54;W=d/H<W?U.height/H:U.width/d;W=Math.min(W,2);
d=Math.floor(Math.min(U.width,d*W));H=Math.floor(Math.min(U.height,H*W));U=this.table.element;U.ariaLive="polite";g.wj(U,d,H);g.B9(U,{marginLeft:`${d/-2}px`,marginTop:`${H/-2}px`});this.B.U(this.videoData.mu());this.B instanceof Mv&&bJ(this.B);g.D(this.element,"ytp-endscreen-takeover",ni(this));VS(this);d+=4;H+=4;W=0;U.ariaBusy="true";for(w=0;w<t;w++)for(K=0;K<Z;K++)if(c=W,u=0,E&&w>=t-2&&K>=Z-2?u=1:K%2===0&&w%2===0&&(K<2&&w<2?K===0&&w===0&&(u=2):u=2),c=g.xE(c+this.T,l),u!==0){v=this.stills[W];v||
(v=new u2t(this.player),this.stills[W]=v,U.appendChild(v.element));var z=Math.floor(H*K/Z);const y=Math.floor(d*w/t),a=Math.floor(H*(K+u)/Z)-z-4,Y=Math.floor(d*(w+u)/t)-y-4;g.P9(v.element,y,z);g.wj(v.element,Y,a);g.B9(v.element,"transitionDelay",(K+w)/20+"s");g.D(v.element,"ytp-videowall-still-mini",u===1);g.D(v.element,"ytp-videowall-still-large",u>2);u=Math.max(Y,a);g.D(v.element,"ytp-videowall-still-round-large",u>=256);g.D(v.element,"ytp-videowall-still-round-medium",u>96&&u<256);g.D(v.element,
"ytp-videowall-still-round-small",u<=96);c=I[c];v.suggestion!==c&&(v.suggestion=c,u=v.api.S(),z=g.VM(v.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.w7(v,c,z),g.r8(u)&&!v.api.K("web_player_log_click_before_generating_ve_conversion_params")&&(u=c.Q3(),z={},g.M9(v.api,"addEmbedsConversionTrackingParams",[z]),u=g.pw(u,z),v.updateValue("url",u)),(c=(c=c.sessionData)&&c.itct)&&v.api.setTrackingParams(v.element,c));W++}U.ariaBusy="false";g.D(this.element,"ytp-endscreen-paginate",
W<l);for(I=this.stills.length-1;I>=W;I--)t=this.stills[I],g.C1(t.element),g.WW(t);this.stills.length=W}}onVideoDataChange(){const I=this.player.getVideoData({playerType:1});this.videoData!==I&&(I?.mu()?(this.T=0,this.videoData=I,this.J()):this.player.EJ("missg",{vid:I?.videoId||"",cpn:I?.clientPlaybackNonce||""}))}Js(){this.T+=this.stills.length;this.J()}u0(){this.T-=this.stills.length;this.J()}N(){return this.B.B()}C(I){I===1?(this.V=!1,this.G=this.videoData.clientPlaybackNonce,this.B.J(),this.lU&&
this.J()):(this.V=!0,this.lU&&ni(this)&&(I===2?this.B.T():I===3&&this.B.D()))}l0(I){if(I){for(I=0;I<this.stills.length;I++)this.Z.logVisibility(this.stills[I].element,!0);this.C(1)}else this.G=null,this.V=!1;this.J()}vZ(){return this.lU&&ni(this)}};var SGV=class extends g.V{constructor(I){super({X:"button",fl:["ytp-watch-on-youtube-button","ytp-button"],Fe:"{{content}}"});this.Z=I;this.buttonType=this.buttonType=1;this.B();this.buttonType===2&&g.MV(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.B);this.gC(!0)}B(){let I,U;switch(this.buttonType){case 1:I="Watch again on YouTube";U=156915;break;case 2:I="Continue watching on YouTube";U=156942;break;default:I="Continue watching on YouTube",
U=156942}this.update({content:I});this.Z.hasVe(this.element)&&this.Z.destroyVe(this.element);this.Z.createClientVe(this.element,this,U)}onClick(I){this.Z.K("web_player_log_click_before_generating_ve_conversion_params")&&this.Z.logClick(this.element);g.JY(this.getVideoUrl(),this.Z,I);this.Z.K("web_player_log_click_before_generating_ve_conversion_params")||this.Z.logClick(this.element)}getVideoUrl(){var I=!0;switch(this.buttonType){case 1:I=!0;break;case 2:I=!1}I=this.Z.getVideoUrl(I,!1,!1,!0);const U=
this.Z.S();if(g.r8(U)){const t={};g.r8(U)&&g.M9(this.Z,"addEmbedsConversionTrackingParams",[t]);I=g.pw(I,t)}return I}logVisibility(){this.Z.logVisibility(this.element,this.lU&&this.mu)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}E5(I){super.E5(I);this.logVisibility()}};var zQw=class extends Pg{constructor(I){super(I,"watch-again-on-youtube-endscreen");this.watchButton=new SGV(I);g.J(this,this.watchButton);this.watchButton.As(this.element);g.lbI(I)&&(this.B=new g.KwH(I),g.J(this,this.B),this.J=new g.V({X:"div",fl:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},j:[this.B]}),g.J(this,this.J),this.B.As(this.J.element),this.J.As(this.element));I.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.B?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const U=this.J;if(U){var I=this.B.hasSuggestions();g.D(this.element,"ytp-shorts-branded-ui",I);I?U.show():U.hide()}g.W7(this.player)?.m0(!0);this.player.logVisibility(this.element,!0);this.watchButton.E5(!0)}}hide(){super.hide();g.W7(this.player)?.m0(!1);this.player.logVisibility(this.element,!1);this.watchButton.E5(!1)}};g.g7("endscreen",class extends g.p0{constructor(I){super(I);this.endScreen=null;this.B=this.J=this.D=!1;this.listeners=new g.E9(this);g.J(this,this.listeners);const U=I.S();I.isEmbedsShortsMode()?this.endScreen=new zQw(I):HhH(I)?(this.D=!0,wU0(this),this.B?this.endScreen=new vcw(I):U.K("delhi_modern_endscreen")?this.endScreen=new cB8(I):this.endScreen=new hQY(I)):U.fJ?this.endScreen=new $NL(I):this.endScreen=new Pg(I);g.J(this,this.endScreen);g.zp(I,this.endScreen.element,4);lff(this);this.listeners.L(I,
"videodatachange",this.onVideoDataChange,this);this.listeners.L(I,g.EZ("endscreen"),t=>{this.onCueRangeEnter(t)});
this.listeners.L(I,g.Zl("endscreen"),t=>{this.onCueRangeExit(t)})}tN(){var I=this.player.getVideoData();
const U=I.mutedAutoplay&&(I.limitedPlaybackDurationInSeconds>0||I.endSeconds>0||I.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!U)return!0;var t=!(!I?.mu()&&!I?.suggestions?.length);t=!HhH(this.player)||t;I=I.uG;const W=this.player.w4();return t&&!I&&!W&&!U}vZ(){return this.endScreen.vZ()}Ik(){return this.vZ()?this.endScreen.N():!1}b0(){this.player.RW("endscreen");super.b0()}load(){{const t=this.player.getVideoData(),W=t.transitionEndpointAtEndOfStream;if(W&&W.videoId){var I=
this.player.Dw().JU.get("heartbeat");var U=t.mu();!U||W.videoId!==U.videoId||t.Iy?(this.player.fb(W.videoId,void 0,void 0,!0,!0,W),I&&I.Na("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),I=!0):I=!1}else I=!1}I||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(I){this.tN()&&(this.endScreen.created||this.endScreen.create(),I.getId()==="load"&&this.load())}onCueRangeExit(I){I.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){lff(this);this.D&&wU0(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.B?this.endScreen=new vcw(this.player):this.endScreen=new hQY(this.player),g.J(this,this.endScreen),g.zp(this.player,this.endScreen.element,4))}});})(_yt_player);
