(function(g){var window=this;'use strict';var UA=function(I,U){if(!Number.isFinite(I))return String(I);I=String(I);let t=I.indexOf(".");t===-1&&(t=I.length);const W=I[0]==="-"?"-":"";W&&(I=I.substring(1));U="0".repeat(Math.max(0,U-t));return W+U+I},WB=function(I){typeof I==="number"?(this.date=L8f(I,0,1),tF(this,1)):g.R3(I)?(this.date=L8f(I.getFullYear(),I.getMonth(),I.getDate()),tF(this,I.getDate())):(this.date=new Date(g.UH()),I=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
tF(this,I))},L8f=function(I,U,t){U=new Date(I,U,t);
I>=0&&I<100&&U.setFullYear(U.getFullYear()-1900);return U},tF=function(I,U){I.getDate()!=U&&I.date.setUTCHours(I.date.getUTCHours()+(I.getDate()<U?1:-1))},EA=function(I){if(I.toggleButtonRenderer){var U=I.toggleButtonRenderer;
if(U.isToggled){var t=U.toggledText?g.Kf(U.toggledText):"";I.update({text:t,icon:pUL(U.toggledIcon)})}else t=U.defaultText?g.Kf(U.defaultText):"",I.update({text:t,icon:pUL(U.defaultIcon)});I.show()}else I.hide()},mNx=function(I,U){!I.toggleButtonRenderer&&U&&U.toggleButtonRenderer?I.toggleButtonRenderer=U.toggleButtonRenderer:U&&U.toggleButtonRenderer||(I.toggleButtonRenderer=null);
EA(I)},pUL=function(I){if(!I)return null;
switch(I.iconType){case "NOTIFICATIONS":return{X:"svg",W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{X:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{X:"svg",W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{X:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return g.M7m();default:return null}},F8k=function(I,U){const t=g.Q(U,gcQ),W=g.Q(U,COL);
if(U&&(t||W)){if(t){var E=t;var Z="notification/add_upcoming_event_reminder"}else W&&(E=W,Z="notification/remove_upcoming_event_reminder");Z&&E&&E.params&&yBL(I,Z,E.params)}},yBL=function(I,U,t){I.B||(I.B=new g.uh(I.Z.S().Eq));
const W={context:g.p6(I.B.config_||g.L6())};g.gW()&&(W.context.clientScreenNonce=g.gW());W.params=t;g.PL(I.B,U,W,{timeout:5E3,onError:()=>{QAk(I)},
onTimeout:()=>{QAk(I)}})},QAk=function(I){I.toggleButtonRenderer&&(I.toggleButtonRenderer.isToggled=!I.toggleButtonRenderer.isToggled,EA(I))},ZT=function(I,U,t){if(U){var W=U.subtitleText!=null?g.Kf(U.subtitleText):"";
t=t?t:U.mainText!=null?g.Kf(U.mainText):"";I.update({mainText:t,subtitleText:W,label:U.mainText?.accessibility?.accessibilityData?.label??t});g.D(I.element,"ytp-offline-slate-single-text-line",!W);g.D(I.D,"ytp-offline-slate-bar-hidden",!t&&!W)}},ffk=function(I){try{const U=JSON.parse(I);
return U!=null?U:void 0}catch(U){}},NjQ=async function(I){const U=I.player.S(),t=I.getVideoData();
HB(I)&&(jAw(I)?AB6(I,U,t):(sAV(I),await afQ(I,U,t)))},sAV=function(I){var U=I.getVideoData();
if(U.IJ)if(U.K("use_rta_for_player"))I.attestationResponse=JBQ(I);else{const Z=new g.ZcA(U);if(g.X5.isInitialized()||I.sequenceNumber>=3){U=Promise;var t=U.resolve;let H=null;if(Z.videoData.EO){var W=g.H2A(Z);if(W){H={};const w={};W=W.split("&");for(E of W)W=E.split("="),W.length===2&&(w[W[0]]=W[1]);var E=w;E.r1a&&(H.webResponse=E.r1a);E.r1c&&(H.error=ock[Number(E.r1c)]);H.challenge=Z.videoData.EO}}I.attestationResponse=t.call(U,H||void 0)}}},YGf=function(I){var U=I.getVideoData();
const t=I.player.S();if(U.isLivePlayback)if(g.at(t.T)){I.A=!0;I.V=!0;if(!g.Be(t)||g.ef(t))I.offlineSlate=new XUw(I.player),g.J(I,I.offlineSlate),g.zp(I.player,I.offlineSlate.element,4);(U=U.getPlayerResponse())&&U.playabilityStatus&&(I.B=U.playabilityStatus);I.B?.status!=="UNPLAYABLE"&&(I.B?(U=ihw(void 0,I.B.liveStreamability&&I.B.liveStreamability.liveStreamabilityRenderer))?wk(I,U):wk(I,7500):wk(I,lB(I,!0)))}else I.player.g8("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Fe(U.hd,"heartbeat")&&I.player.Fu("heartbeat",I.getPlayerType())},DNV=function(I,U,t){var W=t.liveStreamability&&t.liveStreamability.liveStreamabilityRenderer,E=!(!W||!(W.switchStreamsImmediately||W.transitionTiming&&W.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
U=ihw(U,W);var Z=I.getVideoData();const H=I.player.getPlayerStateObject(I.getPlayerType()),w=H.isPlaying()&&!g.aT(Z)&&!I.player.isAtLiveHead(I.getPlayerType());if(Z.S().Vi()){var l=I.player.iK()?.Or()||{};l.status=t.status||"";l.dvr=`${+w}`;l["switch"]=`${+E}`;l.ended=`${+!(!W||!W.displayEndscreen)}`;I.player.EJ("heartbeat",l)}l=W&&W.broadcastId;const d=I.B&&I.B.liveStreamability&&I.B.liveStreamability.liveStreamabilityRenderer&&I.B.liveStreamability.liveStreamabilityRenderer.broadcastId,K=l!==d&&
l!=null;K&&I.player.EJ("lbidh",{broadcastId:l},!0);var v=Z.S();if(v.Wo().B.OJ(g.JaW)&&g.Be(v)&&W&&W.streamTransitionEndpoint){v=g.Q(W.streamTransitionEndpoint,g.qf)?.commands||[];for(var c of v)if(g.Q(c,g.QJ)?.signal==="RELOAD_PLAYER"){I.player.g8("qoe.restart",1,void 0,"sa.reload","7");break}}c=I.player.K("always_cache_redirect_endpoint");if(w&&!E&&!c)return U;v=W&&W.streamTransitionEndpoint&&g.Q(W.streamTransitionEndpoint,g.VJ);const u=W&&W.transitionTiming;if(u==="STREAM_TRANSITION_TIMING_AT_STREAM_END")I.getVideoData().transitionEndpointAtEndOfStream=
v;else if(c&&!v&&I.getVideoData().transitionEndpointAtEndOfStream)I.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!c&&v&&dk(I,v,t))return U;if(w&&!E&&c||c&&v&&(u==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||u==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&dk(I,v,t))return U;if(t.status.toUpperCase()==="OK"){if(!g.RP(Z)||K)return W={video_id:Z.videoId},Z.T6&&(W.is_live_destination="1"),W.disable_watch_next=!0,W.raw_watch_next_response=Z.getWatchNextResponse(),W.autonav_state=Z.autonavState,
W.oauth_token=Z.oauthToken,W.EA=Z.EA,Z.G&&(W.vss_credentials_token=Z.G,W.vss_credentials_token_type=Z.A1),Z.wk&&(W.vvt=Z.wk),E=void 0,g.RP(Z)?K&&(E=new kQH("broadcastIdChanged",`${d},${l}`),I.Na("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",t)):(l&&(E=new kQH("formatsReceived",`${l}`)),I.Na("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",t)),K&&I.player.EJ("lbidr",{broadcastId:l}),I.player.loadVideoByPlayerVars(W,
void 0,void 0,void 0,E),U;I.player.Fu("heartbeat",I.getPlayerType())}W&&W.displayEndscreen&&(I.offlineSlate?(I=I.offlineSlate,I.G=!0,I.lU&&I.api.EE()):H.isBuffering()&&(Z=I.player.iK()?.Or()||{},I.player.EJ("hbse",Z,!0),I.player.EE(!0,"h"),g.Of(I.player,"onLiveMediaEnded",t)));return U},lB=function(I,U=!1){I=I.getVideoData();
return I.K("html5_use_server_init_heartbeat_delay")?isNaN(I.RS)?15E3:I.RS:U?1E3:2E3},xNQ=function(I){var U=I.getVideoData();
!U.K("use_rta_for_player")&&U.IJ&&(U=U.botguardData)&&g.kj(U,I.player.S())},Kv=function(I){I.U=0;
I.J.stop();I.T=!1;I.sequenceNumber=0},JBQ=async function(I){if(await g.riz())return I=I.getVideoData(),g.xAW({cpn:I.clientPlaybackNonce,
encryptedVideoId:I.videoId||""},1500);if(I.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},wk=function(I,U){if(!I.J.isActive()&&I.V){var t=I.getVideoData();
if(vB(I)||t.isLivePlayback)U===void 0&&(U=I.T?I.A?7500:I.heartbeatParams?.interval?I.heartbeatParams.interval*1E3:I.getVideoData().RS||6E4:1E3),I.J.start(U)}},jAw=function(I){var U=I.getVideoData();
if(!g.Qn(I.getVideoData())||U.SL)return!1;if(U.T){I=U.T.flavor==="playready";const t=U.T.flavor==="widevine"&&U.K("html5_innertube_heartbeats_for_widevine");U=g.zB(U.T)&&U.K("html5_innertube_heartbeats_for_fairplay");return!(I||t||U)}return!0},vB=function(I){if(jAw(I))return!!I.heartbeatParams;
const U=I.getVideoData();return!g.Qn(I.getVideoData())||U.tF||U.Sk?!!U.heartbeatToken:!1},qGk=function(I,U,t){U.Q0&&(t=g.pw(t,{internalipoverride:U.Q0}));
const W={cpn:U.clientPlaybackNonce};U.contextParams&&(W.context_params=U.contextParams);U.PK&&(W.kpt=U.PK);t=g.pw(t,W);g.x9(t,{format:"RAW",method:"GET",timeout:3E4,onSuccess:E=>{if(!I.J.isActive()&&HB(I)){I.G.reset();I.sequenceNumber++;E=E.responseText;var Z=ffk(E);if(Z){g.Of(I.player,"onHeartbeat",Z);var H=Z.status==="ok"?Z.stop_heartbeat?2:0:Z.status==="stop"?1:Z.status==="live_stream_offline"?0:-1}else H=(H=E.match(rBx))?H[1]==="0"?0:1:-1;GQ6(I,void 0,Z,E,H)}},
onError:E=>{HB(I)&&cB(I,!0,`net-${E.status}`)},
onTimeout:()=>{HB(I)&&cB(I,!0,"timeout")},
withCredentials:!0})},HB=function(I){const U=I.getVideoData();
return I.player.getPresentingPlayerType()===3||!I.player.S().experiments.Wo().B.OJ(g.Bdm)&&I.player.getPlayerStateObject(I.getPlayerType()).B(4)?!1:vB(I)||U.isLivePlayback?!0:(Kv(I),!1)},AB6=function(I,U,t){if(I.heartbeatParams?.url){var W=g.pw(I.heartbeatParams.url,{request_id:g.Yn_()});
t.wk&&(W=g.pw(W,{vvt:t.wk}),t.mdxEnvironment&&(W=g.pw(W,{mdx_environment:t.mdxEnvironment})));g.vI(U,t.oauthToken).then(E=>{E&&(W=g.pw(W,{access_token:E}));qGk(I,t,W)})}},afQ=async function(I,U,t){const W={videoId:t.videoId,
sequenceNumber:I.sequenceNumber,heartbeatServerData:I.wk??t.heartbeatServerData};I.C=I.attestationResponse;t.IJ&&(W.attestationResponse=await I.C);var E=g.RT(t),Z=E.client??{};Z.utcOffsetMinutes=I.utcOffsetMinutes;W.context=E;W.cpn=t.clientPlaybackNonce;if(E=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)Z.timeZone=E;Z={heartbeatChecks:[]};if(E=t.getPlayerResponse())t.heartbeatToken&&(W.heartbeatToken=t.heartbeatToken),(E=E.playabilityStatus)&&(E=E.liveStreamability)&&
E.liveStreamabilityRenderer&&Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");t.heartbeatToken&&Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.ef(U)){Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var H=eQL(I);E={};H!==null&&(E.clientPlayerPositionUtcMillis=H);H=I.player.Dw()?.kF()?.JP()||0;H>0&&(E.freePreviewWatchedDuration={seconds:`${H}`});Z.unpluggedParams=E}W.heartbeatRequestParams=Z;t.isLivePlayback?(Z=eQL(I),Z!==null&&(W.playbackState||(W.playbackState={}),
W.playbackState.playbackPosition={utcTimeMillis:Z})):U.K("enable_heartbeat_vod_playback_position")&&(Z=bhV(I),Z!==null&&(W.playbackState||(W.playbackState={}),W.playbackState.playbackPosition={streamTimeMillis:Z}));I.player.publish("heartbeatRequest",W);const w={timeout:3E4,onSuccess:l=>{if(!I.J.isActive()&&HB(I)){var d=I.getVideoData(),K=d.IJ&&I.C==null;d.IJ=!!l.heartbeatAttestationConfig?.requiresAttestation||K;K=l.playabilityStatus;var v=JSON.stringify(K)||"{}";l.authenticationMismatch&&I.player.EJ("authshear",
{});var c=-1;var u=l.playabilityStatus;u&&(g.Of(I.player,"onHeartbeat",u),u.status==="OK"?c=l.stopHeartbeat?2:0:u.status==="UNPLAYABLE"?c=1:u.status==="LIVE_STREAM_OFFLINE"&&(c=0));I.sequenceNumber&&c===-1||I.G.reset();I.sequenceNumber++;l.heartbeatServerData&&(I.wk=l.heartbeatServerData);d.Pt=l;(u=l.playerCueRangeSet)&&g.Mx(d,u);l.playerCueRanges&&l.playerCueRanges.length>0&&(d.cueRanges=l.playerCueRanges);l.progressBarConfig?.progressBarStartPosition&&l.progressBarConfig?.progressBarEndPosition&&
(d.progressBarStartPosition=l.progressBarConfig.progressBarStartPosition,d.progressBarEndPosition=l.progressBarConfig.progressBarEndPosition);d.compositeLiveIngestionOffsetToken=l.compositeLiveIngestionOffsetToken;l.compositeLiveStatusToken!==d.compositeLiveStatusToken&&(d.compositeLiveStatusToken=l.compositeLiveStatusToken);d.heartbeatLoggingToken=l.heartbeatLoggingToken;d.publish("dataupdated");GQ6(I,l,K,v,c)}},
onError:l=>{HB(I)&&cB(I,!0,`net-${l.status}`)},
onTimeout:()=>{HB(I)&&cB(I,!0,"timeout")}};
g.vI(U,t.V()).then(l=>{l&&(w.t_=`Bearer ${l}`);g.PL(I.on,"player/heartbeat",W,w)})},eQL=function(I){return(I=I.player.getProgressState(I.getPlayerType()).ingestionTime)&&isFinite(I)?`${Math.floor(I*1E3)}`:null},bhV=function(I){return(I=I.player.getCurrentTime(I.getPlayerType()))&&isFinite(I)?`${Math.floor(I*1E3)}`:null},GQ6=function(I,U,t,W,E){E===-1?(t=`decode ${g.Df(W,3)}`,cB(I,!1,t)):E===2?(Kv(I),I.T=!0):(I.U=0,I.J.stop(),E===1?(I.T=!1,t&&t.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&I.player.Ge(!0),
E=`pe.${t?.errorCode};ps.${t?.status}`,I.player.g8("heartbeat.stop",2,I.pJ(W),E),g.hu("heartbeatActionPlayerHalted",Bjk(t)),U?.videoTransitionEndpoint&&t&&(U=U.videoTransitionEndpoint,(W=g.Q(U,g.VJ))&&dk(I,W,t,{itct:U?.clickTrackingParams}))):(I.T=!0,W=0,I.A&&t&&(W=DNV(I,U,t),I.player.publish("livestatedata",t)),W?wk(I,W):wk(I)))},cB=function(I,U,t){if(!I.J.isActive()){I.J.stop();
I.U++;var W=U?"heartbeat.net":"heartbeat.servererror";{const Z=I.getVideoData();if(Z.hv||U&&!g.Qn(I.getVideoData())&&!vB(I)&&Z.isLivePlayback)var E=!1;else I.heartbeatParams?.retries?E=I.heartbeatParams.retries:E=Z.ZA||5,E=I.U>=E}E?(g.hu("heartbeatActionPlayerHalted",U?{enforcedPolicyToHaltOnNetworkFailure:!0}:Bjk()),(U=I.getVideoData())&&U.isLivePlayback?I.player.g8(W,1,"Video playback interrupted. Please try again.",t):I.player.g8(W,1,"Sorry, there was an error licensing this video.",t)):(wk(I,
I.G.getValue()),g.UK(I.G))}},Bjk=function(I){const U={enforcedPolicyToHaltOnNetworkFailure:!1};
I&&(U.serializedServerContext=I.additionalLoggingData);return U},ihw=function(I,U){return(I=Number(I?.pollDelayMs))?I:(U=Number(U?.pollDelayMs))?U:0},dk=function(I,U,t,W){const E=U&&U.videoId;
return E?(I.player.fb(E,{autonav:"1",...(W||{})},void 0,!0,!0,U,I.getVideoData().V()),I.Na("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",t),!0):!1},Tjw={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},$x=Tjw;$x=Tjw;
var ock=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],RQk={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.F=WB.prototype;g.F.hm=$x.FIRSTDAYOFWEEK;g.F.GF=$x.FIRSTWEEKCUTOFFDAY;
g.F.clone=function(){const I=new WB(this.date);I.hm=this.hm;I.GF=this.GF;return I};
g.F.getFullYear=function(){return this.date.getFullYear()};
g.F.getYear=function(){return this.getFullYear()};
g.F.getMonth=function(){return this.date.getMonth()};
g.F.getDate=function(){return this.date.getDate()};
g.F.getTime=function(){return this.date.getTime()};
g.F.getDay=function(){return this.date.getDay()};
g.F.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.F.getUTCMonth=function(){return this.date.getUTCMonth()};
g.F.getUTCDate=function(){return this.date.getUTCDate()};
g.F.getUTCDay=function(){return this.date.getDay()};
g.F.getUTCHours=function(){return this.date.getUTCHours()};
g.F.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.F.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.F.set=function(I){this.date=new Date(I.getFullYear(),I.getMonth(),I.getDate())};
g.F.setFullYear=function(I){this.date.setFullYear(I)};
g.F.setYear=function(I){this.setFullYear(I)};
g.F.setMonth=function(I){this.date.setMonth(I)};
g.F.setDate=function(I){this.date.setDate(I)};
g.F.setTime=function(I){this.date.setTime(I)};
g.F.setUTCFullYear=function(I){this.date.setUTCFullYear(I)};
g.F.setUTCMonth=function(I){this.date.setUTCMonth(I)};
g.F.setUTCDate=function(I){this.date.setUTCDate(I)};
g.F.add=function(I){if(I.years||I.months){var U=this.getMonth()+I.months+I.years*12,t=this.getYear()+Math.floor(U/12);U%=12;U<0&&(U+=12);a:{switch(U){case 1:var W=t%4!=0||t%100==0&&t%400!=0?28:29;break a;case 5:case 8:case 10:case 3:W=30;break a}W=31}W=Math.min(W,this.getDate());this.setDate(1);this.setFullYear(t);this.setMonth(U);this.setDate(W)}I.days&&(t=this.getYear(),U=t>=0&&t<=99?-1900:0,I=new Date((new Date(t,this.getMonth(),this.getDate(),12)).getTime()+I.days*864E5),this.setDate(1),this.setFullYear(I.getFullYear()+
U),this.setMonth(I.getMonth()),this.setDate(I.getDate()),tF(this,I.getDate()))};
g.F.equals=function(I){return!(!I||this.getYear()!=I.getYear()||this.getMonth()!=I.getMonth()||this.getDate()!=I.getDate())};
g.F.toString=function(){var I=this.getFullYear();const U=I<0?"-":I>=1E4?"+":"";return[U+UA(Math.abs(I),U?6:4),UA(this.getMonth()+1,2),UA(this.getDate(),2)].join("")+""};
g.F.valueOf=function(){return this.date.valueOf()};var gcQ=new g.P("addUpcomingEventReminderEndpoint");var COL=new g.P("removeUpcomingEventReminderEndpoint");var Ohx=class extends g.V{constructor(I){super({X:"div",j:[{X:"button",fl:["ytp-offline-slate-button","ytp-button"],j:[{X:"div",Y:"ytp-offline-slate-button-icon",Fe:"{{icon}}"},{X:"div",Y:"ytp-offline-slate-button-text",Fe:"{{text}}"}]}]});this.Z=I;this.B=this.toggleButtonRenderer=null;(this.J=this.e6("ytp-offline-slate-button"))&&this.L(this.J,"click",this.D);this.hide()}D(){if(this.toggleButtonRenderer){const I=this.toggleButtonRenderer;I.isToggled?F8k(this,I.toggledServiceEndpoint):F8k(this,I.defaultServiceEndpoint);
I.isToggled=!I.isToggled;EA(this)}}};var XUw=class extends g.V{constructor(I){super({X:"div",Y:"ytp-offline-slate",j:[{X:"div",Y:"ytp-offline-slate-background"},{X:"div",Y:"ytp-offline-slate-bar",j:[{X:"span",Y:"ytp-offline-slate-icon",j:[{X:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},j:[{X:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{X:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{X:"span",Y:"ytp-offline-slate-messages",j:[{X:"div",Y:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},Fe:"{{mainText}}"},{X:"div",Y:"ytp-offline-slate-subtitle-text",Fe:"{{subtitleText}}"}]},{X:"span",Y:"ytp-offline-slate-buttons"}]},{X:"button",fl:["ytp-offline-slate-close-button","ytp-button"],j:[g.up()]},{X:"button",fl:["ytp-offline-slate-open-button","ytp-button"],j:[g.$Z()]}]});this.api=I;this.B=this.J=null;this.background=this.e6("ytp-offline-slate-background");
this.D=this.e6("ytp-offline-slate-bar");this.T=new g.bP(()=>{g.MV(this.D,"ytp-offline-slate-bar-fade")},15E3);
this.G=!1;this.A=new g.bP(()=>{g.MV(this.element,"ytp-offline-slate-collapsed")},15E3);
g.J(this,this.A);g.J(this,this.T);this.countdownTimer=new g.bP(this.V,1E3,this);this.L(I,"presentingplayerstatechange",this.U);this.L(I,"livestatedata",this.YA);this.L(this.e6("ytp-offline-slate-close-button"),"click",()=>{g.MV(this.element,"ytp-offline-slate-collapsed")});
this.L(this.e6("ytp-offline-slate-open-button"),"click",()=>{g.Ih(this.element,"ytp-offline-slate-collapsed")});
this.hide();I=this.getVideoData();I.getPlayerResponse()&&(I=I.getPlayerResponse().playabilityStatus)&&this.YA(I);I=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Y1;const U=this.api.getPresentingPlayerType()===8;g.D(this.element,"ytp-offline-slate-premiere-trailer",I);g.D(this.element,"ytp-offline-slate-hide-background",U)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}YA(I){var U=I?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(U){this.J=I;U=U.liveStreamOfflineSlateRenderer;U.canShowCountdown?this.V():ZT(this,U);var t=I?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(t){let W=0,E=null;t=t.thumbnails;for(let Z=0;Z<t.length;Z++)t[Z].width>W&&(W=t[Z].width||0,E=t[Z].url);E&&(this.background.style.backgroundImage=`url(${E})`)}else this.background.style.backgroundImage="";U.actionButtons?(this.B||(this.B=new Ohx(this.api),this.B.As(this.e6("ytp-offline-slate-buttons")),
g.J(this,this.B)),mNx(this.B,U.actionButtons&&U.actionButtons[0])):this.B&&mNx(this.B,null);this.J=I}else this.J=null;this.U()}U(I){if(this.api.getPresentingPlayerType()===8)var U=!0;else{var t=this.api.getPlayerStateObject(),W=this.getVideoData();U=W.isLivePlayback&&(t.isBuffering()||t.B(2)||t.B(64));var E=W.autonavState===2&&t.B(2);t=t.isPlaying()&&!g.aT(W)&&!this.api.isAtLiveHead(void 0,!0);U=U&&!t&&!E}U&&this.J?this.lU?I?.dS(2)&&!this.getVideoData().Y1&&(g.Ih(this.element,"ytp-offline-slate-collapsed"),
this.A.stop(),g.Ih(this.D,"ytp-offline-slate-bar-fade"),this.T.start()):(this.show(),this.A.start(),this.api.publish("offlineslatestatechange"),this.G&&this.api.EE()):this.lU&&(this.hide(),this.api.publish("offlineslatestatechange"))}V(){const I=this.J?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(I){var U=Math.floor(g.UH()/1E3),t=I.canShowCountdown&&Number(I.scheduledStartTime);!t||t<=U?(ZT(this,I),this.countdownTimer.stop()):(ZT(this,I,g.e4(t-U)),
this.countdownTimer.cL())}}b0(){this.countdownTimer.dispose();this.countdownTimer=null;super.b0()}};var kQH=class{constructor(I,U){var t=(0,g.q)();this.trigger=I;this.B=U;this.D=t}J(I){return this.trigger&&I.trigger?this.trigger===I.trigger&&this.B===I.B:!1}isExpired(){return(0,g.q)()-this.D>6E4}toString(){return`${"heartbeat"}:${this.trigger}:${this.B}`}};var rBx=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.g7("heartbeat",class extends g.p0{constructor(I){super(I);this.V=!1;this.U=0;this.T=!1;this.J=new g.bP(()=>{NjQ(this)},0);
this.B=this.heartbeatParams=null;this.A=!1;this.G=new g.Im(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.on=new g.uh(void 0);this.attestationResponse=Promise.resolve(void 0);this.C=Promise.resolve(void 0);this.utcOffsetMinutes=-(new WB).getTimezoneOffset();this.D=new g.E9(this);g.J(this,this.J);g.J(this,this.D);sAV(this);YGf(this);this.D.L(I,"heartbeatparams",this.FU);this.D.L(I,"presentingplayerstatechange",this.mu);this.D.L(I,"videoplayerreset",this.N);this.D.L(I,g.EZ("heartbeat"),
this.onCueRangeEnter);this.A&&this.B&&DNV(this,void 0,this.B);const U=new g.jd(lB(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),t=new g.jd(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});I.d8([U,t]);xNQ(this)}b0(){Kv(this);this.player.RW("heartbeat");super.b0()}onCueRangeEnter(){this.V=!0;wk(this,lB(this))}FU(I){this.heartbeatParams=I;wk(this,lB(this))}mu(I){if(this.player.getPresentingPlayerType()!==8&&this.B?.status!=="UNPLAYABLE")if(I.state.B(2)||
I.state.B(64))Kv(this),this.A&&(this.V=!0,wk(this,lB(this,!0)));else{const U=this.player.S().experiments.Wo().B.OJ(g.Bdm);(I.state.B(1)||I.state.B(8)||U&&I.state.B(4))&&wk(this,lB(this))}}N(){this.player.getPresentingPlayerType()!==3&&wk(this,lB(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}l6(I){switch(I){case 4:case 3:return!1}return!0}Na(I,U,t){I={trigger:I,reason:U};t&&(I.serializedServerContext=
t.additionalLoggingData);g.hu("heartbeatActionPlayerTransitioned",I)}pJ(I){var U="LICENSE";const t=ffk(I);if(t)return t.reason||g.r7[U]||"";if(I=I.match(rBx))if(I=Number(I[1]))U=(U=RQk[I.toString()])?U:"LICENSE";return g.r7[U]||""}I_(){return!!this.offlineSlate&&this.offlineSlate.lU}});})(_yt_player);
